// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/semantic.proto

/*
Package semantic is a generated protocol buffer package.

It is generated from these files:
	grr/proto/semantic.proto

It has these top-level messages:
	SemanticDescriptor
	SemanticMessageDescriptor
*/
package semantic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SemanticDescriptor_Labels int32

const (
	SemanticDescriptor_ADVANCED SemanticDescriptor_Labels = 1
	// only.
	SemanticDescriptor_HIDDEN SemanticDescriptor_Labels = 2
)

var SemanticDescriptor_Labels_name = map[int32]string{
	1: "ADVANCED",
	2: "HIDDEN",
}
var SemanticDescriptor_Labels_value = map[string]int32{
	"ADVANCED": 1,
	"HIDDEN":   2,
}

func (x SemanticDescriptor_Labels) Enum() *SemanticDescriptor_Labels {
	p := new(SemanticDescriptor_Labels)
	*p = x
	return p
}
func (x SemanticDescriptor_Labels) String() string {
	return proto.EnumName(SemanticDescriptor_Labels_name, int32(x))
}
func (x *SemanticDescriptor_Labels) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SemanticDescriptor_Labels_value, data, "SemanticDescriptor_Labels")
	if err != nil {
		return err
	}
	*x = SemanticDescriptor_Labels(value)
	return nil
}
func (SemanticDescriptor_Labels) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type SemanticDescriptor struct {
	// The semantic name of the SemanticValue contained in this field.
	Type *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// The type of this field can be specified dynamically. This is the name of
	// the attribute to use to retrieve the SemanticValue class to be used for
	// parsing this field.
	DynamicType *string                     `protobuf:"bytes,5,opt,name=dynamic_type,json=dynamicType" json:"dynamic_type,omitempty"`
	Description *string                     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Label       []SemanticDescriptor_Labels `protobuf:"varint,3,rep,name=label,enum=SemanticDescriptor_Labels" json:"label,omitempty"`
	// A friendly name for this field - to be used in GUIs etc.
	FriendlyName     *string `protobuf:"bytes,4,opt,name=friendly_name,json=friendlyName" json:"friendly_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SemanticDescriptor) Reset()                    { *m = SemanticDescriptor{} }
func (m *SemanticDescriptor) String() string            { return proto.CompactTextString(m) }
func (*SemanticDescriptor) ProtoMessage()               {}
func (*SemanticDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SemanticDescriptor) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *SemanticDescriptor) GetDynamicType() string {
	if m != nil && m.DynamicType != nil {
		return *m.DynamicType
	}
	return ""
}

func (m *SemanticDescriptor) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *SemanticDescriptor) GetLabel() []SemanticDescriptor_Labels {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *SemanticDescriptor) GetFriendlyName() string {
	if m != nil && m.FriendlyName != nil {
		return *m.FriendlyName
	}
	return ""
}

type SemanticMessageDescriptor struct {
	// Describe the purpose of this protobuf.
	Description *string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// Certain RDFValues have union-like semantics. I.e. they are essentially
	// selectors of a number of other predefined RDFValues. They have a single
	// field that identifies the type of the selected "subvalue" and
	// nested fields corresponding to different selections. For examples:
	//
	// message FileFinderFilter {
	//   option (semantic) = {
	//     union_field: "filter_type"
	//   };
	//   enum Type {
	//     MODIFICATION_TIME = 0 [(description) = "Modification time"];
	//     ACCESS_TIME = 1 [(description) = "Access time"];
	//   }
	//
	//   optional Type filter_type = 1;
	//   optional FileFinderModificationTimeFilter modification_time = 2;
	//   optional FileFinderAccessTimeFilter access_time = 3;
	// }
	//
	// Field specified in union_field is used to determine which nested fields is
	// actually used. Field identified by union_field has to be Enum.
	// Corresponding nested values have to have names equal to enum values names,
	// but in lower case.
	//
	// At the moment setting union_field attribute on an RDFValue only affects the
	// UI rendering. RDFValues with union_field set are rendered with a select
	// box that allows users to switch between different available types.
	//
	// TODO(user): Suggestion from bgalehouse: We can just have "is_union"
	// boolean attribute instead of a string "union_field", because for
	// union-like structures we can understand the type of the structure by
	// inspecting its data fields.
	UnionField       *string `protobuf:"bytes,2,opt,name=union_field,json=unionField" json:"union_field,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SemanticMessageDescriptor) Reset()                    { *m = SemanticMessageDescriptor{} }
func (m *SemanticMessageDescriptor) String() string            { return proto.CompactTextString(m) }
func (*SemanticMessageDescriptor) ProtoMessage()               {}
func (*SemanticMessageDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SemanticMessageDescriptor) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *SemanticMessageDescriptor) GetUnionField() string {
	if m != nil && m.UnionField != nil {
		return *m.UnionField
	}
	return ""
}

var E_SemType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*SemanticDescriptor)(nil),
	Field:         51584972,
	Name:          "sem_type",
	Tag:           "bytes,51584972,opt,name=sem_type,json=semType",
	Filename:      "grr/proto/semantic.proto",
}

var E_Semantic = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*SemanticMessageDescriptor)(nil),
	Field:         51584971,
	Name:          "semantic",
	Tag:           "bytes,51584971,opt,name=semantic",
	Filename:      "grr/proto/semantic.proto",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         48651165,
	Name:          "description",
	Tag:           "bytes,48651165,opt,name=description",
	Filename:      "grr/proto/semantic.proto",
}

var E_Label = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: ([]SemanticDescriptor_Labels)(nil),
	Field:         48651166,
	Name:          "label",
	Tag:           "varint,48651166,rep,name=label,enum=SemanticDescriptor_Labels",
	Filename:      "grr/proto/semantic.proto",
}

func init() {
	proto.RegisterType((*SemanticDescriptor)(nil), "SemanticDescriptor")
	proto.RegisterType((*SemanticMessageDescriptor)(nil), "SemanticMessageDescriptor")
	proto.RegisterEnum("SemanticDescriptor_Labels", SemanticDescriptor_Labels_name, SemanticDescriptor_Labels_value)
	proto.RegisterExtension(E_SemType)
	proto.RegisterExtension(E_Semantic)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Label)
}

func init() { proto.RegisterFile("grr/proto/semantic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0xea, 0x40,
	0x18, 0xc5, 0x53, 0xfe, 0x5d, 0xee, 0x57, 0xee, 0x0d, 0x99, 0xbb, 0xb8, 0x95, 0xc4, 0x50, 0xea,
	0x86, 0x55, 0x31, 0x2c, 0xbb, 0x23, 0x16, 0xa2, 0x89, 0xa2, 0xa9, 0x86, 0x85, 0x0b, 0xc9, 0x40,
	0x87, 0x66, 0x92, 0xce, 0x0c, 0xe9, 0xb4, 0x0b, 0x1e, 0xc5, 0x85, 0xbe, 0x86, 0x4b, 0x1f, 0x40,
	0x1e, 0xc4, 0xc7, 0x30, 0x9d, 0xb6, 0xa0, 0xd6, 0x05, 0xbb, 0xf6, 0x3b, 0x67, 0x7e, 0xdf, 0x9c,
	0x33, 0x60, 0x04, 0x51, 0x34, 0x58, 0x47, 0x22, 0x16, 0x03, 0x49, 0x18, 0xe6, 0x31, 0x5d, 0xda,
	0xea, 0xb7, 0x63, 0x06, 0x42, 0x04, 0x21, 0xc9, 0xc4, 0x45, 0xb2, 0x1a, 0xf8, 0x44, 0x2e, 0x23,
	0xba, 0x8e, 0x45, 0x94, 0x39, 0xac, 0x77, 0x0d, 0xd0, 0x6d, 0x7e, 0xc8, 0xdd, 0x89, 0x08, 0x41,
	0x2d, 0xde, 0xac, 0x89, 0xa1, 0x99, 0x5a, 0xff, 0xb7, 0xa7, 0xbe, 0x51, 0x0f, 0x5a, 0xfe, 0x86,
	0x63, 0x46, 0x97, 0x73, 0xa5, 0xd5, 0x95, 0xa6, 0xe7, 0xb3, 0xbb, 0xd4, 0x62, 0x82, 0x5e, 0x6c,
	0xa0, 0x82, 0x1b, 0x95, 0xdc, 0xb1, 0x1f, 0xa1, 0x53, 0xa8, 0x87, 0x78, 0x41, 0x42, 0xa3, 0x6a,
	0x56, 0xfb, 0x7f, 0x87, 0x1d, 0xbb, 0xbc, 0xdc, 0xbe, 0x4c, 0x0d, 0xd2, 0xcb, 0x8c, 0xe8, 0x04,
	0xfe, 0xac, 0x22, 0x4a, 0xb8, 0x1f, 0x6e, 0xe6, 0x1c, 0x33, 0x62, 0xd4, 0x14, 0xb5, 0x55, 0x0c,
	0xa7, 0x98, 0x11, 0xcb, 0x82, 0x46, 0x76, 0x0a, 0xb5, 0xa0, 0x39, 0x72, 0x67, 0xa3, 0xe9, 0xd9,
	0xd8, 0x6d, 0x6b, 0x08, 0xa0, 0x71, 0x7e, 0xe1, 0xba, 0xe3, 0x69, 0xbb, 0x62, 0x3d, 0xc0, 0x51,
	0xb1, 0xec, 0x8a, 0x48, 0x89, 0x03, 0xf2, 0x29, 0xf0, 0xb7, 0x9b, 0x6b, 0xe5, 0x9b, 0x77, 0x41,
	0x4f, 0x38, 0x15, 0x7c, 0xbe, 0xa2, 0x24, 0xf4, 0xf3, 0x6c, 0xa0, 0x46, 0x93, 0x74, 0xe2, 0xdc,
	0x40, 0x53, 0x12, 0xa6, 0xba, 0x41, 0xc7, 0x76, 0xd6, 0xbc, 0x5d, 0x34, 0x6f, 0x2b, 0xcf, 0xb5,
	0x42, 0x49, 0x63, 0xfb, 0xba, 0x35, 0x4c, 0xad, 0xaf, 0x0f, 0xff, 0xfd, 0x90, 0xdf, 0xfb, 0x25,
	0x09, 0x4b, 0xeb, 0x74, 0xee, 0x15, 0x51, 0xc9, 0xa8, 0x5b, 0x22, 0xe6, 0x21, 0x0a, 0xe6, 0x5b,
	0xc1, 0xdc, 0x77, 0x5a, 0x8a, 0xe9, 0xed, 0x78, 0xce, 0xe4, 0x4b, 0x60, 0xd4, 0x2b, 0xe1, 0xc7,
	0x3c, 0x61, 0x33, 0x1c, 0x26, 0xbb, 0x05, 0x4f, 0x2f, 0x8f, 0xff, 0x4b, 0xb5, 0x38, 0xb3, 0xfc,
	0x41, 0x0f, 0x21, 0x3c, 0xa7, 0x84, 0xc3, 0x9e, 0xfd, 0x23, 0x00, 0x00, 0xff, 0xff, 0x06, 0x48,
	0x85, 0x1d, 0xd5, 0x02, 0x00, 0x00,
}
