// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/client.proto

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/client.proto

It has these top-level messages:
	ApiClient
	ApiClientActionRequest
	ApiSearchClientsArgs
	ApiSearchClientsResult
	ApiGetClientArgs
	ApiGetClientVersionTimesArgs
	ApiGetClientVersionTimesResult
	ApiInterrogateClientArgs
	ApiInterrogateClientResult
	ApiGetInterrogateOperationStateArgs
	ApiGetInterrogateOperationStateResult
	ApiGetLastClientIPAddressArgs
	ApiGetLastClientIPAddressResult
	ApiListClientCrashesArgs
	ApiListClientCrashesResult
	ApiAddClientsLabelsArgs
	ApiRemoveClientsLabelsArgs
	ApiListClientsLabelsResult
	ApiListKbFieldsResult
	ApiGetClientLoadStatsArgs
	ApiGetClientLoadStatsResult
	ApiListClientActionRequestsArgs
	ApiListClientActionRequestsResult
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stats "github.com/google/grr_go_api_client/grrproto/grr/proto/api/stats_proto"
import jobs "github.com/google/grr_go_api_client/grrproto/grr/proto/jobs_proto"
import knowledge_base "github.com/google/grr_go_api_client/grrproto/grr/proto/knowledge_base_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"
import sysinfo "github.com/google/grr_go_api_client/grrproto/grr/proto/sysinfo_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiGetInterrogateOperationStateResult_State int32

const (
	ApiGetInterrogateOperationStateResult_RUNNING  ApiGetInterrogateOperationStateResult_State = 0
	ApiGetInterrogateOperationStateResult_FINISHED ApiGetInterrogateOperationStateResult_State = 1
)

var ApiGetInterrogateOperationStateResult_State_name = map[int32]string{
	0: "RUNNING",
	1: "FINISHED",
}
var ApiGetInterrogateOperationStateResult_State_value = map[string]int32{
	"RUNNING":  0,
	"FINISHED": 1,
}

func (x ApiGetInterrogateOperationStateResult_State) Enum() *ApiGetInterrogateOperationStateResult_State {
	p := new(ApiGetInterrogateOperationStateResult_State)
	*p = x
	return p
}
func (x ApiGetInterrogateOperationStateResult_State) String() string {
	return proto.EnumName(ApiGetInterrogateOperationStateResult_State_name, int32(x))
}
func (x *ApiGetInterrogateOperationStateResult_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetInterrogateOperationStateResult_State_value, data, "ApiGetInterrogateOperationStateResult_State")
	if err != nil {
		return err
	}
	*x = ApiGetInterrogateOperationStateResult_State(value)
	return nil
}
func (ApiGetInterrogateOperationStateResult_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type ApiGetLastClientIPAddressResult_Status int32

const (
	ApiGetLastClientIPAddressResult_UNKNOWN  ApiGetLastClientIPAddressResult_Status = 0
	ApiGetLastClientIPAddressResult_INTERNAL ApiGetLastClientIPAddressResult_Status = 1
	ApiGetLastClientIPAddressResult_EXTERNAL ApiGetLastClientIPAddressResult_Status = 2
	ApiGetLastClientIPAddressResult_VPN      ApiGetLastClientIPAddressResult_Status = 3
)

var ApiGetLastClientIPAddressResult_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "INTERNAL",
	2: "EXTERNAL",
	3: "VPN",
}
var ApiGetLastClientIPAddressResult_Status_value = map[string]int32{
	"UNKNOWN":  0,
	"INTERNAL": 1,
	"EXTERNAL": 2,
	"VPN":      3,
}

func (x ApiGetLastClientIPAddressResult_Status) Enum() *ApiGetLastClientIPAddressResult_Status {
	p := new(ApiGetLastClientIPAddressResult_Status)
	*p = x
	return p
}
func (x ApiGetLastClientIPAddressResult_Status) String() string {
	return proto.EnumName(ApiGetLastClientIPAddressResult_Status_name, int32(x))
}
func (x *ApiGetLastClientIPAddressResult_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetLastClientIPAddressResult_Status_value, data, "ApiGetLastClientIPAddressResult_Status")
	if err != nil {
		return err
	}
	*x = ApiGetLastClientIPAddressResult_Status(value)
	return nil
}
func (ApiGetLastClientIPAddressResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

type ApiGetClientLoadStatsArgs_Metric int32

const (
	ApiGetClientLoadStatsArgs_CPU_PERCENT            ApiGetClientLoadStatsArgs_Metric = 0
	ApiGetClientLoadStatsArgs_CPU_SYSTEM             ApiGetClientLoadStatsArgs_Metric = 1
	ApiGetClientLoadStatsArgs_CPU_USER               ApiGetClientLoadStatsArgs_Metric = 2
	ApiGetClientLoadStatsArgs_IO_READ_BYTES          ApiGetClientLoadStatsArgs_Metric = 3
	ApiGetClientLoadStatsArgs_IO_WRITE_BYTES         ApiGetClientLoadStatsArgs_Metric = 4
	ApiGetClientLoadStatsArgs_IO_READ_OPS            ApiGetClientLoadStatsArgs_Metric = 5
	ApiGetClientLoadStatsArgs_IO_WRITE_OPS           ApiGetClientLoadStatsArgs_Metric = 6
	ApiGetClientLoadStatsArgs_NETWORK_BYTES_RECEIVED ApiGetClientLoadStatsArgs_Metric = 7
	ApiGetClientLoadStatsArgs_NETWORK_BYTES_SENT     ApiGetClientLoadStatsArgs_Metric = 8
	ApiGetClientLoadStatsArgs_MEMORY_PERCENT         ApiGetClientLoadStatsArgs_Metric = 9
	ApiGetClientLoadStatsArgs_MEMORY_RSS_SIZE        ApiGetClientLoadStatsArgs_Metric = 10
	ApiGetClientLoadStatsArgs_MEMORY_VMS_SIZE        ApiGetClientLoadStatsArgs_Metric = 11
)

var ApiGetClientLoadStatsArgs_Metric_name = map[int32]string{
	0:  "CPU_PERCENT",
	1:  "CPU_SYSTEM",
	2:  "CPU_USER",
	3:  "IO_READ_BYTES",
	4:  "IO_WRITE_BYTES",
	5:  "IO_READ_OPS",
	6:  "IO_WRITE_OPS",
	7:  "NETWORK_BYTES_RECEIVED",
	8:  "NETWORK_BYTES_SENT",
	9:  "MEMORY_PERCENT",
	10: "MEMORY_RSS_SIZE",
	11: "MEMORY_VMS_SIZE",
}
var ApiGetClientLoadStatsArgs_Metric_value = map[string]int32{
	"CPU_PERCENT":            0,
	"CPU_SYSTEM":             1,
	"CPU_USER":               2,
	"IO_READ_BYTES":          3,
	"IO_WRITE_BYTES":         4,
	"IO_READ_OPS":            5,
	"IO_WRITE_OPS":           6,
	"NETWORK_BYTES_RECEIVED": 7,
	"NETWORK_BYTES_SENT":     8,
	"MEMORY_PERCENT":         9,
	"MEMORY_RSS_SIZE":        10,
	"MEMORY_VMS_SIZE":        11,
}

func (x ApiGetClientLoadStatsArgs_Metric) Enum() *ApiGetClientLoadStatsArgs_Metric {
	p := new(ApiGetClientLoadStatsArgs_Metric)
	*p = x
	return p
}
func (x ApiGetClientLoadStatsArgs_Metric) String() string {
	return proto.EnumName(ApiGetClientLoadStatsArgs_Metric_name, int32(x))
}
func (x *ApiGetClientLoadStatsArgs_Metric) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetClientLoadStatsArgs_Metric_value, data, "ApiGetClientLoadStatsArgs_Metric")
	if err != nil {
		return err
	}
	*x = ApiGetClientLoadStatsArgs_Metric(value)
	return nil
}
func (ApiGetClientLoadStatsArgs_Metric) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19, 0}
}

// Next id: 20
type ApiClient struct {
	ClientId         *string                       `protobuf:"bytes,18,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Urn              *string                       `protobuf:"bytes,1,opt,name=urn" json:"urn,omitempty"`
	AgentInfo        *jobs.ClientInformation       `protobuf:"bytes,2,opt,name=agent_info,json=agentInfo" json:"agent_info,omitempty"`
	HardwareInfo     *sysinfo.HardwareInfo         `protobuf:"bytes,3,opt,name=hardware_info,json=hardwareInfo" json:"hardware_info,omitempty"`
	OsInfo           *jobs.Uname                   `protobuf:"bytes,4,opt,name=os_info,json=osInfo" json:"os_info,omitempty"`
	KnowledgeBase    *knowledge_base.KnowledgeBase `protobuf:"bytes,16,opt,name=knowledge_base,json=knowledgeBase" json:"knowledge_base,omitempty"`
	MemorySize       *uint64                       `protobuf:"varint,17,opt,name=memory_size,json=memorySize" json:"memory_size,omitempty"`
	FirstSeenAt      *uint64                       `protobuf:"varint,6,opt,name=first_seen_at,json=firstSeenAt" json:"first_seen_at,omitempty"`
	LastSeenAt       *uint64                       `protobuf:"varint,7,opt,name=last_seen_at,json=lastSeenAt" json:"last_seen_at,omitempty"`
	LastBootedAt     *uint64                       `protobuf:"varint,8,opt,name=last_booted_at,json=lastBootedAt" json:"last_booted_at,omitempty"`
	LastClock        *uint64                       `protobuf:"varint,9,opt,name=last_clock,json=lastClock" json:"last_clock,omitempty"`
	LastCrashAt      *uint64                       `protobuf:"varint,10,opt,name=last_crash_at,json=lastCrashAt" json:"last_crash_at,omitempty"`
	Labels           []*jobs.AFF4ObjectLabel       `protobuf:"bytes,11,rep,name=labels" json:"labels,omitempty"`
	Interfaces       []*jobs.Interface             `protobuf:"bytes,12,rep,name=interfaces" json:"interfaces,omitempty"`
	Users            []*knowledge_base.User        `protobuf:"bytes,13,rep,name=users" json:"users,omitempty"`
	Volumes          []*sysinfo.Volume             `protobuf:"bytes,14,rep,name=volumes" json:"volumes,omitempty"`
	Age              *uint64                       `protobuf:"varint,15,opt,name=age" json:"age,omitempty"`
	CloudInstance    *jobs.CloudInstance           `protobuf:"bytes,19,opt,name=cloud_instance,json=cloudInstance" json:"cloud_instance,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ApiClient) Reset()                    { *m = ApiClient{} }
func (m *ApiClient) String() string            { return proto.CompactTextString(m) }
func (*ApiClient) ProtoMessage()               {}
func (*ApiClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiClient) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiClient) GetUrn() string {
	if m != nil && m.Urn != nil {
		return *m.Urn
	}
	return ""
}

func (m *ApiClient) GetAgentInfo() *jobs.ClientInformation {
	if m != nil {
		return m.AgentInfo
	}
	return nil
}

func (m *ApiClient) GetHardwareInfo() *sysinfo.HardwareInfo {
	if m != nil {
		return m.HardwareInfo
	}
	return nil
}

func (m *ApiClient) GetOsInfo() *jobs.Uname {
	if m != nil {
		return m.OsInfo
	}
	return nil
}

func (m *ApiClient) GetKnowledgeBase() *knowledge_base.KnowledgeBase {
	if m != nil {
		return m.KnowledgeBase
	}
	return nil
}

func (m *ApiClient) GetMemorySize() uint64 {
	if m != nil && m.MemorySize != nil {
		return *m.MemorySize
	}
	return 0
}

func (m *ApiClient) GetFirstSeenAt() uint64 {
	if m != nil && m.FirstSeenAt != nil {
		return *m.FirstSeenAt
	}
	return 0
}

func (m *ApiClient) GetLastSeenAt() uint64 {
	if m != nil && m.LastSeenAt != nil {
		return *m.LastSeenAt
	}
	return 0
}

func (m *ApiClient) GetLastBootedAt() uint64 {
	if m != nil && m.LastBootedAt != nil {
		return *m.LastBootedAt
	}
	return 0
}

func (m *ApiClient) GetLastClock() uint64 {
	if m != nil && m.LastClock != nil {
		return *m.LastClock
	}
	return 0
}

func (m *ApiClient) GetLastCrashAt() uint64 {
	if m != nil && m.LastCrashAt != nil {
		return *m.LastCrashAt
	}
	return 0
}

func (m *ApiClient) GetLabels() []*jobs.AFF4ObjectLabel {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ApiClient) GetInterfaces() []*jobs.Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *ApiClient) GetUsers() []*knowledge_base.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ApiClient) GetVolumes() []*sysinfo.Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ApiClient) GetAge() uint64 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *ApiClient) GetCloudInstance() *jobs.CloudInstance {
	if m != nil {
		return m.CloudInstance
	}
	return nil
}

type ApiClientActionRequest struct {
	TaskId           *uint64            `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	TaskEta          *uint64            `protobuf:"varint,2,opt,name=task_eta,json=taskEta" json:"task_eta,omitempty"`
	SessionId        *string            `protobuf:"bytes,3,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	ClientAction     *string            `protobuf:"bytes,4,opt,name=client_action,json=clientAction" json:"client_action,omitempty"`
	Responses        []*jobs.GrrMessage `protobuf:"bytes,5,rep,name=responses" json:"responses,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiClientActionRequest) Reset()                    { *m = ApiClientActionRequest{} }
func (m *ApiClientActionRequest) String() string            { return proto.CompactTextString(m) }
func (*ApiClientActionRequest) ProtoMessage()               {}
func (*ApiClientActionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiClientActionRequest) GetTaskId() uint64 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *ApiClientActionRequest) GetTaskEta() uint64 {
	if m != nil && m.TaskEta != nil {
		return *m.TaskEta
	}
	return 0
}

func (m *ApiClientActionRequest) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *ApiClientActionRequest) GetClientAction() string {
	if m != nil && m.ClientAction != nil {
		return *m.ClientAction
	}
	return ""
}

func (m *ApiClientActionRequest) GetResponses() []*jobs.GrrMessage {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ApiSearchClientsArgs struct {
	Query            *string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiSearchClientsArgs) Reset()                    { *m = ApiSearchClientsArgs{} }
func (m *ApiSearchClientsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiSearchClientsArgs) ProtoMessage()               {}
func (*ApiSearchClientsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiSearchClientsArgs) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *ApiSearchClientsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiSearchClientsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiSearchClientsResult struct {
	Items            []*ApiClient `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ApiSearchClientsResult) Reset()                    { *m = ApiSearchClientsResult{} }
func (m *ApiSearchClientsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiSearchClientsResult) ProtoMessage()               {}
func (*ApiSearchClientsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiSearchClientsResult) GetItems() []*ApiClient {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiGetClientArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetClientArgs) Reset()                    { *m = ApiGetClientArgs{} }
func (m *ApiGetClientArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientArgs) ProtoMessage()               {}
func (*ApiGetClientArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiGetClientArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetClientArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiGetClientVersionTimesArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetClientVersionTimesArgs) Reset()                    { *m = ApiGetClientVersionTimesArgs{} }
func (m *ApiGetClientVersionTimesArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientVersionTimesArgs) ProtoMessage()               {}
func (*ApiGetClientVersionTimesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApiGetClientVersionTimesArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

type ApiGetClientVersionTimesResult struct {
	Times            []uint64 `protobuf:"varint,1,rep,name=times" json:"times,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiGetClientVersionTimesResult) Reset()                    { *m = ApiGetClientVersionTimesResult{} }
func (m *ApiGetClientVersionTimesResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientVersionTimesResult) ProtoMessage()               {}
func (*ApiGetClientVersionTimesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ApiGetClientVersionTimesResult) GetTimes() []uint64 {
	if m != nil {
		return m.Times
	}
	return nil
}

type ApiInterrogateClientArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiInterrogateClientArgs) Reset()                    { *m = ApiInterrogateClientArgs{} }
func (m *ApiInterrogateClientArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiInterrogateClientArgs) ProtoMessage()               {}
func (*ApiInterrogateClientArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApiInterrogateClientArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

type ApiInterrogateClientResult struct {
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiInterrogateClientResult) Reset()                    { *m = ApiInterrogateClientResult{} }
func (m *ApiInterrogateClientResult) String() string            { return proto.CompactTextString(m) }
func (*ApiInterrogateClientResult) ProtoMessage()               {}
func (*ApiInterrogateClientResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApiInterrogateClientResult) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetInterrogateOperationStateArgs struct {
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetInterrogateOperationStateArgs) Reset()         { *m = ApiGetInterrogateOperationStateArgs{} }
func (m *ApiGetInterrogateOperationStateArgs) String() string { return proto.CompactTextString(m) }
func (*ApiGetInterrogateOperationStateArgs) ProtoMessage()    {}
func (*ApiGetInterrogateOperationStateArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *ApiGetInterrogateOperationStateArgs) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetInterrogateOperationStateResult struct {
	State            *ApiGetInterrogateOperationStateResult_State `protobuf:"varint,1,opt,name=state,enum=ApiGetInterrogateOperationStateResult_State" json:"state,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *ApiGetInterrogateOperationStateResult) Reset()         { *m = ApiGetInterrogateOperationStateResult{} }
func (m *ApiGetInterrogateOperationStateResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetInterrogateOperationStateResult) ProtoMessage()    {}
func (*ApiGetInterrogateOperationStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10}
}

func (m *ApiGetInterrogateOperationStateResult) GetState() ApiGetInterrogateOperationStateResult_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiGetInterrogateOperationStateResult_RUNNING
}

type ApiGetLastClientIPAddressArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetLastClientIPAddressArgs) Reset()                    { *m = ApiGetLastClientIPAddressArgs{} }
func (m *ApiGetLastClientIPAddressArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetLastClientIPAddressArgs) ProtoMessage()               {}
func (*ApiGetLastClientIPAddressArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiGetLastClientIPAddressArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

type ApiGetLastClientIPAddressResult struct {
	Ip               *string                                 `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Info             *string                                 `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Status           *ApiGetLastClientIPAddressResult_Status `protobuf:"varint,3,opt,name=status,enum=ApiGetLastClientIPAddressResult_Status" json:"status,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *ApiGetLastClientIPAddressResult) Reset()         { *m = ApiGetLastClientIPAddressResult{} }
func (m *ApiGetLastClientIPAddressResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetLastClientIPAddressResult) ProtoMessage()    {}
func (*ApiGetLastClientIPAddressResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

func (m *ApiGetLastClientIPAddressResult) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ApiGetLastClientIPAddressResult) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *ApiGetLastClientIPAddressResult) GetStatus() ApiGetLastClientIPAddressResult_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ApiGetLastClientIPAddressResult_UNKNOWN
}

type ApiListClientCrashesArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListClientCrashesArgs) Reset()                    { *m = ApiListClientCrashesArgs{} }
func (m *ApiListClientCrashesArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListClientCrashesArgs) ProtoMessage()               {}
func (*ApiListClientCrashesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ApiListClientCrashesArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiListClientCrashesArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListClientCrashesArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListClientCrashesArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListClientCrashesResult struct {
	Items            []*jobs.ClientCrash `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64              `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApiListClientCrashesResult) Reset()                    { *m = ApiListClientCrashesResult{} }
func (m *ApiListClientCrashesResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListClientCrashesResult) ProtoMessage()               {}
func (*ApiListClientCrashesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ApiListClientCrashesResult) GetItems() []*jobs.ClientCrash {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListClientCrashesResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiAddClientsLabelsArgs struct {
	ClientIds        []string `protobuf:"bytes,1,rep,name=client_ids,json=clientIds" json:"client_ids,omitempty"`
	Labels           []string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiAddClientsLabelsArgs) Reset()                    { *m = ApiAddClientsLabelsArgs{} }
func (m *ApiAddClientsLabelsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiAddClientsLabelsArgs) ProtoMessage()               {}
func (*ApiAddClientsLabelsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ApiAddClientsLabelsArgs) GetClientIds() []string {
	if m != nil {
		return m.ClientIds
	}
	return nil
}

func (m *ApiAddClientsLabelsArgs) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ApiRemoveClientsLabelsArgs struct {
	ClientIds        []string `protobuf:"bytes,1,rep,name=client_ids,json=clientIds" json:"client_ids,omitempty"`
	Labels           []string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiRemoveClientsLabelsArgs) Reset()                    { *m = ApiRemoveClientsLabelsArgs{} }
func (m *ApiRemoveClientsLabelsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiRemoveClientsLabelsArgs) ProtoMessage()               {}
func (*ApiRemoveClientsLabelsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ApiRemoveClientsLabelsArgs) GetClientIds() []string {
	if m != nil {
		return m.ClientIds
	}
	return nil
}

func (m *ApiRemoveClientsLabelsArgs) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ApiListClientsLabelsResult struct {
	Items            []*jobs.AFF4ObjectLabel `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ApiListClientsLabelsResult) Reset()                    { *m = ApiListClientsLabelsResult{} }
func (m *ApiListClientsLabelsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListClientsLabelsResult) ProtoMessage()               {}
func (*ApiListClientsLabelsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ApiListClientsLabelsResult) GetItems() []*jobs.AFF4ObjectLabel {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiListKbFieldsResult struct {
	Items            []string `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiListKbFieldsResult) Reset()                    { *m = ApiListKbFieldsResult{} }
func (m *ApiListKbFieldsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListKbFieldsResult) ProtoMessage()               {}
func (*ApiListKbFieldsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ApiListKbFieldsResult) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiGetClientLoadStatsArgs struct {
	ClientId         *string                           `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Start            *uint64                           `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End              *uint64                           `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	Metric           *ApiGetClientLoadStatsArgs_Metric `protobuf:"varint,5,opt,name=metric,enum=ApiGetClientLoadStatsArgs_Metric" json:"metric,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *ApiGetClientLoadStatsArgs) Reset()                    { *m = ApiGetClientLoadStatsArgs{} }
func (m *ApiGetClientLoadStatsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientLoadStatsArgs) ProtoMessage()               {}
func (*ApiGetClientLoadStatsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ApiGetClientLoadStatsArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetClientLoadStatsArgs) GetStart() uint64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *ApiGetClientLoadStatsArgs) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func (m *ApiGetClientLoadStatsArgs) GetMetric() ApiGetClientLoadStatsArgs_Metric {
	if m != nil && m.Metric != nil {
		return *m.Metric
	}
	return ApiGetClientLoadStatsArgs_CPU_PERCENT
}

type ApiGetClientLoadStatsResult struct {
	DataPoints       []*stats.ApiStatsStoreMetricDataPoint `protobuf:"bytes,1,rep,name=data_points,json=dataPoints" json:"data_points,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *ApiGetClientLoadStatsResult) Reset()                    { *m = ApiGetClientLoadStatsResult{} }
func (m *ApiGetClientLoadStatsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientLoadStatsResult) ProtoMessage()               {}
func (*ApiGetClientLoadStatsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ApiGetClientLoadStatsResult) GetDataPoints() []*stats.ApiStatsStoreMetricDataPoint {
	if m != nil {
		return m.DataPoints
	}
	return nil
}

type ApiListClientActionRequestsArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FetchResponses   *bool   `protobuf:"varint,2,opt,name=fetch_responses,json=fetchResponses" json:"fetch_responses,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListClientActionRequestsArgs) Reset()         { *m = ApiListClientActionRequestsArgs{} }
func (m *ApiListClientActionRequestsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListClientActionRequestsArgs) ProtoMessage()    {}
func (*ApiListClientActionRequestsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21}
}

func (m *ApiListClientActionRequestsArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiListClientActionRequestsArgs) GetFetchResponses() bool {
	if m != nil && m.FetchResponses != nil {
		return *m.FetchResponses
	}
	return false
}

type ApiListClientActionRequestsResult struct {
	Items            []*ApiClientActionRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ApiListClientActionRequestsResult) Reset()         { *m = ApiListClientActionRequestsResult{} }
func (m *ApiListClientActionRequestsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListClientActionRequestsResult) ProtoMessage()    {}
func (*ApiListClientActionRequestsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *ApiListClientActionRequestsResult) GetItems() []*ApiClientActionRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiClient)(nil), "ApiClient")
	proto.RegisterType((*ApiClientActionRequest)(nil), "ApiClientActionRequest")
	proto.RegisterType((*ApiSearchClientsArgs)(nil), "ApiSearchClientsArgs")
	proto.RegisterType((*ApiSearchClientsResult)(nil), "ApiSearchClientsResult")
	proto.RegisterType((*ApiGetClientArgs)(nil), "ApiGetClientArgs")
	proto.RegisterType((*ApiGetClientVersionTimesArgs)(nil), "ApiGetClientVersionTimesArgs")
	proto.RegisterType((*ApiGetClientVersionTimesResult)(nil), "ApiGetClientVersionTimesResult")
	proto.RegisterType((*ApiInterrogateClientArgs)(nil), "ApiInterrogateClientArgs")
	proto.RegisterType((*ApiInterrogateClientResult)(nil), "ApiInterrogateClientResult")
	proto.RegisterType((*ApiGetInterrogateOperationStateArgs)(nil), "ApiGetInterrogateOperationStateArgs")
	proto.RegisterType((*ApiGetInterrogateOperationStateResult)(nil), "ApiGetInterrogateOperationStateResult")
	proto.RegisterType((*ApiGetLastClientIPAddressArgs)(nil), "ApiGetLastClientIPAddressArgs")
	proto.RegisterType((*ApiGetLastClientIPAddressResult)(nil), "ApiGetLastClientIPAddressResult")
	proto.RegisterType((*ApiListClientCrashesArgs)(nil), "ApiListClientCrashesArgs")
	proto.RegisterType((*ApiListClientCrashesResult)(nil), "ApiListClientCrashesResult")
	proto.RegisterType((*ApiAddClientsLabelsArgs)(nil), "ApiAddClientsLabelsArgs")
	proto.RegisterType((*ApiRemoveClientsLabelsArgs)(nil), "ApiRemoveClientsLabelsArgs")
	proto.RegisterType((*ApiListClientsLabelsResult)(nil), "ApiListClientsLabelsResult")
	proto.RegisterType((*ApiListKbFieldsResult)(nil), "ApiListKbFieldsResult")
	proto.RegisterType((*ApiGetClientLoadStatsArgs)(nil), "ApiGetClientLoadStatsArgs")
	proto.RegisterType((*ApiGetClientLoadStatsResult)(nil), "ApiGetClientLoadStatsResult")
	proto.RegisterType((*ApiListClientActionRequestsArgs)(nil), "ApiListClientActionRequestsArgs")
	proto.RegisterType((*ApiListClientActionRequestsResult)(nil), "ApiListClientActionRequestsResult")
	proto.RegisterEnum("ApiGetInterrogateOperationStateResult_State", ApiGetInterrogateOperationStateResult_State_name, ApiGetInterrogateOperationStateResult_State_value)
	proto.RegisterEnum("ApiGetLastClientIPAddressResult_Status", ApiGetLastClientIPAddressResult_Status_name, ApiGetLastClientIPAddressResult_Status_value)
	proto.RegisterEnum("ApiGetClientLoadStatsArgs_Metric", ApiGetClientLoadStatsArgs_Metric_name, ApiGetClientLoadStatsArgs_Metric_value)
}

func init() { proto.RegisterFile("grr/proto/api/client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x72, 0x1b, 0xb7,
	0xf5, 0x0f, 0x25, 0x91, 0x12, 0x41, 0x49, 0x66, 0x10, 0xc7, 0x66, 0x94, 0xbf, 0x65, 0x78, 0x13,
	0xdb, 0xfa, 0xa7, 0xd6, 0x2a, 0x91, 0x93, 0x74, 0xe2, 0xa6, 0xce, 0x90, 0x12, 0xe5, 0x30, 0x92,
	0x28, 0x15, 0x94, 0xfc, 0xd1, 0x69, 0xca, 0x01, 0x77, 0x41, 0x12, 0xf1, 0x72, 0x41, 0x03, 0x58,
	0xc9, 0x4a, 0x2f, 0x3a, 0xbd, 0x6a, 0xaf, 0x3a, 0xd3, 0xfb, 0x76, 0x3a, 0x7d, 0x8b, 0x5e, 0x76,
	0xda, 0xe6, 0x15, 0xfa, 0x00, 0xed, 0x23, 0xf4, 0xb6, 0x33, 0xed, 0xe0, 0x2c, 0x96, 0x1f, 0x8e,
	0x1d, 0x27, 0x53, 0x4d, 0xef, 0x76, 0xcf, 0xc7, 0xef, 0x1c, 0x9c, 0x83, 0xf3, 0x01, 0xb4, 0xd2,
	0x53, 0x6a, 0x63, 0xa8, 0xa4, 0x91, 0x1b, 0x6c, 0x28, 0x36, 0x82, 0x48, 0xf0, 0xd8, 0xf8, 0x40,
	0x58, 0x79, 0x63, 0x9a, 0xa7, 0x0d, 0x33, 0xda, 0xb1, 0x2e, 0x8e, 0x59, 0x5f, 0xc8, 0x4e, 0x46,
	0x5d, 0x1d, 0x53, 0x1f, 0xc7, 0xf2, 0x34, 0xe2, 0x61, 0x8f, 0xb7, 0x3b, 0x4c, 0x73, 0xc7, 0xaf,
	0x8c, 0xf9, 0x9a, 0x0f, 0x58, 0x6c, 0x44, 0xe0, 0x38, 0x97, 0x27, 0x38, 0x67, 0x5a, 0xc4, 0x5d,
	0x99, 0x32, 0xbc, 0xaf, 0x16, 0x50, 0xb1, 0x3a, 0x14, 0x5b, 0xe0, 0x17, 0xfe, 0x18, 0x15, 0x53,
	0x0f, 0xdb, 0x22, 0xac, 0x60, 0x92, 0x5b, 0x2b, 0xd6, 0xae, 0xfe, 0xfd, 0x5f, 0xff, 0xf8, 0x6b,
	0xee, 0x0d, 0x54, 0x1a, 0x49, 0x35, 0x42, 0x8c, 0xd2, 0x2f, 0x22, 0x42, 0x9f, 0x2e, 0x04, 0x19,
	0xf5, 0x5d, 0x34, 0x9b, 0xa8, 0xb8, 0x92, 0x03, 0xbd, 0x55, 0xd0, 0xab, 0xa0, 0x62, 0x2a, 0x7a,
	0x4c, 0x9b, 0xb8, 0xe4, 0xb4, 0x8e, 0x69, 0xd3, 0xa7, 0x56, 0x14, 0xbf, 0x87, 0x10, 0xeb, 0x81,
	0xb9, 0xb8, 0x2b, 0x2b, 0x33, 0x24, 0xb7, 0x56, 0xda, 0xc4, 0xbe, 0x33, 0x13, 0x77, 0xa5, 0x1a,
	0x30, 0x23, 0x64, 0x4c, 0x8b, 0x20, 0x65, 0x29, 0x78, 0x13, 0x2d, 0xf5, 0x99, 0x0a, 0x4f, 0x99,
	0xe2, 0xa9, 0xd6, 0x2c, 0x68, 0x2d, 0xf9, 0x9f, 0x3a, 0xaa, 0x95, 0xa2, 0x8b, 0xfd, 0x89, 0x3f,
	0x7c, 0x15, 0xcd, 0x4b, 0x9d, 0x4a, 0xcf, 0x81, 0x74, 0xc1, 0x3f, 0x8e, 0xd9, 0x80, 0xd3, 0x82,
	0xd4, 0x20, 0xf0, 0x01, 0x5a, 0x9e, 0x0e, 0x68, 0xa5, 0x0c, 0x72, 0xcb, 0xfe, 0x6e, 0x46, 0xae,
	0x31, 0xcd, 0xe9, 0xd2, 0xe3, 0xc9, 0x5f, 0xdc, 0x42, 0xa5, 0x01, 0x1f, 0x48, 0x75, 0xd6, 0xd6,
	0xe2, 0x4b, 0x5e, 0x79, 0x95, 0xe4, 0xd6, 0xe6, 0x6a, 0x9b, 0x70, 0xf0, 0x5b, 0x68, 0xa1, 0x76,
	0x66, 0x78, 0x4b, 0x7c, 0xc9, 0x31, 0xd9, 0x07, 0x21, 0xc2, 0x4e, 0x98, 0x88, 0x58, 0x27, 0xe2,
	0xc4, 0x48, 0x62, 0xfa, 0x42, 0x13, 0x77, 0x1d, 0x28, 0x4a, 0x61, 0x40, 0xfa, 0x00, 0x2d, 0x75,
	0x85, 0xd2, 0xa6, 0xad, 0x39, 0x8f, 0xdb, 0xcc, 0x54, 0x0a, 0x00, 0xfb, 0x3d, 0x80, 0xbd, 0x8e,
	0x4a, 0x74, 0x7b, 0x67, 0x9b, 0x19, 0x6e, 0xc4, 0x80, 0xe3, 0x4b, 0x0f, 0xfa, 0x3c, 0x26, 0xdd,
	0x48, 0x9e, 0x92, 0x53, 0xa6, 0x49, 0xa0, 0x38, 0x33, 0x3c, 0xf4, 0x69, 0x09, 0x10, 0x5a, 0x9c,
	0xc7, 0x55, 0x83, 0x1f, 0xa2, 0xc5, 0x88, 0x4d, 0xe0, 0xcd, 0x03, 0xde, 0x87, 0x80, 0xf7, 0xee,
	0x34, 0xde, 0xb5, 0x3d, 0xa6, 0x0d, 0xb1, 0x9f, 0xe4, 0xd4, 0x22, 0xa7, 0xfe, 0x91, 0xa0, 0xcf,
	0x83, 0xc7, 0x3c, 0x24, 0x22, 0xf6, 0x29, 0xb2, 0x58, 0x0e, 0xf9, 0x33, 0xb4, 0x0c, 0xc8, 0x1d,
	0x29, 0x0d, 0x0f, 0x2d, 0xf6, 0x02, 0x60, 0xbf, 0x0d, 0xd8, 0xab, 0xd3, 0xd8, 0x17, 0x00, 0xdb,
	0x8a, 0x82, 0x01, 0x9f, 0x82, 0x57, 0x35, 0x50, 0xad, 0x1a, 0xfc, 0x53, 0x04, 0xc8, 0xed, 0x20,
	0x92, 0xc1, 0xe3, 0x4a, 0x11, 0x70, 0x3e, 0x01, 0x9c, 0x8f, 0xa6, 0x71, 0xde, 0x71, 0xb7, 0x08,
	0x04, 0x35, 0x39, 0x61, 0x51, 0xc2, 0x49, 0x98, 0x28, 0x11, 0xf7, 0x48, 0xc4, 0x0c, 0xd7, 0xce,
	0x5f, 0xeb, 0x6c, 0xd1, 0x42, 0x6e, 0x59, 0x41, 0xdc, 0x40, 0x4b, 0x29, 0xbe, 0x62, 0xba, 0x6f,
	0x5d, 0x45, 0x60, 0xe2, 0x3a, 0x98, 0xb8, 0x3a, 0x6d, 0xa2, 0x0c, 0xae, 0x82, 0xa4, 0xf3, 0xb5,
	0x04, 0x40, 0x96, 0x50, 0x35, 0x78, 0x0d, 0x15, 0x22, 0xd6, 0xe1, 0x91, 0xae, 0x94, 0xc8, 0xec,
	0x5a, 0x69, 0xb3, 0xec, 0x57, 0x77, 0x76, 0xde, 0x3f, 0xe8, 0x7c, 0xc1, 0x03, 0xb3, 0x67, 0x19,
	0xd4, 0xf1, 0xf1, 0x3b, 0x08, 0x89, 0xd8, 0x70, 0xd5, 0x65, 0x01, 0xd7, 0x95, 0x45, 0x90, 0x46,
	0x7e, 0x23, 0x23, 0xd1, 0x09, 0x2e, 0x7e, 0x13, 0xe5, 0x13, 0xcd, 0x95, 0xae, 0x2c, 0x81, 0x58,
	0xde, 0x3f, 0xd6, 0x5c, 0xd1, 0x94, 0x86, 0xaf, 0xa1, 0xf9, 0x13, 0x19, 0x25, 0x03, 0xae, 0x2b,
	0xcb, 0xc0, 0x9e, 0xf7, 0xef, 0xc3, 0x3f, 0xcd, 0xe8, 0xb8, 0x8e, 0x66, 0x59, 0x8f, 0x57, 0x2e,
	0xc0, 0xb1, 0x6e, 0xc3, 0xb1, 0xd6, 0xa7, 0x8f, 0xb5, 0x5a, 0xed, 0x71, 0x22, 0xbb, 0xc4, 0xf4,
	0x79, 0x96, 0x59, 0x31, 0x2e, 0x32, 0x9f, 0x5a, 0x7d, 0x5b, 0x0a, 0x41, 0x24, 0x93, 0xb0, 0x2d,
	0x62, 0x6d, 0x58, 0x1c, 0xf0, 0xca, 0x6b, 0xae, 0x14, 0xb6, 0x2c, 0xb9, 0xe1, 0xa8, 0x74, 0x29,
	0x98, 0xfc, 0xf5, 0xfe, 0x3d, 0x83, 0x2e, 0x8d, 0x3a, 0x44, 0x35, 0x80, 0xaa, 0xe5, 0x4f, 0x12,
	0xae, 0x0d, 0xbe, 0x8c, 0xe6, 0x0d, 0xd3, 0x8f, 0x6d, 0x4b, 0xb1, 0xad, 0x61, 0x8e, 0x16, 0xec,
	0x6f, 0x23, 0xc4, 0x14, 0x2d, 0x00, 0x83, 0x1b, 0x06, 0xb5, 0x3f, 0x57, 0xfb, 0x3e, 0xb8, 0xfd,
	0xde, 0xb4, 0xdb, 0xde, 0x91, 0x2d, 0x15, 0x2b, 0x79, 0x53, 0x93, 0x88, 0x33, 0xcd, 0x09, 0x7f,
	0x3a, 0x14, 0x0a, 0xbc, 0x76, 0xf9, 0x01, 0x0b, 0x75, 0xc3, 0xf0, 0x31, 0x42, 0x9a, 0x6b, 0x2d,
	0x64, 0x6c, 0xed, 0xcd, 0x42, 0x2b, 0xca, 0xae, 0x7a, 0x81, 0x6e, 0xef, 0xd8, 0x3e, 0x74, 0xa3,
	0x95, 0x4a, 0x10, 0x11, 0x12, 0xd3, 0x67, 0x86, 0x18, 0x25, 0x7a, 0x3d, 0xae, 0x78, 0x08, 0xa1,
	0x51, 0xa9, 0xdf, 0x3e, 0x2d, 0x3a, 0xa4, 0x46, 0x88, 0x3f, 0x43, 0x4b, 0xae, 0x31, 0x32, 0x38,
	0x1b, 0xf4, 0x91, 0x62, 0x76, 0x7b, 0xf0, 0x15, 0x77, 0x56, 0x1e, 0x66, 0x81, 0x4d, 0xc5, 0x88,
	0xed, 0x32, 0x3e, 0x5d, 0x0c, 0x26, 0xc2, 0x82, 0x8f, 0x51, 0x51, 0x71, 0x3d, 0x94, 0xb1, 0xe6,
	0xba, 0x92, 0x87, 0x6c, 0x96, 0xfc, 0x7b, 0x4a, 0xed, 0x73, 0xad, 0x59, 0x8f, 0xd7, 0xde, 0x01,
	0xd0, 0xb7, 0xb1, 0x47, 0x33, 0x29, 0xf2, 0x24, 0xe1, 0x09, 0x0f, 0x49, 0x57, 0xaa, 0xb4, 0x6f,
	0x8c, 0x5d, 0x1c, 0x21, 0x79, 0x7f, 0x9c, 0x41, 0x17, 0xab, 0x43, 0xd1, 0xe2, 0x4c, 0x05, 0xfd,
	0x34, 0x0f, 0xba, 0xaa, 0x7a, 0x1a, 0xff, 0x3e, 0x87, 0xf2, 0x4f, 0x12, 0xae, 0xce, 0x5c, 0x67,
	0xfe, 0x55, 0x0e, 0x0c, 0xfc, 0x22, 0x87, 0x7f, 0x9e, 0x0a, 0x13, 0xe0, 0x12, 0x6d, 0x6c, 0x0d,
	0xf9, 0xa4, 0xc5, 0x39, 0xe9, 0x73, 0xc5, 0xc1, 0x9c, 0x3e, 0x8b, 0x0d, 0x7b, 0x7a, 0x87, 0xf4,
	0x8d, 0x19, 0xea, 0x3b, 0x1b, 0x1b, 0x3d, 0x61, 0xfa, 0x49, 0xc7, 0x0f, 0xe4, 0x60, 0xa3, 0x27,
	0x65, 0x2f, 0xe2, 0x1b, 0x3d, 0xa5, 0xd6, 0x43, 0x19, 0x6c, 0x74, 0x22, 0xd9, 0xd9, 0x18, 0x30,
	0x6d, 0xb8, 0xda, 0xb0, 0x97, 0xb6, 0x3d, 0x60, 0x71, 0xc2, 0x22, 0x9f, 0x85, 0x32, 0x78, 0x4b,
	0x83, 0x21, 0x11, 0xf7, 0xd6, 0xbb, 0x52, 0xad, 0xb3, 0xf5, 0x34, 0x20, 0x34, 0xf5, 0x0b, 0xdf,
	0x45, 0x05, 0xd9, 0xed, 0x6a, 0x6e, 0xe0, 0x1a, 0xcc, 0xd6, 0x6e, 0x80, 0x83, 0x04, 0xaf, 0xee,
	0xc8, 0x24, 0xce, 0x42, 0xaa, 0x89, 0x36, 0x4c, 0x19, 0x5b, 0xe6, 0xa9, 0xb0, 0x4f, 0x9d, 0x16,
	0xbe, 0x8b, 0xf2, 0x81, 0x4c, 0x62, 0x03, 0xf9, 0x9e, 0xad, 0xad, 0x81, 0xba, 0x87, 0x49, 0x33,
	0x19, 0x74, 0xb8, 0xb2, 0x57, 0xbe, 0x3b, 0x01, 0x64, 0xbb, 0x6f, 0x97, 0x9b, 0xa0, 0xef, 0xd3,
	0x54, 0xcd, 0xbb, 0x03, 0x77, 0x77, 0x2a, 0x72, 0x94, 0xeb, 0x24, 0x32, 0x98, 0xa0, 0xbc, 0x30,
	0x7c, 0xa0, 0x2b, 0x39, 0x57, 0xbb, 0xa3, 0x3b, 0x4e, 0x53, 0x86, 0xf7, 0xbb, 0x1c, 0x2a, 0x57,
	0x87, 0xe2, 0x1e, 0x37, 0xee, 0xee, 0xdb, 0x90, 0x4f, 0xcd, 0xd1, 0xdc, 0x77, 0x9d, 0xa3, 0xbb,
	0xa8, 0x68, 0x6f, 0xb5, 0x36, 0x6c, 0x30, 0x74, 0x85, 0xb1, 0x0e, 0xda, 0x37, 0xa7, 0x0b, 0xa3,
	0x72, 0x94, 0x49, 0x4d, 0x57, 0xb5, 0x4f, 0xc7, 0xfa, 0xde, 0x4f, 0xd0, 0xff, 0x4d, 0xba, 0x77,
	0x9f, 0x2b, 0x7b, 0xa5, 0x41, 0xf3, 0xbf, 0x77, 0xd5, 0xeb, 0xa1, 0xd5, 0x17, 0xa1, 0xbb, 0x08,
	0xd6, 0x51, 0x1e, 0x9c, 0x81, 0x08, 0xce, 0xd5, 0x36, 0x00, 0xfb, 0xff, 0xa7, 0x0f, 0xb2, 0x72,
	0xd4, 0xe7, 0x24, 0x12, 0xda, 0xd8, 0x73, 0x9c, 0xa4, 0x18, 0x50, 0xd8, 0xda, 0xa7, 0xa9, 0xb6,
	0xf7, 0x10, 0x55, 0xaa, 0x43, 0x01, 0x9d, 0x53, 0xc9, 0x1e, 0x33, 0xfc, 0xbc, 0xa2, 0xed, 0x0d,
	0xd0, 0xca, 0xf3, 0x90, 0x9d, 0xfb, 0x07, 0x68, 0x51, 0x0e, 0x79, 0xda, 0x6b, 0xc6, 0xf0, 0xb7,
	0x00, 0xfe, 0x06, 0x7e, 0xdb, 0x3a, 0x2e, 0xc2, 0x2c, 0xfc, 0x62, 0x0c, 0x42, 0x46, 0x5a, 0x3e,
	0x2d, 0x8d, 0xbe, 0x1b, 0xa1, 0x77, 0x82, 0xde, 0x4a, 0x23, 0x36, 0x61, 0xf1, 0x20, 0xe3, 0xb7,
	0x0c, 0x33, 0x1c, 0xce, 0x74, 0xee, 0x76, 0xff, 0x94, 0x43, 0xd7, 0x5f, 0x62, 0xd8, 0x1d, 0x59,
	0xa3, 0xbc, 0x5d, 0x45, 0x39, 0xd8, 0x5c, 0xde, 0xbc, 0xe5, 0x7f, 0x2b, 0x35, 0x1f, 0xbe, 0xb3,
	0xfc, 0xe2, 0x9b, 0xd6, 0x43, 0x80, 0x79, 0x89, 0x93, 0xa9, 0x2d, 0xcf, 0x43, 0x79, 0x00, 0xc0,
	0x25, 0x34, 0x4f, 0x8f, 0x9b, 0xcd, 0x46, 0xf3, 0x5e, 0xf9, 0x15, 0xbc, 0x88, 0x16, 0x76, 0x1a,
	0xcd, 0x46, 0xeb, 0xd3, 0xfa, 0x76, 0x39, 0xe7, 0x7d, 0x8e, 0xae, 0xa4, 0xae, 0xec, 0xc1, 0x54,
	0x87, 0xfc, 0x1d, 0x56, 0xc3, 0x50, 0x71, 0x7d, 0x1e, 0x77, 0xf9, 0x6f, 0x33, 0xe8, 0xea, 0x0b,
	0xf1, 0x5d, 0x6c, 0xf6, 0xd0, 0x8c, 0x18, 0x3a, 0xe8, 0x8f, 0x01, 0xfa, 0x43, 0xfc, 0x3e, 0x24,
	0x63, 0x38, 0x39, 0x56, 0x13, 0x3d, 0xea, 0xd6, 0x7c, 0xb4, 0x94, 0xc8, 0xc1, 0x20, 0x89, 0x45,
	0xe0, 0xce, 0x3d, 0x23, 0x86, 0xb8, 0x8a, 0xe6, 0x46, 0x8b, 0x6f, 0x31, 0xab, 0x71, 0x7c, 0xbd,
	0x1a, 0x86, 0xc2, 0x0a, 0xb1, 0x08, 0xe6, 0x33, 0x61, 0x1d, 0x99, 0x98, 0x34, 0x86, 0x43, 0xc2,
	0x52, 0x7f, 0x7c, 0x0a, 0xaa, 0xb8, 0x8b, 0x0a, 0x36, 0x80, 0x89, 0x86, 0xde, 0xb7, 0xbc, 0x79,
	0xd3, 0x7f, 0xc9, 0x11, 0x20, 0x4f, 0x89, 0x1e, 0x8f, 0xae, 0x2c, 0x51, 0x89, 0x1e, 0x65, 0x6a,
	0xc2, 0x8a, 0x43, 0xf7, 0xee, 0xa0, 0x42, 0xaa, 0x68, 0x13, 0x74, 0xdc, 0xdc, 0x6d, 0x1e, 0x3c,
	0x68, 0xa6, 0x09, 0x6a, 0x34, 0x8f, 0xea, 0xb4, 0x59, 0xdd, 0x2b, 0xe7, 0xec, 0x5f, 0xfd, 0xa1,
	0xfb, 0x9b, 0xc1, 0xf3, 0x68, 0xf6, 0xfe, 0x61, 0xb3, 0x3c, 0xeb, 0xfd, 0x65, 0x06, 0x8a, 0x77,
	0x4f, 0x64, 0x2e, 0xc1, 0x22, 0x75, 0x1e, 0xfd, 0x07, 0x7f, 0xf2, 0xcc, 0xe4, 0xb8, 0x09, 0xaa,
	0xd7, 0xf0, 0xd5, 0x6c, 0x49, 0x4c, 0x2d, 0xbd, 0x78, 0x74, 0xfc, 0x70, 0x7a, 0x74, 0x8c, 0xf4,
	0xf7, 0xd9, 0x53, 0x12, 0x8f, 0xc6, 0x47, 0x06, 0xf3, 0xec, 0xe4, 0xc0, 0x02, 0x15, 0xba, 0x22,
	0x32, 0x5c, 0xb9, 0x85, 0xe0, 0x47, 0xa0, 0xbf, 0x8b, 0x1b, 0x94, 0x9b, 0x44, 0xc5, 0x44, 0xc6,
	0xd1, 0x19, 0x51, 0x10, 0x78, 0x4d, 0x4e, 0xfb, 0x52, 0x73, 0x37, 0x66, 0x89, 0xe2, 0x43, 0xc5,
	0x35, 0x8f, 0x4d, 0xba, 0xc6, 0x04, 0x32, 0x36, 0x4c, 0xc4, 0x9a, 0xf4, 0xc4, 0x09, 0x8f, 0x89,
	0x4e, 0x3a, 0x6e, 0x1c, 0x53, 0x67, 0xc0, 0xfb, 0x6d, 0x0e, 0x1a, 0xd5, 0xd7, 0xa2, 0xe8, 0x6e,
	0xe6, 0xdd, 0xe9, 0x49, 0xb5, 0xe8, 0x4f, 0x08, 0xd5, 0x56, 0xc0, 0xad, 0x8b, 0x18, 0x1f, 0x8d,
	0xef, 0xa8, 0x3b, 0x93, 0x9b, 0x63, 0xf8, 0x2e, 0x2a, 0x19, 0x69, 0x58, 0xd4, 0x4e, 0xc3, 0x91,
	0x86, 0xf3, 0x0a, 0xe8, 0x5d, 0xc6, 0xaf, 0x1f, 0x59, 0x16, 0x01, 0x96, 0x8d, 0x07, 0xa8, 0xf8,
	0x14, 0x81, 0xc6, 0x16, 0xcc, 0xd0, 0x27, 0xe8, 0x72, 0x75, 0x28, 0xaa, 0x61, 0xe8, 0x06, 0x28,
	0x2c, 0xc2, 0x69, 0x8a, 0xef, 0x22, 0x34, 0x4a, 0x71, 0xea, 0xdf, 0xb7, 0xc8, 0x71, 0x31, 0xcb,
	0xb1, 0xc6, 0x97, 0x46, 0xfb, 0xf6, 0x8c, 0xd5, 0xcd, 0xb6, 0x6b, 0xcf, 0x40, 0x40, 0x28, 0x1f,
	0xc8, 0x13, 0xfe, 0xbf, 0xb3, 0xba, 0xfd, 0x4c, 0x1a, 0x9c, 0x4d, 0x97, 0x86, 0x1b, 0xd3, 0x69,
	0xf8, 0xfa, 0xd3, 0xc0, 0xad, 0x0d, 0xeb, 0xe8, 0x75, 0x87, 0xb2, 0xdb, 0xd9, 0x11, 0x3c, 0x0a,
	0x33, 0x80, 0x8b, 0x19, 0x40, 0x6a, 0xd5, 0x89, 0xff, 0x39, 0x8f, 0xde, 0x98, 0x1c, 0xb4, 0x7b,
	0x92, 0x85, 0xb6, 0x1e, 0xcf, 0xa3, 0x86, 0x7e, 0x93, 0x83, 0x86, 0xaf, 0x8c, 0xdb, 0x35, 0x7e,
	0x06, 0xaa, 0xc9, 0xf4, 0x88, 0xee, 0xee, 0xd8, 0x7b, 0x9f, 0xdd, 0x9d, 0x48, 0xb2, 0x10, 0x9a,
	0x86, 0x26, 0x21, 0x33, 0x6c, 0x5c, 0x5e, 0x5d, 0x25, 0x07, 0xe9, 0x8a, 0x3a, 0xda, 0x40, 0x7c,
	0xd2, 0xe8, 0x92, 0x58, 0x1a, 0xa2, 0xb9, 0xb9, 0x45, 0x4e, 0x45, 0x14, 0x91, 0x90, 0x77, 0x59,
	0x12, 0xc1, 0x22, 0x76, 0xfb, 0x5d, 0x32, 0x10, 0x71, 0x62, 0xb8, 0x26, 0xac, 0x27, 0xd3, 0x71,
	0xa0, 0x0c, 0xfe, 0x43, 0x0e, 0xcd, 0xf2, 0x38, 0x5d, 0xe0, 0xe7, 0x6a, 0xbf, 0x4e, 0x37, 0xd6,
	0x5f, 0xe6, 0xa6, 0x7d, 0x7a, 0xfa, 0x8d, 0x3e, 0x39, 0x57, 0xdc, 0xe0, 0x39, 0x61, 0x11, 0xe1,
	0x71, 0x68, 0x7d, 0x3c, 0x15, 0xa6, 0xff, 0x9d, 0x7c, 0x84, 0xc6, 0x9e, 0x28, 0x05, 0xbb, 0x23,
	0x3c, 0x37, 0xac, 0x6f, 0xf8, 0x23, 0x54, 0x18, 0x70, 0xa3, 0x44, 0x50, 0xc9, 0x43, 0xeb, 0xbd,
	0xe6, 0xbf, 0x30, 0x43, 0xfe, 0x3e, 0x08, 0x52, 0xa7, 0xe0, 0xfd, 0x33, 0x87, 0x0a, 0x29, 0x09,
	0x5f, 0x40, 0xa5, 0xad, 0xc3, 0xe3, 0xf6, 0x61, 0x9d, 0x6e, 0xd5, 0x9b, 0x47, 0xe5, 0x57, 0xf0,
	0x32, 0x42, 0x96, 0xd0, 0x7a, 0xd4, 0x3a, 0xaa, 0xef, 0xa7, 0x4d, 0xd5, 0xfe, 0x1f, 0xb7, 0xea,
	0xb4, 0x3c, 0x83, 0x5f, 0x45, 0x4b, 0x8d, 0x83, 0x36, 0xad, 0x57, 0xb7, 0xdb, 0xb5, 0x47, 0x47,
	0xf5, 0x56, 0x79, 0x16, 0x63, 0xb4, 0xdc, 0x38, 0x68, 0x3f, 0xa0, 0x8d, 0xa3, 0xba, 0xa3, 0xcd,
	0x59, 0xd4, 0x4c, 0xec, 0xe0, 0xb0, 0x55, 0xce, 0xe3, 0x32, 0x5a, 0x1c, 0x09, 0x59, 0x4a, 0x01,
	0xaf, 0xa0, 0x4b, 0xcd, 0xfa, 0xd1, 0x83, 0x03, 0xba, 0x9b, 0x6a, 0xb5, 0x69, 0x7d, 0xab, 0xde,
	0xb8, 0x5f, 0xdf, 0x2e, 0xcf, 0xe3, 0x4b, 0x08, 0x4f, 0xf3, 0x5a, 0xd6, 0xb7, 0x05, 0x6b, 0x6a,
	0xbf, 0xbe, 0x7f, 0x40, 0x1f, 0x8d, 0xfc, 0x2d, 0xe2, 0xd7, 0xd0, 0x05, 0x47, 0xa3, 0xad, 0x56,
	0xbb, 0xd5, 0xf8, 0x71, 0xbd, 0x8c, 0x26, 0x88, 0xf7, 0xf7, 0x1d, 0xb1, 0xe4, 0x7d, 0x8e, 0xde,
	0x7c, 0x6e, 0x84, 0x46, 0x1d, 0xac, 0x64, 0x13, 0xd7, 0x1e, 0x4a, 0x11, 0x9b, 0xac, 0x80, 0xae,
	0xd8, 0xa0, 0x82, 0x54, 0xcb, 0x48, 0xc5, 0xd3, 0xa0, 0x6d, 0x33, 0xc3, 0x0e, 0xad, 0x14, 0x45,
	0x61, 0xf6, 0xa9, 0xbd, 0xaf, 0x72, 0x30, 0xbf, 0xc7, 0x95, 0x39, 0xf5, 0x0c, 0x3d, 0x8f, 0x4a,
	0x09, 0xd1, 0x05, 0x68, 0xff, 0xed, 0xf1, 0xfb, 0xcd, 0x96, 0xcc, 0x42, 0xed, 0x07, 0x80, 0xf1,
	0x01, 0xbe, 0xdd, 0xe8, 0x12, 0xa3, 0x12, 0x7e, 0x2b, 0x1d, 0x13, 0x84, 0x45, 0x91, 0x7b, 0x52,
	0x66, 0x2f, 0x39, 0xbb, 0x14, 0xf0, 0x13, 0xfb, 0xdc, 0x1a, 0xbd, 0xe1, 0x96, 0x41, 0x76, 0xf4,
	0xd8, 0xf3, 0x28, 0xba, 0xf6, 0x0d, 0xc7, 0x70, 0xc1, 0x5a, 0x9f, 0xee, 0x33, 0x97, 0xfd, 0xe7,
	0x3f, 0xbe, 0x5d, 0xff, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xda, 0xe0, 0x83, 0x87,
	0x14, 0x00, 0x00,
}
