// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/hunt.proto

/*
Package hunt is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/hunt.proto

It has these top-level messages:
	ApiHunt
	ApiHuntResult
	ApiListHuntsArgs
	ApiListHuntsResult
	ApiGetHuntArgs
	ApiGetHuntClientCompletionStatsArgs
	ApiGetHuntClientCompletionStatsResult
	ApiListHuntLogsArgs
	ApiListHuntLogsResult
	ApiListHuntErrorsArgs
	ApiListHuntErrorsResult
	ApiListHuntCrashesArgs
	ApiListHuntCrashesResult
	ApiListHuntResultsArgs
	ApiListHuntResultsResult
	ApiGetHuntResultsExportCommandArgs
	ApiGetHuntResultsExportCommandResult
	ApiListHuntOutputPluginsArgs
	ApiListHuntOutputPluginsResult
	ApiListHuntOutputPluginLogsArgs
	ApiListHuntOutputPluginLogsResult
	ApiListHuntOutputPluginErrorsArgs
	ApiListHuntOutputPluginErrorsResult
	ApiGetHuntFilesArchiveArgs
	ApiGetHuntFileArgs
	ApiGetHuntStatsArgs
	ApiGetHuntStatsResult
	ApiListHuntClientsArgs
	ApiHuntClientPendingRequest
	ApiHuntClient
	ApiListHuntClientsResult
	ApiGetHuntContextArgs
	ApiGetHuntContextResult
	ApiCreateHuntArgs
	ApiModifyHuntArgs
	ApiDeleteHuntArgs
	ApiGetExportedHuntResultsArgs
*/
package hunt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import output_plugin1 "github.com/google/grr_go_api_client/grrproto/grr/proto/api/output_plugin_proto"
import analysis "github.com/google/grr_go_api_client/grrproto/grr/proto/analysis_proto"
import api_utils "github.com/google/grr_go_api_client/grrproto/grr/proto/api_utils_proto"
import jobs "github.com/google/grr_go_api_client/grrproto/grr/proto/jobs_proto"
import flows "github.com/google/grr_go_api_client/grrproto/grr/proto/flows_proto"
import output_plugin "github.com/google/grr_go_api_client/grrproto/grr/proto/output_plugin_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum values here correspond to Hunt.State values.
type ApiHunt_State int32

const (
	ApiHunt_PAUSED    ApiHunt_State = 0
	ApiHunt_STARTED   ApiHunt_State = 1
	ApiHunt_STOPPED   ApiHunt_State = 2
	ApiHunt_COMPLETED ApiHunt_State = 3
)

var ApiHunt_State_name = map[int32]string{
	0: "PAUSED",
	1: "STARTED",
	2: "STOPPED",
	3: "COMPLETED",
}
var ApiHunt_State_value = map[string]int32{
	"PAUSED":    0,
	"STARTED":   1,
	"STOPPED":   2,
	"COMPLETED": 3,
}

func (x ApiHunt_State) Enum() *ApiHunt_State {
	p := new(ApiHunt_State)
	*p = x
	return p
}
func (x ApiHunt_State) String() string {
	return proto.EnumName(ApiHunt_State_name, int32(x))
}
func (x *ApiHunt_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiHunt_State_value, data, "ApiHunt_State")
	if err != nil {
		return err
	}
	*x = ApiHunt_State(value)
	return nil
}
func (ApiHunt_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ApiGetHuntFilesArchiveArgs_ArchiveFormat int32

const (
	ApiGetHuntFilesArchiveArgs_ZIP    ApiGetHuntFilesArchiveArgs_ArchiveFormat = 0
	ApiGetHuntFilesArchiveArgs_TAR_GZ ApiGetHuntFilesArchiveArgs_ArchiveFormat = 1
)

var ApiGetHuntFilesArchiveArgs_ArchiveFormat_name = map[int32]string{
	0: "ZIP",
	1: "TAR_GZ",
}
var ApiGetHuntFilesArchiveArgs_ArchiveFormat_value = map[string]int32{
	"ZIP":    0,
	"TAR_GZ": 1,
}

func (x ApiGetHuntFilesArchiveArgs_ArchiveFormat) Enum() *ApiGetHuntFilesArchiveArgs_ArchiveFormat {
	p := new(ApiGetHuntFilesArchiveArgs_ArchiveFormat)
	*p = x
	return p
}
func (x ApiGetHuntFilesArchiveArgs_ArchiveFormat) String() string {
	return proto.EnumName(ApiGetHuntFilesArchiveArgs_ArchiveFormat_name, int32(x))
}
func (x *ApiGetHuntFilesArchiveArgs_ArchiveFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetHuntFilesArchiveArgs_ArchiveFormat_value, data, "ApiGetHuntFilesArchiveArgs_ArchiveFormat")
	if err != nil {
		return err
	}
	*x = ApiGetHuntFilesArchiveArgs_ArchiveFormat(value)
	return nil
}
func (ApiGetHuntFilesArchiveArgs_ArchiveFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{23, 0}
}

type ApiListHuntClientsArgs_ClientStatus int32

const (
	ApiListHuntClientsArgs_STARTED     ApiListHuntClientsArgs_ClientStatus = 0
	ApiListHuntClientsArgs_OUTSTANDING ApiListHuntClientsArgs_ClientStatus = 1
	ApiListHuntClientsArgs_COMPLETED   ApiListHuntClientsArgs_ClientStatus = 2
)

var ApiListHuntClientsArgs_ClientStatus_name = map[int32]string{
	0: "STARTED",
	1: "OUTSTANDING",
	2: "COMPLETED",
}
var ApiListHuntClientsArgs_ClientStatus_value = map[string]int32{
	"STARTED":     0,
	"OUTSTANDING": 1,
	"COMPLETED":   2,
}

func (x ApiListHuntClientsArgs_ClientStatus) Enum() *ApiListHuntClientsArgs_ClientStatus {
	p := new(ApiListHuntClientsArgs_ClientStatus)
	*p = x
	return p
}
func (x ApiListHuntClientsArgs_ClientStatus) String() string {
	return proto.EnumName(ApiListHuntClientsArgs_ClientStatus_name, int32(x))
}
func (x *ApiListHuntClientsArgs_ClientStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiListHuntClientsArgs_ClientStatus_value, data, "ApiListHuntClientsArgs_ClientStatus")
	if err != nil {
		return err
	}
	*x = ApiListHuntClientsArgs_ClientStatus(value)
	return nil
}
func (ApiListHuntClientsArgs_ClientStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{27, 0}
}

// Next id: 22
type ApiHunt struct {
	Urn                   *string                    `protobuf:"bytes,1,opt,name=urn" json:"urn,omitempty"`
	Name                  *string                    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	State                 *ApiHunt_State             `protobuf:"varint,4,opt,name=state,enum=ApiHunt_State" json:"state,omitempty"`
	FlowName              *string                    `protobuf:"bytes,20,opt,name=flow_name,json=flowName" json:"flow_name,omitempty"`
	FlowArgs              *google_protobuf.Any       `protobuf:"bytes,21,opt,name=flow_args,json=flowArgs" json:"flow_args,omitempty"`
	HuntRunnerArgs        *flows.HuntRunnerArgs      `protobuf:"bytes,6,opt,name=hunt_runner_args,json=huntRunnerArgs" json:"hunt_runner_args,omitempty"`
	AllClientsCount       *int64                     `protobuf:"varint,7,opt,name=all_clients_count,json=allClientsCount" json:"all_clients_count,omitempty"`
	RemainingClientsCount *int64                     `protobuf:"varint,8,opt,name=remaining_clients_count,json=remainingClientsCount" json:"remaining_clients_count,omitempty"`
	CompletedClientsCount *int64                     `protobuf:"varint,9,opt,name=completed_clients_count,json=completedClientsCount" json:"completed_clients_count,omitempty"`
	ClientLimit           *int64                     `protobuf:"varint,10,opt,name=client_limit,json=clientLimit" json:"client_limit,omitempty"`
	ClientRate            *float32                   `protobuf:"fixed32,11,opt,name=client_rate,json=clientRate" json:"client_rate,omitempty"`
	Created               *uint64                    `protobuf:"varint,12,opt,name=created" json:"created,omitempty"`
	Expires               *uint64                    `protobuf:"varint,13,opt,name=expires" json:"expires,omitempty"`
	Creator               *string                    `protobuf:"bytes,14,opt,name=creator" json:"creator,omitempty"`
	Description           *string                    `protobuf:"bytes,15,opt,name=description" json:"description,omitempty"`
	ClientRuleSet         *jobs.ForemanClientRuleSet `protobuf:"bytes,16,opt,name=client_rule_set,json=clientRuleSet" json:"client_rule_set,omitempty"`
	IsRobot               *bool                      `protobuf:"varint,17,opt,name=is_robot,json=isRobot" json:"is_robot,omitempty"`
	TotalCpuUsage         *float32                   `protobuf:"fixed32,18,opt,name=total_cpu_usage,json=totalCpuUsage" json:"total_cpu_usage,omitempty"`
	TotalNetUsage         *int64                     `protobuf:"varint,19,opt,name=total_net_usage,json=totalNetUsage" json:"total_net_usage,omitempty"`
	XXX_unrecognized      []byte                     `json:"-"`
}

func (m *ApiHunt) Reset()                    { *m = ApiHunt{} }
func (m *ApiHunt) String() string            { return proto.CompactTextString(m) }
func (*ApiHunt) ProtoMessage()               {}
func (*ApiHunt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiHunt) GetUrn() string {
	if m != nil && m.Urn != nil {
		return *m.Urn
	}
	return ""
}

func (m *ApiHunt) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiHunt) GetState() ApiHunt_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiHunt_PAUSED
}

func (m *ApiHunt) GetFlowName() string {
	if m != nil && m.FlowName != nil {
		return *m.FlowName
	}
	return ""
}

func (m *ApiHunt) GetFlowArgs() *google_protobuf.Any {
	if m != nil {
		return m.FlowArgs
	}
	return nil
}

func (m *ApiHunt) GetHuntRunnerArgs() *flows.HuntRunnerArgs {
	if m != nil {
		return m.HuntRunnerArgs
	}
	return nil
}

func (m *ApiHunt) GetAllClientsCount() int64 {
	if m != nil && m.AllClientsCount != nil {
		return *m.AllClientsCount
	}
	return 0
}

func (m *ApiHunt) GetRemainingClientsCount() int64 {
	if m != nil && m.RemainingClientsCount != nil {
		return *m.RemainingClientsCount
	}
	return 0
}

func (m *ApiHunt) GetCompletedClientsCount() int64 {
	if m != nil && m.CompletedClientsCount != nil {
		return *m.CompletedClientsCount
	}
	return 0
}

func (m *ApiHunt) GetClientLimit() int64 {
	if m != nil && m.ClientLimit != nil {
		return *m.ClientLimit
	}
	return 0
}

func (m *ApiHunt) GetClientRate() float32 {
	if m != nil && m.ClientRate != nil {
		return *m.ClientRate
	}
	return 0
}

func (m *ApiHunt) GetCreated() uint64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *ApiHunt) GetExpires() uint64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *ApiHunt) GetCreator() string {
	if m != nil && m.Creator != nil {
		return *m.Creator
	}
	return ""
}

func (m *ApiHunt) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ApiHunt) GetClientRuleSet() *jobs.ForemanClientRuleSet {
	if m != nil {
		return m.ClientRuleSet
	}
	return nil
}

func (m *ApiHunt) GetIsRobot() bool {
	if m != nil && m.IsRobot != nil {
		return *m.IsRobot
	}
	return false
}

func (m *ApiHunt) GetTotalCpuUsage() float32 {
	if m != nil && m.TotalCpuUsage != nil {
		return *m.TotalCpuUsage
	}
	return 0
}

func (m *ApiHunt) GetTotalNetUsage() int64 {
	if m != nil && m.TotalNetUsage != nil {
		return *m.TotalNetUsage
	}
	return 0
}

type ApiHuntResult struct {
	ClientId         *string              `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Payload          *google_protobuf.Any `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	PayloadType      *string              `protobuf:"bytes,4,opt,name=payload_type,json=payloadType" json:"payload_type,omitempty"`
	Timestamp        *uint64              `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApiHuntResult) Reset()                    { *m = ApiHuntResult{} }
func (m *ApiHuntResult) String() string            { return proto.CompactTextString(m) }
func (*ApiHuntResult) ProtoMessage()               {}
func (*ApiHuntResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiHuntResult) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiHuntResult) GetPayload() *google_protobuf.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ApiHuntResult) GetPayloadType() string {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return ""
}

func (m *ApiHuntResult) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiListHuntsArgs struct {
	Offset *int64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Count  *int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	// Filtering criterias.
	CreatedBy           *string `protobuf:"bytes,3,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	DescriptionContains *string `protobuf:"bytes,4,opt,name=description_contains,json=descriptionContains" json:"description_contains,omitempty"`
	ActiveWithin        *uint64 `protobuf:"varint,5,opt,name=active_within,json=activeWithin" json:"active_within,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *ApiListHuntsArgs) Reset()                    { *m = ApiListHuntsArgs{} }
func (m *ApiListHuntsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntsArgs) ProtoMessage()               {}
func (*ApiListHuntsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiListHuntsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntsArgs) GetCreatedBy() string {
	if m != nil && m.CreatedBy != nil {
		return *m.CreatedBy
	}
	return ""
}

func (m *ApiListHuntsArgs) GetDescriptionContains() string {
	if m != nil && m.DescriptionContains != nil {
		return *m.DescriptionContains
	}
	return ""
}

func (m *ApiListHuntsArgs) GetActiveWithin() uint64 {
	if m != nil && m.ActiveWithin != nil {
		return *m.ActiveWithin
	}
	return 0
}

type ApiListHuntsResult struct {
	Items            []*ApiHunt `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64     `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ApiListHuntsResult) Reset()                    { *m = ApiListHuntsResult{} }
func (m *ApiListHuntsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntsResult) ProtoMessage()               {}
func (*ApiListHuntsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiListHuntsResult) GetItems() []*ApiHunt {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiGetHuntArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntArgs) Reset()                    { *m = ApiGetHuntArgs{} }
func (m *ApiGetHuntArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntArgs) ProtoMessage()               {}
func (*ApiGetHuntArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiGetHuntArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiGetHuntClientCompletionStatsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Size             *int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntClientCompletionStatsArgs) Reset()         { *m = ApiGetHuntClientCompletionStatsArgs{} }
func (m *ApiGetHuntClientCompletionStatsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiGetHuntClientCompletionStatsArgs) ProtoMessage()    {}
func (*ApiGetHuntClientCompletionStatsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *ApiGetHuntClientCompletionStatsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGetHuntClientCompletionStatsArgs) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type ApiGetHuntClientCompletionStatsResult struct {
	StartPoints      []*analysis.SampleFloat `protobuf:"bytes,1,rep,name=start_points,json=startPoints" json:"start_points,omitempty"`
	CompletePoints   []*analysis.SampleFloat `protobuf:"bytes,2,rep,name=complete_points,json=completePoints" json:"complete_points,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ApiGetHuntClientCompletionStatsResult) Reset()         { *m = ApiGetHuntClientCompletionStatsResult{} }
func (m *ApiGetHuntClientCompletionStatsResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetHuntClientCompletionStatsResult) ProtoMessage()    {}
func (*ApiGetHuntClientCompletionStatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func (m *ApiGetHuntClientCompletionStatsResult) GetStartPoints() []*analysis.SampleFloat {
	if m != nil {
		return m.StartPoints
	}
	return nil
}

func (m *ApiGetHuntClientCompletionStatsResult) GetCompletePoints() []*analysis.SampleFloat {
	if m != nil {
		return m.CompletePoints
	}
	return nil
}

type ApiListHuntLogsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntLogsArgs) Reset()                    { *m = ApiListHuntLogsArgs{} }
func (m *ApiListHuntLogsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntLogsArgs) ProtoMessage()               {}
func (*ApiListHuntLogsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApiListHuntLogsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntLogsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntLogsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntLogsArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListHuntLogsResult struct {
	Items            []*jobs.FlowLog `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64          `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ApiListHuntLogsResult) Reset()                    { *m = ApiListHuntLogsResult{} }
func (m *ApiListHuntLogsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntLogsResult) ProtoMessage()               {}
func (*ApiListHuntLogsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApiListHuntLogsResult) GetItems() []*jobs.FlowLog {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntLogsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListHuntErrorsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntErrorsArgs) Reset()                    { *m = ApiListHuntErrorsArgs{} }
func (m *ApiListHuntErrorsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntErrorsArgs) ProtoMessage()               {}
func (*ApiListHuntErrorsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiListHuntErrorsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntErrorsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntErrorsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntErrorsArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListHuntErrorsResult struct {
	Items            []*jobs.HuntError `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64            `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ApiListHuntErrorsResult) Reset()                    { *m = ApiListHuntErrorsResult{} }
func (m *ApiListHuntErrorsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntErrorsResult) ProtoMessage()               {}
func (*ApiListHuntErrorsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApiListHuntErrorsResult) GetItems() []*jobs.HuntError {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntErrorsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListHuntCrashesArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntCrashesArgs) Reset()                    { *m = ApiListHuntCrashesArgs{} }
func (m *ApiListHuntCrashesArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntCrashesArgs) ProtoMessage()               {}
func (*ApiListHuntCrashesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiListHuntCrashesArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntCrashesArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntCrashesArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntCrashesArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListHuntCrashesResult struct {
	Items            []*jobs.ClientCrash `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64              `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApiListHuntCrashesResult) Reset()                    { *m = ApiListHuntCrashesResult{} }
func (m *ApiListHuntCrashesResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntCrashesResult) ProtoMessage()               {}
func (*ApiListHuntCrashesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ApiListHuntCrashesResult) GetItems() []*jobs.ClientCrash {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntCrashesResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListHuntResultsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntResultsArgs) Reset()                    { *m = ApiListHuntResultsArgs{} }
func (m *ApiListHuntResultsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntResultsArgs) ProtoMessage()               {}
func (*ApiListHuntResultsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ApiListHuntResultsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntResultsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntResultsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntResultsArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListHuntResultsResult struct {
	Items            []*ApiHuntResult `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64           `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ApiListHuntResultsResult) Reset()                    { *m = ApiListHuntResultsResult{} }
func (m *ApiListHuntResultsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntResultsResult) ProtoMessage()               {}
func (*ApiListHuntResultsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ApiListHuntResultsResult) GetItems() []*ApiHuntResult {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntResultsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiGetHuntResultsExportCommandArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntResultsExportCommandArgs) Reset()         { *m = ApiGetHuntResultsExportCommandArgs{} }
func (m *ApiGetHuntResultsExportCommandArgs) String() string { return proto.CompactTextString(m) }
func (*ApiGetHuntResultsExportCommandArgs) ProtoMessage()    {}
func (*ApiGetHuntResultsExportCommandArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

func (m *ApiGetHuntResultsExportCommandArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiGetHuntResultsExportCommandResult struct {
	Command          *string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntResultsExportCommandResult) Reset()         { *m = ApiGetHuntResultsExportCommandResult{} }
func (m *ApiGetHuntResultsExportCommandResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetHuntResultsExportCommandResult) ProtoMessage()    {}
func (*ApiGetHuntResultsExportCommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16}
}

func (m *ApiGetHuntResultsExportCommandResult) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

type ApiListHuntOutputPluginsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntOutputPluginsArgs) Reset()                    { *m = ApiListHuntOutputPluginsArgs{} }
func (m *ApiListHuntOutputPluginsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginsArgs) ProtoMessage()               {}
func (*ApiListHuntOutputPluginsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ApiListHuntOutputPluginsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiListHuntOutputPluginsResult struct {
	Items            []*output_plugin1.ApiOutputPlugin `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64                            `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *ApiListHuntOutputPluginsResult) Reset()                    { *m = ApiListHuntOutputPluginsResult{} }
func (m *ApiListHuntOutputPluginsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginsResult) ProtoMessage()               {}
func (*ApiListHuntOutputPluginsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ApiListHuntOutputPluginsResult) GetItems() []*output_plugin1.ApiOutputPlugin {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntOutputPluginsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListHuntOutputPluginLogsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	PluginId         *string `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	Offset           *int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntOutputPluginLogsArgs) Reset()         { *m = ApiListHuntOutputPluginLogsArgs{} }
func (m *ApiListHuntOutputPluginLogsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginLogsArgs) ProtoMessage()    {}
func (*ApiListHuntOutputPluginLogsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19}
}

func (m *ApiListHuntOutputPluginLogsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntOutputPluginLogsArgs) GetPluginId() string {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return ""
}

func (m *ApiListHuntOutputPluginLogsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntOutputPluginLogsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiListHuntOutputPluginLogsResult struct {
	Items            []*output_plugin.OutputPluginBatchProcessingStatus `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64                                             `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte                                             `json:"-"`
}

func (m *ApiListHuntOutputPluginLogsResult) Reset()         { *m = ApiListHuntOutputPluginLogsResult{} }
func (m *ApiListHuntOutputPluginLogsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginLogsResult) ProtoMessage()    {}
func (*ApiListHuntOutputPluginLogsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{20}
}

func (m *ApiListHuntOutputPluginLogsResult) GetItems() []*output_plugin.OutputPluginBatchProcessingStatus {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntOutputPluginLogsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListHuntOutputPluginErrorsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	PluginId         *string `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	Offset           *int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListHuntOutputPluginErrorsArgs) Reset()         { *m = ApiListHuntOutputPluginErrorsArgs{} }
func (m *ApiListHuntOutputPluginErrorsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginErrorsArgs) ProtoMessage()    {}
func (*ApiListHuntOutputPluginErrorsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21}
}

func (m *ApiListHuntOutputPluginErrorsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntOutputPluginErrorsArgs) GetPluginId() string {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return ""
}

func (m *ApiListHuntOutputPluginErrorsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntOutputPluginErrorsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiListHuntOutputPluginErrorsResult struct {
	Items            []*output_plugin.OutputPluginBatchProcessingStatus `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64                                             `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte                                             `json:"-"`
}

func (m *ApiListHuntOutputPluginErrorsResult) Reset()         { *m = ApiListHuntOutputPluginErrorsResult{} }
func (m *ApiListHuntOutputPluginErrorsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListHuntOutputPluginErrorsResult) ProtoMessage()    {}
func (*ApiListHuntOutputPluginErrorsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *ApiListHuntOutputPluginErrorsResult) GetItems() []*output_plugin.OutputPluginBatchProcessingStatus {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntOutputPluginErrorsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiGetHuntFilesArchiveArgs struct {
	HuntId           *string                                   `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	ArchiveFormat    *ApiGetHuntFilesArchiveArgs_ArchiveFormat `protobuf:"varint,3,opt,name=archive_format,json=archiveFormat,enum=ApiGetHuntFilesArchiveArgs_ArchiveFormat" json:"archive_format,omitempty"`
	XXX_unrecognized []byte                                    `json:"-"`
}

func (m *ApiGetHuntFilesArchiveArgs) Reset()                    { *m = ApiGetHuntFilesArchiveArgs{} }
func (m *ApiGetHuntFilesArchiveArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntFilesArchiveArgs) ProtoMessage()               {}
func (*ApiGetHuntFilesArchiveArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ApiGetHuntFilesArchiveArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGetHuntFilesArchiveArgs) GetArchiveFormat() ApiGetHuntFilesArchiveArgs_ArchiveFormat {
	if m != nil && m.ArchiveFormat != nil {
		return *m.ArchiveFormat
	}
	return ApiGetHuntFilesArchiveArgs_ZIP
}

type ApiGetHuntFileArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	ClientId         *string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	VfsPath          *string `protobuf:"bytes,4,opt,name=vfs_path,json=vfsPath" json:"vfs_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntFileArgs) Reset()                    { *m = ApiGetHuntFileArgs{} }
func (m *ApiGetHuntFileArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntFileArgs) ProtoMessage()               {}
func (*ApiGetHuntFileArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ApiGetHuntFileArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGetHuntFileArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetHuntFileArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApiGetHuntFileArgs) GetVfsPath() string {
	if m != nil && m.VfsPath != nil {
		return *m.VfsPath
	}
	return ""
}

type ApiGetHuntStatsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntStatsArgs) Reset()                    { *m = ApiGetHuntStatsArgs{} }
func (m *ApiGetHuntStatsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntStatsArgs) ProtoMessage()               {}
func (*ApiGetHuntStatsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ApiGetHuntStatsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiGetHuntStatsResult struct {
	Stats            *jobs.ClientResourcesStats `protobuf:"bytes,1,opt,name=stats" json:"stats,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ApiGetHuntStatsResult) Reset()                    { *m = ApiGetHuntStatsResult{} }
func (m *ApiGetHuntStatsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntStatsResult) ProtoMessage()               {}
func (*ApiGetHuntStatsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ApiGetHuntStatsResult) GetStats() *jobs.ClientResourcesStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ApiListHuntClientsArgs struct {
	HuntId           *string                              `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Offset           *int64                               `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64                               `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ClientStatus     *ApiListHuntClientsArgs_ClientStatus `protobuf:"varint,4,opt,name=client_status,json=clientStatus,enum=ApiListHuntClientsArgs_ClientStatus" json:"client_status,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *ApiListHuntClientsArgs) Reset()                    { *m = ApiListHuntClientsArgs{} }
func (m *ApiListHuntClientsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntClientsArgs) ProtoMessage()               {}
func (*ApiListHuntClientsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ApiListHuntClientsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiListHuntClientsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntClientsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListHuntClientsArgs) GetClientStatus() ApiListHuntClientsArgs_ClientStatus {
	if m != nil && m.ClientStatus != nil {
		return *m.ClientStatus
	}
	return ApiListHuntClientsArgs_STARTED
}

type ApiHuntClientPendingRequest struct {
	FlowUrn                      *string `protobuf:"bytes,1,opt,name=flow_urn,json=flowUrn" json:"flow_urn,omitempty"`
	IncompleteRequestId          *string `protobuf:"bytes,2,opt,name=incomplete_request_id,json=incompleteRequestId" json:"incomplete_request_id,omitempty"`
	NextState                    *string `protobuf:"bytes,3,opt,name=next_state,json=nextState" json:"next_state,omitempty"`
	ExpectedArgs                 *string `protobuf:"bytes,4,opt,name=expected_args,json=expectedArgs" json:"expected_args,omitempty"`
	AvailableResponsesCount      *int64  `protobuf:"varint,5,opt,name=available_responses_count,json=availableResponsesCount" json:"available_responses_count,omitempty"`
	ExpectedResponses            *string `protobuf:"bytes,6,opt,name=expected_responses,json=expectedResponses" json:"expected_responses,omitempty"`
	IsStatusAvailable            *bool   `protobuf:"varint,7,opt,name=is_status_available,json=isStatusAvailable" json:"is_status_available,omitempty"`
	AvailableClientRequestsCount *int64  `protobuf:"varint,8,opt,name=available_client_requests_count,json=availableClientRequestsCount" json:"available_client_requests_count,omitempty"`
	XXX_unrecognized             []byte  `json:"-"`
}

func (m *ApiHuntClientPendingRequest) Reset()                    { *m = ApiHuntClientPendingRequest{} }
func (m *ApiHuntClientPendingRequest) String() string            { return proto.CompactTextString(m) }
func (*ApiHuntClientPendingRequest) ProtoMessage()               {}
func (*ApiHuntClientPendingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ApiHuntClientPendingRequest) GetFlowUrn() string {
	if m != nil && m.FlowUrn != nil {
		return *m.FlowUrn
	}
	return ""
}

func (m *ApiHuntClientPendingRequest) GetIncompleteRequestId() string {
	if m != nil && m.IncompleteRequestId != nil {
		return *m.IncompleteRequestId
	}
	return ""
}

func (m *ApiHuntClientPendingRequest) GetNextState() string {
	if m != nil && m.NextState != nil {
		return *m.NextState
	}
	return ""
}

func (m *ApiHuntClientPendingRequest) GetExpectedArgs() string {
	if m != nil && m.ExpectedArgs != nil {
		return *m.ExpectedArgs
	}
	return ""
}

func (m *ApiHuntClientPendingRequest) GetAvailableResponsesCount() int64 {
	if m != nil && m.AvailableResponsesCount != nil {
		return *m.AvailableResponsesCount
	}
	return 0
}

func (m *ApiHuntClientPendingRequest) GetExpectedResponses() string {
	if m != nil && m.ExpectedResponses != nil {
		return *m.ExpectedResponses
	}
	return ""
}

func (m *ApiHuntClientPendingRequest) GetIsStatusAvailable() bool {
	if m != nil && m.IsStatusAvailable != nil {
		return *m.IsStatusAvailable
	}
	return false
}

func (m *ApiHuntClientPendingRequest) GetAvailableClientRequestsCount() int64 {
	if m != nil && m.AvailableClientRequestsCount != nil {
		return *m.AvailableClientRequestsCount
	}
	return 0
}

type ApiHuntClient struct {
	ClientId         *string                        `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FlowUrn          *string                        `protobuf:"bytes,2,opt,name=flow_urn,json=flowUrn" json:"flow_urn,omitempty"`
	CpuUsage         *jobs.CpuSeconds               `protobuf:"bytes,10,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	NetworkBytesSent *int64                         `protobuf:"varint,11,opt,name=network_bytes_sent,json=networkBytesSent" json:"network_bytes_sent,omitempty"`
	PendingRequests  []*ApiHuntClientPendingRequest `protobuf:"bytes,12,rep,name=pending_requests,json=pendingRequests" json:"pending_requests,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *ApiHuntClient) Reset()                    { *m = ApiHuntClient{} }
func (m *ApiHuntClient) String() string            { return proto.CompactTextString(m) }
func (*ApiHuntClient) ProtoMessage()               {}
func (*ApiHuntClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ApiHuntClient) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiHuntClient) GetFlowUrn() string {
	if m != nil && m.FlowUrn != nil {
		return *m.FlowUrn
	}
	return ""
}

func (m *ApiHuntClient) GetCpuUsage() *jobs.CpuSeconds {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *ApiHuntClient) GetNetworkBytesSent() int64 {
	if m != nil && m.NetworkBytesSent != nil {
		return *m.NetworkBytesSent
	}
	return 0
}

func (m *ApiHuntClient) GetPendingRequests() []*ApiHuntClientPendingRequest {
	if m != nil {
		return m.PendingRequests
	}
	return nil
}

type ApiListHuntClientsResult struct {
	Items            []*ApiHuntClient `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64           `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ApiListHuntClientsResult) Reset()                    { *m = ApiListHuntClientsResult{} }
func (m *ApiListHuntClientsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntClientsResult) ProtoMessage()               {}
func (*ApiListHuntClientsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ApiListHuntClientsResult) GetItems() []*ApiHuntClient {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListHuntClientsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiGetHuntContextArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntContextArgs) Reset()                    { *m = ApiGetHuntContextArgs{} }
func (m *ApiGetHuntContextArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntContextArgs) ProtoMessage()               {}
func (*ApiGetHuntContextArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ApiGetHuntContextArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiGetHuntContextResult struct {
	Context          *flows.HuntContext       `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	State            *api_utils.ApiDataObject `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ApiGetHuntContextResult) Reset()                    { *m = ApiGetHuntContextResult{} }
func (m *ApiGetHuntContextResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntContextResult) ProtoMessage()               {}
func (*ApiGetHuntContextResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ApiGetHuntContextResult) GetContext() *flows.HuntContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ApiGetHuntContextResult) GetState() *api_utils.ApiDataObject {
	if m != nil {
		return m.State
	}
	return nil
}

// Next id: 6
type ApiCreateHuntArgs struct {
	FlowName         *string               `protobuf:"bytes,3,opt,name=flow_name,json=flowName" json:"flow_name,omitempty"`
	FlowArgs         *google_protobuf.Any  `protobuf:"bytes,4,opt,name=flow_args,json=flowArgs" json:"flow_args,omitempty"`
	HuntRunnerArgs   *flows.HuntRunnerArgs `protobuf:"bytes,1,opt,name=hunt_runner_args,json=huntRunnerArgs" json:"hunt_runner_args,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ApiCreateHuntArgs) Reset()                    { *m = ApiCreateHuntArgs{} }
func (m *ApiCreateHuntArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiCreateHuntArgs) ProtoMessage()               {}
func (*ApiCreateHuntArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *ApiCreateHuntArgs) GetFlowName() string {
	if m != nil && m.FlowName != nil {
		return *m.FlowName
	}
	return ""
}

func (m *ApiCreateHuntArgs) GetFlowArgs() *google_protobuf.Any {
	if m != nil {
		return m.FlowArgs
	}
	return nil
}

func (m *ApiCreateHuntArgs) GetHuntRunnerArgs() *flows.HuntRunnerArgs {
	if m != nil {
		return m.HuntRunnerArgs
	}
	return nil
}

type ApiModifyHuntArgs struct {
	HuntId           *string        `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	State            *ApiHunt_State `protobuf:"varint,2,opt,name=state,enum=ApiHunt_State" json:"state,omitempty"`
	ClientLimit      *int64         `protobuf:"varint,3,opt,name=client_limit,json=clientLimit" json:"client_limit,omitempty"`
	ClientRate       *int64         `protobuf:"varint,4,opt,name=client_rate,json=clientRate" json:"client_rate,omitempty"`
	Expires          *uint64        `protobuf:"varint,5,opt,name=expires" json:"expires,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ApiModifyHuntArgs) Reset()                    { *m = ApiModifyHuntArgs{} }
func (m *ApiModifyHuntArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiModifyHuntArgs) ProtoMessage()               {}
func (*ApiModifyHuntArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ApiModifyHuntArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiModifyHuntArgs) GetState() ApiHunt_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiHunt_PAUSED
}

func (m *ApiModifyHuntArgs) GetClientLimit() int64 {
	if m != nil && m.ClientLimit != nil {
		return *m.ClientLimit
	}
	return 0
}

func (m *ApiModifyHuntArgs) GetClientRate() int64 {
	if m != nil && m.ClientRate != nil {
		return *m.ClientRate
	}
	return 0
}

func (m *ApiModifyHuntArgs) GetExpires() uint64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

type ApiDeleteHuntArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiDeleteHuntArgs) Reset()                    { *m = ApiDeleteHuntArgs{} }
func (m *ApiDeleteHuntArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiDeleteHuntArgs) ProtoMessage()               {}
func (*ApiDeleteHuntArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *ApiDeleteHuntArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

type ApiGetExportedHuntResultsArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	PluginName       *string `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName" json:"plugin_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetExportedHuntResultsArgs) Reset()                    { *m = ApiGetExportedHuntResultsArgs{} }
func (m *ApiGetExportedHuntResultsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetExportedHuntResultsArgs) ProtoMessage()               {}
func (*ApiGetExportedHuntResultsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ApiGetExportedHuntResultsArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGetExportedHuntResultsArgs) GetPluginName() string {
	if m != nil && m.PluginName != nil {
		return *m.PluginName
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiHunt)(nil), "ApiHunt")
	proto.RegisterType((*ApiHuntResult)(nil), "ApiHuntResult")
	proto.RegisterType((*ApiListHuntsArgs)(nil), "ApiListHuntsArgs")
	proto.RegisterType((*ApiListHuntsResult)(nil), "ApiListHuntsResult")
	proto.RegisterType((*ApiGetHuntArgs)(nil), "ApiGetHuntArgs")
	proto.RegisterType((*ApiGetHuntClientCompletionStatsArgs)(nil), "ApiGetHuntClientCompletionStatsArgs")
	proto.RegisterType((*ApiGetHuntClientCompletionStatsResult)(nil), "ApiGetHuntClientCompletionStatsResult")
	proto.RegisterType((*ApiListHuntLogsArgs)(nil), "ApiListHuntLogsArgs")
	proto.RegisterType((*ApiListHuntLogsResult)(nil), "ApiListHuntLogsResult")
	proto.RegisterType((*ApiListHuntErrorsArgs)(nil), "ApiListHuntErrorsArgs")
	proto.RegisterType((*ApiListHuntErrorsResult)(nil), "ApiListHuntErrorsResult")
	proto.RegisterType((*ApiListHuntCrashesArgs)(nil), "ApiListHuntCrashesArgs")
	proto.RegisterType((*ApiListHuntCrashesResult)(nil), "ApiListHuntCrashesResult")
	proto.RegisterType((*ApiListHuntResultsArgs)(nil), "ApiListHuntResultsArgs")
	proto.RegisterType((*ApiListHuntResultsResult)(nil), "ApiListHuntResultsResult")
	proto.RegisterType((*ApiGetHuntResultsExportCommandArgs)(nil), "ApiGetHuntResultsExportCommandArgs")
	proto.RegisterType((*ApiGetHuntResultsExportCommandResult)(nil), "ApiGetHuntResultsExportCommandResult")
	proto.RegisterType((*ApiListHuntOutputPluginsArgs)(nil), "ApiListHuntOutputPluginsArgs")
	proto.RegisterType((*ApiListHuntOutputPluginsResult)(nil), "ApiListHuntOutputPluginsResult")
	proto.RegisterType((*ApiListHuntOutputPluginLogsArgs)(nil), "ApiListHuntOutputPluginLogsArgs")
	proto.RegisterType((*ApiListHuntOutputPluginLogsResult)(nil), "ApiListHuntOutputPluginLogsResult")
	proto.RegisterType((*ApiListHuntOutputPluginErrorsArgs)(nil), "ApiListHuntOutputPluginErrorsArgs")
	proto.RegisterType((*ApiListHuntOutputPluginErrorsResult)(nil), "ApiListHuntOutputPluginErrorsResult")
	proto.RegisterType((*ApiGetHuntFilesArchiveArgs)(nil), "ApiGetHuntFilesArchiveArgs")
	proto.RegisterType((*ApiGetHuntFileArgs)(nil), "ApiGetHuntFileArgs")
	proto.RegisterType((*ApiGetHuntStatsArgs)(nil), "ApiGetHuntStatsArgs")
	proto.RegisterType((*ApiGetHuntStatsResult)(nil), "ApiGetHuntStatsResult")
	proto.RegisterType((*ApiListHuntClientsArgs)(nil), "ApiListHuntClientsArgs")
	proto.RegisterType((*ApiHuntClientPendingRequest)(nil), "ApiHuntClientPendingRequest")
	proto.RegisterType((*ApiHuntClient)(nil), "ApiHuntClient")
	proto.RegisterType((*ApiListHuntClientsResult)(nil), "ApiListHuntClientsResult")
	proto.RegisterType((*ApiGetHuntContextArgs)(nil), "ApiGetHuntContextArgs")
	proto.RegisterType((*ApiGetHuntContextResult)(nil), "ApiGetHuntContextResult")
	proto.RegisterType((*ApiCreateHuntArgs)(nil), "ApiCreateHuntArgs")
	proto.RegisterType((*ApiModifyHuntArgs)(nil), "ApiModifyHuntArgs")
	proto.RegisterType((*ApiDeleteHuntArgs)(nil), "ApiDeleteHuntArgs")
	proto.RegisterType((*ApiGetExportedHuntResultsArgs)(nil), "ApiGetExportedHuntResultsArgs")
	proto.RegisterEnum("ApiHunt_State", ApiHunt_State_name, ApiHunt_State_value)
	proto.RegisterEnum("ApiGetHuntFilesArchiveArgs_ArchiveFormat", ApiGetHuntFilesArchiveArgs_ArchiveFormat_name, ApiGetHuntFilesArchiveArgs_ArchiveFormat_value)
	proto.RegisterEnum("ApiListHuntClientsArgs_ClientStatus", ApiListHuntClientsArgs_ClientStatus_name, ApiListHuntClientsArgs_ClientStatus_value)
}

func init() { proto.RegisterFile("grr/proto/api/hunt.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x5a, 0xdd, 0x6f, 0x1c, 0xb7,
	0x11, 0xcf, 0x9d, 0x2c, 0x4b, 0xe2, 0xe9, 0xcb, 0x94, 0x64, 0x9f, 0xbf, 0xe9, 0xb3, 0x63, 0xcb,
	0x4e, 0xb2, 0x76, 0x5d, 0xb7, 0xf9, 0xb0, 0x13, 0xf7, 0x4e, 0x1f, 0xf6, 0x35, 0xb6, 0xa4, 0xac,
	0x64, 0x38, 0x4d, 0x11, 0x1c, 0x56, 0x7b, 0xbc, 0x3b, 0x3a, 0x2b, 0x72, 0xb3, 0xe4, 0x4a, 0x56,
	0x9e, 0x0b, 0xa4, 0x28, 0x50, 0xa0, 0x05, 0x0a, 0x14, 0x68, 0xfa, 0x17, 0xf4, 0xa1, 0x40, 0x92,
	0x02, 0xcd, 0x73, 0xd1, 0xa7, 0xfe, 0x0d, 0x45, 0x1f, 0xda, 0xd7, 0x16, 0xe8, 0x43, 0x1f, 0x5b,
	0xa0, 0xe0, 0x90, 0xfb, 0x75, 0x92, 0x6c, 0xd8, 0xe7, 0x34, 0xe8, 0xdb, 0x2e, 0x39, 0xf3, 0xe3,
	0xec, 0x0c, 0x67, 0x38, 0x9c, 0x59, 0x54, 0xed, 0x46, 0xd1, 0xd5, 0x30, 0x12, 0x4a, 0x5c, 0xf5,
	0x42, 0x76, 0xb5, 0x17, 0x73, 0xe5, 0xc0, 0xeb, 0x89, 0xe3, 0x5d, 0x21, 0xba, 0x01, 0x35, 0x93,
	0x9b, 0x71, 0xe7, 0xaa, 0xc7, 0x77, 0xed, 0xd4, 0xb9, 0x22, 0x93, 0x88, 0x55, 0x18, 0xab, 0x56,
	0x18, 0xc4, 0x5d, 0xc6, 0x2d, 0x49, 0x1e, 0x97, 0x7b, 0xc1, 0xae, 0x64, 0x32, 0xc5, 0xcd, 0x33,
	0xb7, 0x62, 0xc5, 0x82, 0x64, 0x6a, 0x36, 0x9b, 0x7a, 0x24, 0x36, 0x93, 0xd1, 0xb9, 0x6c, 0xb4,
	0x13, 0x88, 0x9d, 0x64, 0xf8, 0x74, 0x36, 0xfc, 0x14, 0x01, 0x24, 0xdd, 0xf2, 0xb8, 0x62, 0xbe,
	0x99, 0xa9, 0x7d, 0x51, 0x41, 0x23, 0xf5, 0x90, 0xdd, 0x8d, 0xb9, 0xc2, 0x0e, 0x1a, 0x8a, 0x23,
	0x5e, 0x2d, 0x91, 0xd2, 0xfc, 0x58, 0xe3, 0xd4, 0x5f, 0xff, 0xfd, 0xb7, 0x3f, 0x96, 0x8e, 0xa2,
	0xb1, 0x75, 0x2a, 0x25, 0x13, 0xbc, 0xb9, 0x88, 0xc7, 0x34, 0x15, 0x79, 0xe0, 0xae, 0x38, 0xae,
	0x26, 0xc4, 0x17, 0xd1, 0x21, 0xee, 0x6d, 0xd1, 0x6a, 0x19, 0x18, 0x30, 0x30, 0x8c, 0x63, 0x04,
	0x54, 0x7a, 0xc2, 0x71, 0x61, 0x1e, 0xd7, 0xd1, 0xb0, 0x54, 0x9e, 0xa2, 0xd5, 0x43, 0xa4, 0x34,
	0x3f, 0x79, 0x7d, 0xd2, 0xb1, 0x0b, 0x3a, 0xeb, 0x7a, 0xb4, 0x71, 0x12, 0x18, 0xe7, 0xf0, 0xcc,
	0x42, 0x1c, 0x45, 0x94, 0x2b, 0xa2, 0xf5, 0x4e, 0x80, 0xc3, 0x71, 0x0d, 0x27, 0xbe, 0x81, 0xc6,
	0xf4, 0xe7, 0xb6, 0x60, 0xbd, 0x59, 0x58, 0xef, 0x18, 0xb0, 0x1d, 0xc1, 0x53, 0x0b, 0x91, 0xe0,
	0x44, 0xcf, 0xda, 0x45, 0x47, 0xf5, 0xf3, 0x8a, 0x5e, 0xd8, 0xb3, 0x5c, 0x5e, 0xd4, 0x95, 0xd5,
	0x39, 0x52, 0x9a, 0xaf, 0x5c, 0x9f, 0x75, 0x8c, 0x25, 0x9d, 0xc4, 0x92, 0x4e, 0x9d, 0xef, 0x36,
	0x1c, 0xc0, 0x9a, 0xc7, 0xb3, 0x19, 0x96, 0x17, 0x75, 0xe3, 0x2d, 0xca, 0x95, 0x74, 0xae, 0x4c,
	0xdf, 0xa1, 0x6a, 0x39, 0x10, 0x3b, 0xf5, 0xa8, 0x2b, 0x17, 0x02, 0x4f, 0x4a, 0xb3, 0x84, 0x7e,
	0xc5, 0x3f, 0x40, 0xd3, 0x5a, 0xdc, 0x56, 0x14, 0x73, 0x4e, 0x23, 0xb3, 0xd2, 0x61, 0x58, 0x69,
	0xca, 0xd1, 0xdf, 0xe8, 0xc2, 0xb8, 0x26, 0x6d, 0x9c, 0x81, 0x45, 0xaa, 0xf8, 0x28, 0x28, 0xc8,
	0x30, 0xe4, 0x96, 0x71, 0x27, 0x7b, 0x05, 0x7a, 0xdc, 0x44, 0x47, 0xbc, 0x20, 0x68, 0xf9, 0x01,
	0xd3, 0xf3, 0x2d, 0x5f, 0xc4, 0x5c, 0x55, 0x47, 0x48, 0x69, 0x7e, 0xa8, 0x71, 0x1a, 0xa0, 0x8e,
	0xe1, 0xb9, 0x05, 0x3d, 0x48, 0x44, 0x87, 0x78, 0x41, 0x40, 0x2c, 0xa5, 0xe3, 0x4e, 0x79, 0x41,
	0xb0, 0x60, 0x5e, 0x80, 0x00, 0xff, 0x10, 0x1d, 0x8b, 0xe8, 0x96, 0xc7, 0x38, 0xe3, 0xdd, 0x3e,
	0xc0, 0x51, 0x00, 0x3c, 0x0f, 0x80, 0xa7, 0xf1, 0xc9, 0x14, 0x30, 0xa5, 0xcf, 0x60, 0xe7, 0xd2,
	0xb1, 0x7e, 0x70, 0x5f, 0x6c, 0x85, 0x01, 0x55, 0xb4, 0xdd, 0x07, 0x3e, 0x76, 0x00, 0x78, 0x4a,
	0x9f, 0x03, 0x4f, 0xc7, 0x0a, 0xe0, 0x6f, 0xa0, 0x71, 0x43, 0xd2, 0x0a, 0xd8, 0x16, 0x53, 0x55,
	0x04, 0x88, 0x73, 0x80, 0x38, 0x85, 0x27, 0x0c, 0x2d, 0x81, 0x39, 0xc7, 0xad, 0x18, 0xd2, 0x7b,
	0xfa, 0x0d, 0x7f, 0x07, 0xd9, 0xd7, 0x56, 0xa4, 0xf7, 0x5e, 0x85, 0x94, 0xe6, 0xcb, 0x8d, 0x59,
	0x60, 0x9c, 0xc4, 0xe3, 0x96, 0x31, 0x82, 0x4d, 0x86, 0x0c, 0xa1, 0xab, 0x77, 0x5a, 0x13, 0x8d,
	0xf8, 0x11, 0xf5, 0x14, 0x6d, 0x57, 0xc7, 0x49, 0x69, 0xfe, 0x50, 0xe3, 0x2a, 0xb0, 0x5c, 0x46,
	0x15, 0x77, 0x71, 0x79, 0xd1, 0x53, 0x54, 0xb1, 0x2d, 0x8a, 0x4f, 0x2c, 0x68, 0x1a, 0x26, 0x38,
	0xd1, 0xaf, 0xfa, 0x93, 0x54, 0x8f, 0xc2, 0xc6, 0x75, 0xdc, 0x84, 0x1f, 0xbf, 0x8b, 0x46, 0xe8,
	0xe3, 0x90, 0x45, 0x54, 0x56, 0x27, 0x00, 0xea, 0x5b, 0x00, 0xf5, 0x4a, 0x11, 0xea, 0xd4, 0x92,
	0xa6, 0x39, 0x10, 0xcc, 0x22, 0xe0, 0xbb, 0x56, 0x2e, 0x11, 0x55, 0x27, 0x61, 0xff, 0x27, 0x7b,
	0xf6, 0xa2, 0xde, 0xea, 0x09, 0x53, 0x2c, 0x69, 0x44, 0x76, 0x7a, 0x82, 0x58, 0x19, 0xf6, 0x88,
	0x25, 0x22, 0x7c, 0x13, 0x55, 0xda, 0x54, 0xfa, 0x11, 0x0b, 0xf5, 0x9a, 0xd5, 0x29, 0x40, 0x3b,
	0x0e, 0x68, 0x33, 0xf8, 0x08, 0x6c, 0xce, 0xdc, 0xbc, 0xe3, 0xe6, 0xa9, 0xf1, 0x06, 0x9a, 0x4a,
	0xb4, 0x1a, 0x07, 0xb4, 0x25, 0xa9, 0xaa, 0x4e, 0xc3, 0x76, 0x9f, 0x73, 0x96, 0x85, 0xde, 0x1f,
	0xdc, 0x68, 0xd6, 0x8d, 0x03, 0xba, 0x4e, 0xd5, 0x1e, 0x4b, 0x69, 0x2e, 0xe9, 0xb8, 0x13, 0x7e,
	0x9e, 0x0a, 0xaf, 0xa2, 0x51, 0x26, 0x5b, 0x91, 0xd8, 0x14, 0xaa, 0x7a, 0x84, 0x94, 0xe6, 0x47,
	0x1b, 0x37, 0x80, 0xcf, 0xc1, 0xaf, 0x3e, 0xec, 0x51, 0xd5, 0xa3, 0x51, 0xfa, 0x21, 0x64, 0xc7,
	0x93, 0xe9, 0xd7, 0x6d, 0xee, 0x12, 0x8f, 0xdc, 0x71, 0xdd, 0x87, 0x22, 0xfa, 0x88, 0x46, 0x8e,
	0x3b, 0xc2, 0xa4, 0xab, 0x41, 0xf0, 0x7d, 0x34, 0xa5, 0x84, 0xf2, 0x82, 0x96, 0x1f, 0xc6, 0xad,
	0x58, 0x7a, 0x5d, 0x5a, 0xc5, 0xb0, 0x01, 0x5e, 0x06, 0xdc, 0xb3, 0xf8, 0xf4, 0x86, 0x9e, 0x26,
	0x0b, 0x6b, 0x0f, 0x08, 0x4c, 0x93, 0x79, 0xc6, 0x89, 0xa4, 0xbe, 0xe0, 0x6d, 0x79, 0xd9, 0x71,
	0x27, 0x80, 0x7b, 0x21, 0x8c, 0x1f, 0xe8, 0x49, 0xbc, 0x9a, 0xc0, 0x71, 0xaa, 0x2c, 0xdc, 0x0c,
	0x6c, 0xc4, 0x4b, 0x00, 0x77, 0x0e, 0x9f, 0x35, 0x70, 0x9c, 0xaa, 0x1d, 0x11, 0x7d, 0x94, 0x83,
	0xdc, 0xdc, 0x55, 0x34, 0x03, 0x5c, 0xa1, 0x0a, 0x00, 0x6b, 0xb7, 0xd0, 0x30, 0x04, 0x3f, 0x8c,
	0xd0, 0xe1, 0xb5, 0xfa, 0x83, 0xf5, 0xa5, 0xc5, 0xe9, 0x97, 0x70, 0x05, 0x8d, 0xac, 0x6f, 0xd4,
	0xdd, 0x8d, 0xa5, 0xc5, 0xe9, 0x92, 0x79, 0x59, 0x5d, 0x5b, 0x5b, 0x5a, 0x9c, 0x2e, 0xe3, 0x09,
	0x34, 0xb6, 0xb0, 0x7a, 0x7f, 0xed, 0xde, 0x92, 0x9e, 0x1b, 0xaa, 0xfd, 0xb9, 0x8c, 0x26, 0x6c,
	0x0c, 0x75, 0xa9, 0x8c, 0x03, 0x85, 0x6f, 0xa1, 0x31, 0x6b, 0x16, 0xd6, 0xb6, 0xf1, 0xf8, 0x2c,
	0x88, 0x76, 0x1c, 0x55, 0xea, 0x21, 0x33, 0xca, 0x6f, 0xb6, 0x31, 0xb2, 0x66, 0x60, 0x6d, 0xc7,
	0x1d, 0xf5, 0x93, 0xd1, 0xf7, 0xd1, 0x48, 0xe8, 0xed, 0x06, 0xc2, 0x6b, 0x57, 0x87, 0x9e, 0x10,
	0x25, 0xe7, 0x01, 0xb1, 0x86, 0xa7, 0xcc, 0xa2, 0xc4, 0xf2, 0x38, 0x57, 0xa6, 0xee, 0x50, 0xb5,
	0x66, 0x5e, 0x4c, 0x7c, 0x4c, 0xe0, 0xf0, 0x6d, 0x34, 0x6e, 0x1f, 0x5b, 0x6a, 0x37, 0x34, 0x27,
	0x40, 0x7a, 0xb6, 0xe0, 0xd9, 0x8d, 0xdd, 0x30, 0xdd, 0xba, 0x09, 0x9a, 0x5b, 0xb1, 0x4f, 0x7a,
	0x12, 0x47, 0x68, 0x4c, 0x3b, 0x85, 0x54, 0xde, 0x56, 0x58, 0x1d, 0x06, 0x2f, 0xda, 0x00, 0xee,
	0x95, 0xa2, 0x17, 0xdd, 0xde, 0x48, 0xa8, 0x08, 0xe3, 0x6d, 0xe6, 0x7b, 0x4a, 0x87, 0xae, 0x9d,
	0x1e, 0xe5, 0x24, 0x32, 0xd2, 0xea, 0x7d, 0xb3, 0x13, 0x31, 0xa5, 0x28, 0x27, 0x4a, 0xc0, 0x92,
	0x6d, 0x4f, 0x79, 0x44, 0x2a, 0x11, 0x51, 0xc7, 0xcd, 0x96, 0xa9, 0x7d, 0x36, 0x82, 0xa6, 0xeb,
	0x21, 0xbb, 0xc7, 0xa4, 0xd2, 0x2a, 0x96, 0x10, 0x8d, 0xaf, 0xa1, 0xc3, 0xa2, 0xd3, 0xd1, 0xfb,
	0xbd, 0x04, 0x96, 0xaf, 0x82, 0x14, 0x18, 0x4f, 0xaf, 0x2b, 0x2f, 0x82, 0xc5, 0xcc, 0xb4, 0xe3,
	0x5a, 0x3a, 0x7c, 0x13, 0x0d, 0x9b, 0x28, 0x58, 0x06, 0x86, 0x74, 0xe7, 0xdd, 0xf7, 0x1e, 0x13,
	0x1e, 0x6f, 0x6d, 0xd2, 0x48, 0x7f, 0x3a, 0x53, 0x74, 0x4b, 0x6a, 0x81, 0x3a, 0x54, 0xf9, 0x3d,
	0xc7, 0x35, 0x3c, 0xf8, 0xf3, 0x32, 0x42, 0x76, 0x97, 0xb7, 0x36, 0x77, 0xc1, 0x2c, 0x63, 0x8d,
	0x9f, 0x97, 0x01, 0xe3, 0x27, 0x65, 0xfc, 0x69, 0x79, 0x95, 0x07, 0xbb, 0x24, 0xa2, 0x2a, 0x8e,
	0x38, 0xf8, 0x45, 0x9f, 0x53, 0x74, 0xd9, 0x36, 0xe5, 0x10, 0x0e, 0x1c, 0xd2, 0xec, 0x10, 0x2f,
	0x0c, 0x23, 0xb1, 0x0d, 0x58, 0x44, 0x44, 0x57, 0x3d, 0xde, 0xce, 0xfb, 0x78, 0xcb, 0x17, 0x5c,
	0x79, 0x8c, 0x4b, 0xe2, 0x45, 0x94, 0x78, 0x81, 0x14, 0x44, 0xc6, 0x61, 0x18, 0x30, 0xda, 0x7e,
	0x55, 0x2b, 0x8a, 0x93, 0x40, 0x74, 0x99, 0xef, 0x05, 0xa4, 0xbe, 0xb2, 0x48, 0x98, 0xd4, 0x70,
	0x7a, 0x52, 0x8b, 0xad, 0x0f, 0x1e, 0xad, 0x4b, 0x3f, 0x62, 0x8a, 0x46, 0xcc, 0x93, 0x0e, 0x59,
	0x59, 0xdd, 0x58, 0x7a, 0x8b, 0xa8, 0x1e, 0x93, 0xa4, 0xc3, 0x02, 0x45, 0x23, 0xe2, 0x7b, 0x9c,
	0x08, 0x2d, 0xf0, 0x26, 0x84, 0xa8, 0x36, 0x61, 0x9c, 0xf8, 0x82, 0x3f, 0x8a, 0xb9, 0x0f, 0x71,
	0x6f, 0x87, 0xa9, 0x1e, 0xb9, 0xe4, 0xf9, 0x8a, 0x6d, 0xd3, 0x96, 0x7e, 0x61, 0xfc, 0x52, 0xc2,
	0x3b, 0xaf, 0x04, 0x09, 0x23, 0xba, 0xad, 0xb7, 0xed, 0xc7, 0x31, 0x8d, 0x18, 0x95, 0x5a, 0x6f,
	0x6d, 0xea, 0xa9, 0xde, 0x65, 0xc7, 0x1d, 0xb3, 0x9f, 0xdd, 0xd8, 0xc5, 0x7f, 0x2f, 0xa3, 0xd9,
	0xfd, 0xbe, 0xca, 0xee, 0xba, 0xaf, 0x8c, 0xf6, 0x3e, 0x2f, 0xe3, 0xdf, 0xee, 0xa3, 0xbd, 0x9d,
	0x1e, 0x8d, 0x68, 0x5e, 0x29, 0x24, 0x55, 0x8a, 0xd1, 0xa5, 0x8c, 0x37, 0xa5, 0x8a, 0xb4, 0xa1,
	0xe7, 0xb7, 0x3c, 0xe5, 0xf7, 0xf4, 0x13, 0x93, 0xc4, 0xf7, 0x24, 0x7d, 0x8d, 0x71, 0x49, 0xb9,
	0x64, 0x5a, 0xfc, 0xcb, 0x4e, 0xb3, 0x43, 0x32, 0xcb, 0x25, 0xda, 0xce, 0x1b, 0xe0, 0xff, 0x4f,
	0xc9, 0x33, 0x39, 0xbd, 0x2c, 0x58, 0xb5, 0xe0, 0x18, 0x4d, 0x14, 0xc0, 0xac, 0x7b, 0xae, 0x81,
	0x96, 0xbf, 0x8f, 0x46, 0x17, 0x63, 0x73, 0xaa, 0xe1, 0x77, 0xf6, 0x6a, 0x5b, 0xf5, 0x3c, 0x45,
	0x76, 0xb4, 0xc6, 0x0d, 0x04, 0x31, 0x10, 0x56, 0xd5, 0x70, 0x0c, 0xb6, 0x2d, 0xbb, 0xe3, 0x8e,
	0x1b, 0x9a, 0x87, 0x40, 0x52, 0xfb, 0x69, 0x09, 0xe1, 0xbc, 0x77, 0xda, 0x08, 0xf8, 0x5d, 0x34,
	0x0c, 0xae, 0x54, 0x2d, 0x91, 0xa1, 0xf9, 0xca, 0xf5, 0xd1, 0x24, 0xc9, 0x6c, 0x1c, 0x05, 0x79,
	0xa6, 0xf1, 0xa4, 0xe6, 0xd0, 0x1f, 0x05, 0x12, 0x38, 0xae, 0x21, 0xc7, 0xb7, 0x51, 0xc5, 0x9e,
	0x14, 0x39, 0x5f, 0x4d, 0x53, 0x35, 0x1b, 0xd6, 0x8b, 0xde, 0xea, 0xb8, 0xc8, 0x1c, 0x0f, 0x9a,
	0xa3, 0xb6, 0x8c, 0x26, 0xeb, 0x21, 0xbb, 0x43, 0x41, 0x1a, 0x08, 0x15, 0x37, 0xd0, 0x08, 0xe4,
	0x84, 0xac, 0x6d, 0x73, 0x69, 0x9b, 0xe1, 0xa2, 0x31, 0x2b, 0x53, 0xb3, 0x8d, 0x47, 0xe1, 0x9c,
	0xd5, 0x61, 0xf8, 0x70, 0x0f, 0x46, 0x6a, 0xbf, 0x2e, 0xa1, 0xf3, 0x19, 0x90, 0x89, 0xd3, 0x0b,
	0x26, 0x27, 0x62, 0x82, 0xeb, 0xd3, 0x42, 0x3e, 0x3f, 0x3a, 0xbe, 0x8d, 0x0e, 0x49, 0xf6, 0x09,
	0xb5, 0xdf, 0xf7, 0x0a, 0xb0, 0xbc, 0x8c, 0xcf, 0x17, 0x63, 0x11, 0xc4, 0xc3, 0x50, 0x30, 0xb0,
	0x50, 0x1a, 0x91, 0x80, 0xb1, 0xf6, 0xaf, 0x12, 0x7a, 0xf9, 0x29, 0xe2, 0x59, 0x4b, 0xb4, 0xd0,
	0xb8, 0xd4, 0x31, 0xb1, 0x65, 0x90, 0xac, 0x41, 0xc6, 0x9d, 0x75, 0x4f, 0x53, 0x2f, 0x07, 0xc2,
	0x53, 0x59, 0xf2, 0xb2, 0xd1, 0xa3, 0x24, 0xb0, 0x86, 0x91, 0x40, 0x20, 0x49, 0x47, 0x44, 0x36,
	0x2f, 0x24, 0x00, 0x24, 0x1d, 0xb7, 0x02, 0x0f, 0x6b, 0x00, 0x88, 0x1f, 0xa1, 0xa9, 0x24, 0x59,
	0x4c, 0xd6, 0x28, 0xef, 0xb3, 0xc6, 0xb7, 0x61, 0x8d, 0xd7, 0xf0, 0x2b, 0x4f, 0x59, 0xc3, 0x4f,
	0xbf, 0x42, 0x27, 0xe1, 0x09, 0xb2, 0x59, 0xab, 0xf6, 0x65, 0x19, 0xcd, 0xe4, 0x76, 0xdb, 0x3d,
	0xd1, 0x1d, 0xc4, 0x0a, 0x6f, 0xa5, 0x87, 0x88, 0xb1, 0x43, 0x0d, 0x98, 0x4e, 0xe1, 0x13, 0xf7,
	0x44, 0xd7, 0x9e, 0x04, 0xf2, 0xa0, 0xe3, 0xe4, 0x76, 0x72, 0x9c, 0x0c, 0x01, 0xeb, 0x65, 0x60,
	0x3d, 0x8f, 0xcf, 0x15, 0x4d, 0x18, 0xa4, 0x40, 0x7b, 0x8e, 0x14, 0x86, 0x0e, 0x1b, 0x6f, 0xb7,
	0xf1, 0xf0, 0x3d, 0x40, 0x78, 0x17, 0x37, 0x5d, 0xe3, 0x99, 0xc2, 0x78, 0xa9, 0xb6, 0xa1, 0x0e,
	0x87, 0x42, 0x52, 0x62, 0x03, 0x5e, 0x44, 0xc3, 0x88, 0x4a, 0xca, 0x95, 0xf7, 0xc4, 0xc0, 0xe8,
	0xb8, 0x76, 0x81, 0xda, 0xcf, 0x4a, 0x68, 0xae, 0x4f, 0x6b, 0x76, 0x73, 0xbc, 0xde, 0xef, 0xa6,
	0xfa, 0x62, 0x75, 0x4f, 0x74, 0xb3, 0xeb, 0xdc, 0x46, 0x92, 0xe8, 0xd1, 0x28, 0x12, 0x91, 0x4c,
	0xfc, 0xf4, 0x9d, 0xfd, 0xfc, 0x34, 0xbd, 0x07, 0x19, 0x3f, 0xf5, 0x93, 0xfb, 0xc5, 0x3e, 0x6e,
	0xfa, 0xbb, 0x72, 0x41, 0xa4, 0x25, 0x00, 0x1f, 0xc0, 0x94, 0xb7, 0xfa, 0x4c, 0x79, 0x01, 0x98,
	0xce, 0xe0, 0x53, 0x77, 0x33, 0xd9, 0x0f, 0x36, 0xe6, 0xad, 0xa2, 0x31, 0x2f, 0x02, 0x33, 0xc1,
	0x67, 0x8a, 0xc6, 0xb4, 0x28, 0xdf, 0xa4, 0x25, 0x7f, 0x51, 0x42, 0xc7, 0xf6, 0xa8, 0xcd, 0xda,
	0xf2, 0xcd, 0xa2, 0x2d, 0x91, 0x93, 0x52, 0x7c, 0xed, 0xd6, 0xfc, 0x7d, 0x19, 0x1d, 0xcd, 0x89,
	0xb5, 0x10, 0x79, 0xb2, 0x47, 0x07, 0x31, 0xe7, 0xdb, 0x7d, 0xe6, 0x4c, 0xb3, 0x35, 0xa0, 0xf4,
	0x0d, 0xfe, 0xc1, 0xf6, 0x7c, 0xbb, 0x68, 0xcf, 0xf4, 0x5a, 0x50, 0xb4, 0x67, 0x02, 0xf3, 0x4d,
	0x1a, 0xf4, 0x57, 0x25, 0x54, 0xdd, 0xab, 0x39, 0x6b, 0xd1, 0x77, 0x8a, 0x16, 0x1d, 0x77, 0x6c,
	0x9c, 0xd7, 0x44, 0x8d, 0x13, 0x20, 0xd4, 0x2c, 0xc6, 0xda, 0xa6, 0x49, 0xec, 0xb4, 0xec, 0x5f,
	0x8f, 0x59, 0x8d, 0x54, 0x5f, 0x9f, 0x59, 0x13, 0x8d, 0x0e, 0x68, 0xd6, 0x04, 0xe6, 0x9b, 0x34,
	0xeb, 0x2f, 0x8b, 0x66, 0xb5, 0x9a, 0xb3, 0x66, 0xbd, 0x59, 0x34, 0x6b, 0x5a, 0x80, 0x33, 0xd3,
	0xd9, 0x1d, 0x3d, 0xaf, 0x14, 0xe7, 0x45, 0xd9, 0xf4, 0x03, 0x54, 0xcb, 0xf2, 0x06, 0x2b, 0xd7,
	0xd2, 0xe3, 0x50, 0x44, 0x3a, 0x7d, 0xd8, 0xf2, 0x78, 0x7b, 0x80, 0x9c, 0xe9, 0x13, 0x74, 0xe1,
	0xc9, 0xd8, 0x56, 0x01, 0x2e, 0x1a, 0xf1, 0xcd, 0x80, 0x45, 0x7f, 0x03, 0xd0, 0xaf, 0xe3, 0x6b,
	0x96, 0xce, 0x24, 0xa4, 0x5b, 0x5e, 0x96, 0x3c, 0x2b, 0x41, 0x28, 0x20, 0x99, 0xf0, 0x95, 0x6a,
	0x25, 0x01, 0xaa, 0x6d, 0xa0, 0x53, 0x39, 0x85, 0xaf, 0x42, 0xd5, 0x75, 0x0d, 0x8a, 0xae, 0x03,
	0x6c, 0xd8, 0xda, 0x8f, 0x4b, 0xe8, 0xcc, 0x41, 0xb0, 0xf6, 0x63, 0x2e, 0x16, 0xad, 0x39, 0xad,
	0xad, 0x99, 0xa7, 0x7b, 0x51, 0x86, 0xfb, 0x51, 0x19, 0x9d, 0x3d, 0x40, 0x94, 0x01, 0xd3, 0xa0,
	0xab, 0x68, 0xcc, 0x94, 0xa7, 0xb3, 0x6a, 0x45, 0x5a, 0x3d, 0x36, 0x0b, 0x98, 0x02, 0x85, 0x21,
	0x6a, 0xb6, 0xf1, 0xeb, 0xa9, 0x1b, 0x1b, 0x47, 0xb4, 0xb5, 0x0d, 0x7c, 0x4c, 0xe7, 0x9d, 0xb1,
	0x24, 0x5b, 0x54, 0x4a, 0xaf, 0x0b, 0x77, 0x96, 0xa2, 0x03, 0xd7, 0x13, 0x07, 0x3e, 0x54, 0xcc,
	0x7b, 0x57, 0x52, 0xe7, 0x95, 0x7d, 0x08, 0xfd, 0x4e, 0x5c, 0xfb, 0xb2, 0x84, 0xce, 0x3d, 0x41,
	0x0d, 0xd6, 0x28, 0x2b, 0x45, 0xa3, 0xd4, 0x9c, 0x3c, 0x5d, 0x43, 0xdf, 0x17, 0xd7, 0x22, 0xe1,
	0x53, 0x29, 0x19, 0xef, 0x1a, 0xa1, 0xb3, 0x5a, 0xa4, 0x4e, 0xfe, 0x28, 0x57, 0xfa, 0xd2, 0xf5,
	0xc2, 0xbc, 0xee, 0x3f, 0x07, 0x4b, 0x3d, 0x70, 0xea, 0xf3, 0xcc, 0xe6, 0x73, 0xfa, 0xcc, 0x97,
	0x5e, 0xc9, 0x8c, 0x28, 0xcf, 0x61, 0x35, 0x9b, 0x19, 0x1d, 0x6c, 0xb5, 0xaf, 0xcc, 0x6d, 0xea,
	0xe0, 0xef, 0xb7, 0x76, 0x7b, 0xef, 0xd9, 0xed, 0x96, 0xe6, 0x36, 0x56, 0xfa, 0x17, 0x6d, 0xba,
	0x3f, 0x95, 0xd0, 0x89, 0x2c, 0xaa, 0x2d, 0xb3, 0x40, 0x27, 0x36, 0x7e, 0x8f, 0x6d, 0xd3, 0x01,
	0x6c, 0xb6, 0x86, 0x26, 0x3d, 0x03, 0xd2, 0xea, 0x88, 0x68, 0xcb, 0x33, 0xa6, 0x98, 0xbc, 0x7e,
	0xd9, 0x39, 0x78, 0x29, 0xc7, 0x3e, 0x2f, 0x03, 0x83, 0x3b, 0xe1, 0xe5, 0x5f, 0x6b, 0x17, 0xd0,
	0x44, 0x61, 0x1e, 0x8f, 0xa0, 0xa1, 0x0f, 0x9a, 0x6b, 0xd3, 0x2f, 0x61, 0x84, 0x0e, 0x6f, 0xd4,
	0xdd, 0xd6, 0x9d, 0x0f, 0xa6, 0x4b, 0xb5, 0x2f, 0xca, 0x70, 0x5b, 0xcf, 0xad, 0x30, 0x50, 0xce,
	0x3d, 0x48, 0x95, 0xf3, 0xc3, 0x7c, 0x29, 0x71, 0x08, 0x6a, 0x15, 0xb7, 0x81, 0xfb, 0xcd, 0x62,
	0x29, 0xf1, 0x4a, 0x56, 0x4a, 0xb4, 0xa5, 0x49, 0x5b, 0x41, 0x64, 0xdc, 0x14, 0x61, 0x44, 0x10,
	0x50, 0xdf, 0x94, 0x26, 0x32, 0x44, 0xdc, 0x44, 0xa3, 0xdb, 0x1d, 0xd9, 0x0a, 0x3d, 0xd5, 0xb3,
	0xc7, 0x7d, 0x7a, 0xc9, 0xad, 0x2f, 0x2f, 0xdf, 0x20, 0x7a, 0x22, 0x29, 0x3c, 0x76, 0x58, 0x40,
	0xf5, 0xf3, 0x26, 0x25, 0x6d, 0xb1, 0xc3, 0x03, 0xe1, 0xb5, 0x69, 0xdb, 0x1d, 0xd9, 0xee, 0xc8,
	0x35, 0x4f, 0xf5, 0x6a, 0xef, 0xc2, 0x9d, 0xd3, 0xea, 0x6c, 0xc0, 0x9b, 0x7f, 0xed, 0x7d, 0xb8,
	0xf7, 0xe4, 0xc1, 0xec, 0xd6, 0xbf, 0x6d, 0xda, 0x72, 0x12, 0xc0, 0x2a, 0xd7, 0xe7, 0x6c, 0xb2,
	0xe7, 0x52, 0x29, 0xe2, 0xc8, 0xa7, 0x12, 0x68, 0x33, 0xcf, 0xd6, 0x59, 0x1f, 0xd0, 0xdb, 0xa6,
	0x9c, 0xac, 0xfd, 0xa3, 0x2f, 0x09, 0x37, 0x7d, 0x9b, 0x01, 0xec, 0x7b, 0xad, 0x2f, 0x5b, 0x7b,
	0x86, 0x1a, 0xeb, 0xd0, 0x73, 0xd4, 0x58, 0x3f, 0x46, 0xb6, 0x0d, 0xd1, 0x32, 0x87, 0x80, 0xed,
	0x4f, 0x5e, 0x70, 0xf6, 0xff, 0x28, 0xab, 0x1f, 0x1b, 0x05, 0xd2, 0x2b, 0x9b, 0xd6, 0x8b, 0xda,
	0x0d, 0x4d, 0xc1, 0xcc, 0xb6, 0xb3, 0x72, 0x6b, 0xd9, 0xf6, 0x95, 0xe1, 0xaa, 0xdd, 0x44, 0xe3,
	0x79, 0x94, 0x7c, 0xc9, 0xff, 0x25, 0x3c, 0x85, 0x2a, 0xab, 0x0f, 0x36, 0xd6, 0x37, 0xea, 0x2b,
	0x8b, 0xcd, 0x95, 0x3b, 0xd3, 0xa5, 0x62, 0xd9, 0xbf, 0x5c, 0xfb, 0xcb, 0x30, 0x3a, 0x69, 0xd5,
	0x67, 0x40, 0xd6, 0x28, 0x6f, 0x33, 0xde, 0x75, 0xe9, 0xc7, 0x31, 0x95, 0x0a, 0xbf, 0x81, 0xa0,
	0x2f, 0xd9, 0xca, 0x9a, 0xb8, 0x36, 0xea, 0xa0, 0xc3, 0xee, 0xe2, 0xf2, 0x03, 0x77, 0x05, 0x4f,
	0x68, 0x61, 0xa1, 0xbd, 0x19, 0x47, 0xdc, 0x71, 0x47, 0xf4, 0xe3, 0x83, 0x88, 0xe3, 0x0f, 0xd1,
	0x1c, 0xe3, 0x69, 0x4d, 0x25, 0x32, 0x78, 0x99, 0x93, 0xa5, 0xb5, 0x06, 0xcd, 0xce, 0xda, 0x89,
	0x5b, 0x64, 0x2c, 0xc4, 0xb2, 0x38, 0xee, 0x4c, 0x36, 0x68, 0xc5, 0x6a, 0xb6, 0x71, 0x03, 0x21,
	0x4e, 0x1f, 0x1b, 0x35, 0x53, 0x5b, 0xcb, 0x4e, 0x9b, 0x82, 0x1a, 0x53, 0xcf, 0x9a, 0x8e, 0x6f,
	0x82, 0xad, 0x25, 0x73, 0xdc, 0x31, 0x3d, 0x61, 0x1a, 0x25, 0x6b, 0x68, 0x82, 0x3e, 0x0e, 0xa9,
	0xaf, 0x68, 0xdb, 0x74, 0x59, 0x8d, 0x8f, 0xa5, 0x67, 0x03, 0xc0, 0xe4, 0x3a, 0x61, 0x09, 0x71,
	0xbe, 0xc3, 0x3a, 0x9e, 0x0c, 0xc2, 0x1e, 0xed, 0xa0, 0xe3, 0xde, 0xb6, 0xc7, 0x02, 0x6f, 0x33,
	0xd0, 0xdf, 0x2c, 0x43, 0xc1, 0x25, 0x4d, 0x3a, 0x97, 0xc3, 0xb0, 0x9f, 0xae, 0x00, 0xfa, 0x05,
	0x5c, 0x03, 0xf4, 0x74, 0x3f, 0xa5, 0x6c, 0x24, 0x65, 0x73, 0xdc, 0x63, 0xe9, 0xa8, 0x9b, 0x0c,
	0x9a, 0x16, 0xe6, 0x0a, 0xc2, 0xa9, 0xe4, 0x29, 0x3d, 0x34, 0x89, 0xc7, 0xb2, 0x44, 0x66, 0x23,
	0x2f, 0x72, 0x0e, 0xf5, 0x48, 0x32, 0x98, 0x82, 0xe2, 0x16, 0x9a, 0x61, 0xd2, 0x6e, 0xd9, 0x56,
	0xba, 0x28, 0x74, 0x86, 0x47, 0x93, 0x6e, 0x25, 0xbe, 0x94, 0xef, 0x9b, 0xd9, 0x1c, 0x87, 0xc9,
	0x9c, 0xe4, 0x22, 0x22, 0x5c, 0x28, 0xc7, 0x3d, 0xc2, 0xa4, 0xd9, 0x8b, 0xf5, 0x64, 0x0a, 0xef,
	0xa0, 0xb3, 0x99, 0x62, 0x92, 0x6e, 0x9f, 0x31, 0x66, 0xb1, 0x6b, 0x7c, 0x0d, 0x16, 0xbb, 0x82,
	0xe7, 0x8b, 0xea, 0xb1, 0x77, 0xc3, 0x84, 0x25, 0x5b, 0xd4, 0x71, 0x4f, 0xa5, 0xcf, 0x49, 0xb0,
	0x31, 0x34, 0xe6, 0xe4, 0xfb, 0x67, 0xd6, 0xd7, 0x32, 0xd3, 0xf8, 0x7b, 0xf9, 0x88, 0x5f, 0xca,
	0x6f, 0x9c, 0x62, 0xc4, 0x9f, 0xcc, 0xdd, 0x49, 0x8b, 0x51, 0x3f, 0xef, 0x14, 0xe5, 0x67, 0x72,
	0x8a, 0x26, 0x1a, 0xcb, 0xba, 0x87, 0x08, 0x62, 0x64, 0xc5, 0x59, 0x08, 0xe3, 0x75, 0xd3, 0x25,
	0xcc, 0x6c, 0x77, 0x50, 0x13, 0x71, 0xd4, 0xcf, 0xfa, 0x87, 0xd8, 0xb6, 0x06, 0x5b, 0xd0, 0x10,
	0x6c, 0xe9, 0xab, 0x1d, 0xb4, 0xa4, 0x87, 0x1a, 0xe7, 0x00, 0xe6, 0x24, 0x3e, 0xbe, 0x72, 0x60,
	0xf3, 0x70, 0xda, 0x32, 0x37, 0xf4, 0xfb, 0xba, 0xd6, 0xcb, 0x1d, 0x34, 0x1d, 0x1a, 0xe7, 0x4f,
	0x2d, 0x53, 0x1d, 0x87, 0x0c, 0xe6, 0x94, 0xf3, 0x84, 0x10, 0xe1, 0x4e, 0x85, 0x85, 0x77, 0x59,
	0xfb, 0x4d, 0x5f, 0x39, 0xc0, 0xc4, 0xaf, 0xfd, 0x93, 0xda, 0xc9, 0x22, 0x74, 0xda, 0x0f, 0x24,
	0xf9, 0x02, 0xab, 0x88, 0x95, 0x54, 0x1e, 0x2c, 0x92, 0x35, 0xf7, 0x5f, 0x50, 0x66, 0x74, 0x3f,
	0x7f, 0x94, 0x2d, 0x08, 0xae, 0xe8, 0xe3, 0x41, 0x2a, 0xee, 0x9f, 0x99, 0xda, 0x56, 0x11, 0xcf,
	0x7e, 0x7a, 0x5d, 0xdf, 0x18, 0x61, 0xc0, 0x1e, 0x8f, 0xe3, 0x4e, 0x8e, 0x28, 0x6b, 0x97, 0xa7,
	0xf5, 0x2d, 0x4b, 0x0d, 0x17, 0x44, 0x78, 0xc2, 0x6f, 0x27, 0xbf, 0xbd, 0x94, 0x01, 0x00, 0xb4,
	0xb7, 0xe8, 0x29, 0x6f, 0x75, 0xf3, 0x11, 0xf5, 0xd5, 0x3e, 0x25, 0xb2, 0xc2, 0x2f, 0x2f, 0xb5,
	0x4f, 0xcb, 0xe8, 0x88, 0xde, 0xe2, 0xd0, 0x4a, 0xca, 0xf5, 0x16, 0x72, 0x3f, 0xc2, 0x0c, 0x3d,
	0xd7, 0x8f, 0x30, 0x87, 0xfe, 0x67, 0x3f, 0xc2, 0x94, 0x5e, 0xc8, 0x8f, 0x30, 0xb5, 0x3f, 0x18,
	0x4d, 0xdc, 0x17, 0x6d, 0xd6, 0xd9, 0x1d, 0xac, 0xcb, 0x82, 0xdf, 0xcc, 0x1b, 0x65, 0xef, 0xbf,
	0x48, 0x33, 0x80, 0x31, 0x81, 0x2b, 0x77, 0xf7, 0xfe, 0x83, 0xd4, 0xff, 0x2b, 0xca, 0xd0, 0xf3,
	0xfe, 0x8a, 0x62, 0x6e, 0x35, 0x4f, 0xff, 0x15, 0x25, 0xf7, 0xff, 0xc8, 0xf0, 0x13, 0xfe, 0x1f,
	0x79, 0xd8, 0xa3, 0x3c, 0xfb, 0x3d, 0x42, 0xf6, 0x44, 0x1c, 0xb4, 0x89, 0x61, 0xcc, 0xfe, 0x1f,
	0xa9, 0x35, 0x41, 0x87, 0x8b, 0x54, 0x9f, 0xcc, 0x03, 0x76, 0xaa, 0x3e, 0x2b, 0xa1, 0xd3, 0xc6,
	0x6f, 0x4c, 0xad, 0x85, 0xb6, 0x5f, 0x4c, 0xb1, 0x6e, 0x11, 0x55, 0xec, 0xbd, 0x32, 0xf7, 0x5b,
	0x59, 0x9a, 0x27, 0x34, 0xb9, 0x8e, 0x2b, 0x8a, 0x98, 0xff, 0xdb, 0x88, 0xa1, 0xb4, 0x3b, 0x1d,
	0x99, 0x37, 0xbd, 0xd7, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x9d, 0x55, 0xf0, 0xc5, 0x27,
	0x00, 0x00,
}
