// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/reflection.proto

/*
Package reflection is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/reflection.proto

It has these top-level messages:
	ApiRDFAllowedEnumValueDescriptor
	ApiRDFValueFieldDescriptor
	ApiRDFValueDescriptor
	ApiMethod
	ApiOutputPluginDescriptor
	ApiGetRDFValueDescriptorArgs
	ApiListRDFValueDescriptorsResult
	ApiAff4AttributeDescriptor
	ApiListAff4AttributeDescriptorsResult
	ApiListOutputPluginDescriptorsResult
	ApiListApiMethodsResult
*/
package reflection

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiRDFValueDescriptor_Kind int32

const (
	ApiRDFValueDescriptor_PRIMITIVE ApiRDFValueDescriptor_Kind = 0
	ApiRDFValueDescriptor_STRUCT    ApiRDFValueDescriptor_Kind = 1
)

var ApiRDFValueDescriptor_Kind_name = map[int32]string{
	0: "PRIMITIVE",
	1: "STRUCT",
}
var ApiRDFValueDescriptor_Kind_value = map[string]int32{
	"PRIMITIVE": 0,
	"STRUCT":    1,
}

func (x ApiRDFValueDescriptor_Kind) Enum() *ApiRDFValueDescriptor_Kind {
	p := new(ApiRDFValueDescriptor_Kind)
	*p = x
	return p
}
func (x ApiRDFValueDescriptor_Kind) String() string {
	return proto.EnumName(ApiRDFValueDescriptor_Kind_name, int32(x))
}
func (x *ApiRDFValueDescriptor_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiRDFValueDescriptor_Kind_value, data, "ApiRDFValueDescriptor_Kind")
	if err != nil {
		return err
	}
	*x = ApiRDFValueDescriptor_Kind(value)
	return nil
}
func (ApiRDFValueDescriptor_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type ApiMethod_ResultKind int32

const (
	ApiMethod_NONE          ApiMethod_ResultKind = 0
	ApiMethod_VALUE         ApiMethod_ResultKind = 1
	ApiMethod_BINARY_STREAM ApiMethod_ResultKind = 2
)

var ApiMethod_ResultKind_name = map[int32]string{
	0: "NONE",
	1: "VALUE",
	2: "BINARY_STREAM",
}
var ApiMethod_ResultKind_value = map[string]int32{
	"NONE":          0,
	"VALUE":         1,
	"BINARY_STREAM": 2,
}

func (x ApiMethod_ResultKind) Enum() *ApiMethod_ResultKind {
	p := new(ApiMethod_ResultKind)
	*p = x
	return p
}
func (x ApiMethod_ResultKind) String() string {
	return proto.EnumName(ApiMethod_ResultKind_name, int32(x))
}
func (x *ApiMethod_ResultKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiMethod_ResultKind_value, data, "ApiMethod_ResultKind")
	if err != nil {
		return err
	}
	*x = ApiMethod_ResultKind(value)
	return nil
}
func (ApiMethod_ResultKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ApiOutputPluginDescriptor_PluginType int32

const (
	ApiOutputPluginDescriptor_LEGACY  ApiOutputPluginDescriptor_PluginType = 0
	ApiOutputPluginDescriptor_INSTANT ApiOutputPluginDescriptor_PluginType = 1
	ApiOutputPluginDescriptor_LIVE    ApiOutputPluginDescriptor_PluginType = 2
)

var ApiOutputPluginDescriptor_PluginType_name = map[int32]string{
	0: "LEGACY",
	1: "INSTANT",
	2: "LIVE",
}
var ApiOutputPluginDescriptor_PluginType_value = map[string]int32{
	"LEGACY":  0,
	"INSTANT": 1,
	"LIVE":    2,
}

func (x ApiOutputPluginDescriptor_PluginType) Enum() *ApiOutputPluginDescriptor_PluginType {
	p := new(ApiOutputPluginDescriptor_PluginType)
	*p = x
	return p
}
func (x ApiOutputPluginDescriptor_PluginType) String() string {
	return proto.EnumName(ApiOutputPluginDescriptor_PluginType_name, int32(x))
}
func (x *ApiOutputPluginDescriptor_PluginType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiOutputPluginDescriptor_PluginType_value, data, "ApiOutputPluginDescriptor_PluginType")
	if err != nil {
		return err
	}
	*x = ApiOutputPluginDescriptor_PluginType(value)
	return nil
}
func (ApiOutputPluginDescriptor_PluginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type ApiRDFAllowedEnumValueDescriptor struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *int64   `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Doc              *string  `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	Labels           []string `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiRDFAllowedEnumValueDescriptor) Reset()         { *m = ApiRDFAllowedEnumValueDescriptor{} }
func (m *ApiRDFAllowedEnumValueDescriptor) String() string { return proto.CompactTextString(m) }
func (*ApiRDFAllowedEnumValueDescriptor) ProtoMessage()    {}
func (*ApiRDFAllowedEnumValueDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *ApiRDFAllowedEnumValueDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiRDFAllowedEnumValueDescriptor) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ApiRDFAllowedEnumValueDescriptor) GetDoc() string {
	if m != nil && m.Doc != nil {
		return *m.Doc
	}
	return ""
}

func (m *ApiRDFAllowedEnumValueDescriptor) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ApiRDFValueFieldDescriptor struct {
	Name             *string                             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             *string                             `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Index            *uint32                             `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	Repeated         *bool                               `protobuf:"varint,4,opt,name=repeated" json:"repeated,omitempty"`
	Dynamic          *bool                               `protobuf:"varint,5,opt,name=dynamic" json:"dynamic,omitempty"`
	Doc              *string                             `protobuf:"bytes,6,opt,name=doc" json:"doc,omitempty"`
	FriendlyName     *string                             `protobuf:"bytes,7,opt,name=friendly_name,json=friendlyName" json:"friendly_name,omitempty"`
	ContextHelpUrl   *string                             `protobuf:"bytes,8,opt,name=context_help_url,json=contextHelpUrl" json:"context_help_url,omitempty"`
	Default          *google_protobuf.Any                `protobuf:"bytes,9,opt,name=default" json:"default,omitempty"`
	Labels           []string                            `protobuf:"bytes,10,rep,name=labels" json:"labels,omitempty"`
	AllowedValues    []*ApiRDFAllowedEnumValueDescriptor `protobuf:"bytes,11,rep,name=allowed_values,json=allowedValues" json:"allowed_values,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *ApiRDFValueFieldDescriptor) Reset()                    { *m = ApiRDFValueFieldDescriptor{} }
func (m *ApiRDFValueFieldDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ApiRDFValueFieldDescriptor) ProtoMessage()               {}
func (*ApiRDFValueFieldDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiRDFValueFieldDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiRDFValueFieldDescriptor) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ApiRDFValueFieldDescriptor) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ApiRDFValueFieldDescriptor) GetRepeated() bool {
	if m != nil && m.Repeated != nil {
		return *m.Repeated
	}
	return false
}

func (m *ApiRDFValueFieldDescriptor) GetDynamic() bool {
	if m != nil && m.Dynamic != nil {
		return *m.Dynamic
	}
	return false
}

func (m *ApiRDFValueFieldDescriptor) GetDoc() string {
	if m != nil && m.Doc != nil {
		return *m.Doc
	}
	return ""
}

func (m *ApiRDFValueFieldDescriptor) GetFriendlyName() string {
	if m != nil && m.FriendlyName != nil {
		return *m.FriendlyName
	}
	return ""
}

func (m *ApiRDFValueFieldDescriptor) GetContextHelpUrl() string {
	if m != nil && m.ContextHelpUrl != nil {
		return *m.ContextHelpUrl
	}
	return ""
}

func (m *ApiRDFValueFieldDescriptor) GetDefault() *google_protobuf.Any {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *ApiRDFValueFieldDescriptor) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ApiRDFValueFieldDescriptor) GetAllowedValues() []*ApiRDFAllowedEnumValueDescriptor {
	if m != nil {
		return m.AllowedValues
	}
	return nil
}

type ApiRDFValueDescriptor struct {
	Name             *string                       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Doc              *string                       `protobuf:"bytes,2,opt,name=doc" json:"doc,omitempty"`
	Kind             *ApiRDFValueDescriptor_Kind   `protobuf:"varint,3,opt,name=kind,enum=ApiRDFValueDescriptor_Kind" json:"kind,omitempty"`
	Default          *google_protobuf.Any          `protobuf:"bytes,4,opt,name=default" json:"default,omitempty"`
	Parents          []string                      `protobuf:"bytes,5,rep,name=parents" json:"parents,omitempty"`
	Fields           []*ApiRDFValueFieldDescriptor `protobuf:"bytes,6,rep,name=fields" json:"fields,omitempty"`
	UnionFieldName   *string                       `protobuf:"bytes,7,opt,name=union_field_name,json=unionFieldName" json:"union_field_name,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ApiRDFValueDescriptor) Reset()                    { *m = ApiRDFValueDescriptor{} }
func (m *ApiRDFValueDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ApiRDFValueDescriptor) ProtoMessage()               {}
func (*ApiRDFValueDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiRDFValueDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiRDFValueDescriptor) GetDoc() string {
	if m != nil && m.Doc != nil {
		return *m.Doc
	}
	return ""
}

func (m *ApiRDFValueDescriptor) GetKind() ApiRDFValueDescriptor_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ApiRDFValueDescriptor_PRIMITIVE
}

func (m *ApiRDFValueDescriptor) GetDefault() *google_protobuf.Any {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *ApiRDFValueDescriptor) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ApiRDFValueDescriptor) GetFields() []*ApiRDFValueFieldDescriptor {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ApiRDFValueDescriptor) GetUnionFieldName() string {
	if m != nil && m.UnionFieldName != nil {
		return *m.UnionFieldName
	}
	return ""
}

type ApiMethod struct {
	Name                 *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Category             *string                `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Doc                  *string                `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	HttpRoute            *string                `protobuf:"bytes,4,opt,name=http_route,json=httpRoute" json:"http_route,omitempty"`
	HttpMethods          []string               `protobuf:"bytes,5,rep,name=http_methods,json=httpMethods" json:"http_methods,omitempty"`
	ArgsTypeDescriptor   *ApiRDFValueDescriptor `protobuf:"bytes,6,opt,name=args_type_descriptor,json=argsTypeDescriptor" json:"args_type_descriptor,omitempty"`
	ResultKind           *ApiMethod_ResultKind  `protobuf:"varint,7,opt,name=result_kind,json=resultKind,enum=ApiMethod_ResultKind" json:"result_kind,omitempty"`
	ResultTypeDescriptor *ApiRDFValueDescriptor `protobuf:"bytes,8,opt,name=result_type_descriptor,json=resultTypeDescriptor" json:"result_type_descriptor,omitempty"`
	XXX_unrecognized     []byte                 `json:"-"`
}

func (m *ApiMethod) Reset()                    { *m = ApiMethod{} }
func (m *ApiMethod) String() string            { return proto.CompactTextString(m) }
func (*ApiMethod) ProtoMessage()               {}
func (*ApiMethod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiMethod) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiMethod) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *ApiMethod) GetDoc() string {
	if m != nil && m.Doc != nil {
		return *m.Doc
	}
	return ""
}

func (m *ApiMethod) GetHttpRoute() string {
	if m != nil && m.HttpRoute != nil {
		return *m.HttpRoute
	}
	return ""
}

func (m *ApiMethod) GetHttpMethods() []string {
	if m != nil {
		return m.HttpMethods
	}
	return nil
}

func (m *ApiMethod) GetArgsTypeDescriptor() *ApiRDFValueDescriptor {
	if m != nil {
		return m.ArgsTypeDescriptor
	}
	return nil
}

func (m *ApiMethod) GetResultKind() ApiMethod_ResultKind {
	if m != nil && m.ResultKind != nil {
		return *m.ResultKind
	}
	return ApiMethod_NONE
}

func (m *ApiMethod) GetResultTypeDescriptor() *ApiRDFValueDescriptor {
	if m != nil {
		return m.ResultTypeDescriptor
	}
	return nil
}

// Next id: 6
type ApiOutputPluginDescriptor struct {
	PluginType       *ApiOutputPluginDescriptor_PluginType `protobuf:"varint,4,opt,name=plugin_type,json=pluginType,enum=ApiOutputPluginDescriptor_PluginType" json:"plugin_type,omitempty"`
	Name             *string                               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FriendlyName     *string                               `protobuf:"bytes,5,opt,name=friendly_name,json=friendlyName" json:"friendly_name,omitempty"`
	Description      *string                               `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	ArgsType         *string                               `protobuf:"bytes,3,opt,name=args_type,json=argsType" json:"args_type,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *ApiOutputPluginDescriptor) Reset()                    { *m = ApiOutputPluginDescriptor{} }
func (m *ApiOutputPluginDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ApiOutputPluginDescriptor) ProtoMessage()               {}
func (*ApiOutputPluginDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiOutputPluginDescriptor) GetPluginType() ApiOutputPluginDescriptor_PluginType {
	if m != nil && m.PluginType != nil {
		return *m.PluginType
	}
	return ApiOutputPluginDescriptor_LEGACY
}

func (m *ApiOutputPluginDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiOutputPluginDescriptor) GetFriendlyName() string {
	if m != nil && m.FriendlyName != nil {
		return *m.FriendlyName
	}
	return ""
}

func (m *ApiOutputPluginDescriptor) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ApiOutputPluginDescriptor) GetArgsType() string {
	if m != nil && m.ArgsType != nil {
		return *m.ArgsType
	}
	return ""
}

type ApiGetRDFValueDescriptorArgs struct {
	Type             *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetRDFValueDescriptorArgs) Reset()                    { *m = ApiGetRDFValueDescriptorArgs{} }
func (m *ApiGetRDFValueDescriptorArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetRDFValueDescriptorArgs) ProtoMessage()               {}
func (*ApiGetRDFValueDescriptorArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApiGetRDFValueDescriptorArgs) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type ApiListRDFValueDescriptorsResult struct {
	Items            []*ApiRDFValueDescriptor `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ApiListRDFValueDescriptorsResult) Reset()         { *m = ApiListRDFValueDescriptorsResult{} }
func (m *ApiListRDFValueDescriptorsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListRDFValueDescriptorsResult) ProtoMessage()    {}
func (*ApiListRDFValueDescriptorsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func (m *ApiListRDFValueDescriptorsResult) GetItems() []*ApiRDFValueDescriptor {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiAff4AttributeDescriptor struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiAff4AttributeDescriptor) Reset()                    { *m = ApiAff4AttributeDescriptor{} }
func (m *ApiAff4AttributeDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ApiAff4AttributeDescriptor) ProtoMessage()               {}
func (*ApiAff4AttributeDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApiAff4AttributeDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ApiListAff4AttributeDescriptorsResult struct {
	Items            []*ApiAff4AttributeDescriptor `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ApiListAff4AttributeDescriptorsResult) Reset()         { *m = ApiListAff4AttributeDescriptorsResult{} }
func (m *ApiListAff4AttributeDescriptorsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListAff4AttributeDescriptorsResult) ProtoMessage()    {}
func (*ApiListAff4AttributeDescriptorsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8}
}

func (m *ApiListAff4AttributeDescriptorsResult) GetItems() []*ApiAff4AttributeDescriptor {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiListOutputPluginDescriptorsResult struct {
	Items            []*ApiOutputPluginDescriptor `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ApiListOutputPluginDescriptorsResult) Reset()         { *m = ApiListOutputPluginDescriptorsResult{} }
func (m *ApiListOutputPluginDescriptorsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListOutputPluginDescriptorsResult) ProtoMessage()    {}
func (*ApiListOutputPluginDescriptorsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *ApiListOutputPluginDescriptorsResult) GetItems() []*ApiOutputPluginDescriptor {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiListApiMethodsResult struct {
	Items            []*ApiMethod `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ApiListApiMethodsResult) Reset()                    { *m = ApiListApiMethodsResult{} }
func (m *ApiListApiMethodsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListApiMethodsResult) ProtoMessage()               {}
func (*ApiListApiMethodsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApiListApiMethodsResult) GetItems() []*ApiMethod {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiRDFAllowedEnumValueDescriptor)(nil), "ApiRDFAllowedEnumValueDescriptor")
	proto.RegisterType((*ApiRDFValueFieldDescriptor)(nil), "ApiRDFValueFieldDescriptor")
	proto.RegisterType((*ApiRDFValueDescriptor)(nil), "ApiRDFValueDescriptor")
	proto.RegisterType((*ApiMethod)(nil), "ApiMethod")
	proto.RegisterType((*ApiOutputPluginDescriptor)(nil), "ApiOutputPluginDescriptor")
	proto.RegisterType((*ApiGetRDFValueDescriptorArgs)(nil), "ApiGetRDFValueDescriptorArgs")
	proto.RegisterType((*ApiListRDFValueDescriptorsResult)(nil), "ApiListRDFValueDescriptorsResult")
	proto.RegisterType((*ApiAff4AttributeDescriptor)(nil), "ApiAff4AttributeDescriptor")
	proto.RegisterType((*ApiListAff4AttributeDescriptorsResult)(nil), "ApiListAff4AttributeDescriptorsResult")
	proto.RegisterType((*ApiListOutputPluginDescriptorsResult)(nil), "ApiListOutputPluginDescriptorsResult")
	proto.RegisterType((*ApiListApiMethodsResult)(nil), "ApiListApiMethodsResult")
	proto.RegisterEnum("ApiRDFValueDescriptor_Kind", ApiRDFValueDescriptor_Kind_name, ApiRDFValueDescriptor_Kind_value)
	proto.RegisterEnum("ApiMethod_ResultKind", ApiMethod_ResultKind_name, ApiMethod_ResultKind_value)
	proto.RegisterEnum("ApiOutputPluginDescriptor_PluginType", ApiOutputPluginDescriptor_PluginType_name, ApiOutputPluginDescriptor_PluginType_value)
}

func init() { proto.RegisterFile("grr/proto/api/reflection.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x0e, 0x63, 0xf9, 0xa2, 0x91, 0x6d, 0x28, 0x13, 0x3b, 0x51, 0x9c, 0x3f, 0xff, 0x3f, 0xd6,
	0x5f, 0xd7, 0x4a, 0xe2, 0x50, 0x89, 0x93, 0x06, 0x2d, 0xd2, 0xa2, 0xa0, 0x7c, 0x49, 0x84, 0x3a,
	0x76, 0xc0, 0xd8, 0x86, 0xd3, 0x45, 0x84, 0x31, 0x39, 0x12, 0x07, 0xa1, 0x86, 0x2c, 0x67, 0x18,
	0x47, 0x05, 0x8a, 0xae, 0xba, 0xe8, 0xba, 0xe8, 0x03, 0xf4, 0x4d, 0xba, 0xe8, 0x03, 0x14, 0x7d,
	0x84, 0xf6, 0x29, 0x0a, 0x74, 0x51, 0xcc, 0x19, 0x52, 0xa2, 0x1c, 0xbb, 0x37, 0xa0, 0x1b, 0x43,
	0x9e, 0x73, 0xce, 0x77, 0x2e, 0xf3, 0x7d, 0x87, 0x83, 0xfe, 0xdb, 0x4b, 0x92, 0x66, 0x9c, 0x44,
	0x2a, 0x6a, 0xd2, 0x98, 0x37, 0x13, 0xd6, 0x0d, 0x99, 0xa7, 0x78, 0x24, 0x6c, 0x38, 0x5c, 0xba,
	0xd6, 0x8b, 0xa2, 0x5e, 0xc8, 0x8c, 0xcb, 0x71, 0xda, 0x6d, 0x52, 0x31, 0xc8, 0x4c, 0xb5, 0x51,
	0xa8, 0x64, 0x7d, 0x2a, 0x14, 0xf7, 0x8c, 0xa5, 0xfe, 0xab, 0x85, 0x88, 0x13, 0x73, 0x77, 0x73,
	0xdb, 0x09, 0xc3, 0xe8, 0x84, 0xf9, 0x5b, 0x22, 0xed, 0x1f, 0xd2, 0x30, 0x65, 0x9b, 0x4c, 0x7a,
	0x09, 0x8f, 0x55, 0x94, 0xe0, 0x35, 0x54, 0x12, 0xb4, 0xcf, 0x6a, 0x16, 0xb1, 0x1a, 0xe5, 0x56,
	0xed, 0xe7, 0xdf, 0x7e, 0xf9, 0xc1, 0xc2, 0xb8, 0xaa, 0x5d, 0xc9, 0x6b, 0xed, 0x4b, 0xb4, 0xd9,
	0x76, 0xc1, 0x0b, 0x37, 0xd1, 0x24, 0x1c, 0xd6, 0x2e, 0x12, 0xab, 0x31, 0xd1, 0xba, 0x06, 0xee,
	0x97, 0xf1, 0xa5, 0x82, 0x3b, 0xfc, 0xb5, 0x5d, 0xe3, 0x87, 0x9b, 0x68, 0xc2, 0x8f, 0xbc, 0xda,
	0x04, 0xa0, 0xdf, 0x00, 0xf7, 0xab, 0x78, 0x71, 0x33, 0xf2, 0xd2, 0x3e, 0x13, 0x8a, 0xea, 0x16,
	0x89, 0x54, 0x09, 0x17, 0x3d, 0xdb, 0xd5, 0x9e, 0x78, 0x0b, 0x4d, 0x85, 0xf4, 0x98, 0x85, 0xb2,
	0x56, 0x22, 0x13, 0x8d, 0x72, 0xeb, 0x0e, 0xc4, 0xac, 0xe2, 0x95, 0x1d, 0x2e, 0x15, 0x89, 0xba,
	0xc4, 0x58, 0x09, 0x8d, 0xe3, 0x90, 0x33, 0x9f, 0xa8, 0x88, 0xa8, 0x80, 0xcb, 0x3c, 0x6d, 0x16,
	0x5c, 0xff, 0x7e, 0x1a, 0x2d, 0x99, 0xde, 0xa1, 0xe1, 0x6d, 0xce, 0x42, 0xbf, 0xd0, 0xf5, 0xea,
	0x58, 0xd7, 0x97, 0x21, 0xc7, 0x1c, 0xae, 0x80, 0xdb, 0x58, 0xc3, 0x1f, 0xa3, 0x92, 0x1a, 0xc4,
	0xa6, 0xdf, 0x72, 0xeb, 0x36, 0x38, 0xae, 0xe0, 0xff, 0x1b, 0x47, 0x6d, 0x21, 0x0d, 0x2a, 0x48,
	0x9e, 0xc6, 0x9c, 0xe8, 0xc0, 0x9b, 0xb6, 0x0b, 0x81, 0xf8, 0x16, 0x9a, 0xe4, 0xc2, 0x67, 0x6f,
	0x60, 0x04, 0x73, 0xad, 0x05, 0x40, 0x98, 0xc7, 0xb3, 0x06, 0x01, 0x4c, 0xb6, 0x6b, 0x5c, 0xf0,
	0x26, 0x9a, 0x49, 0x58, 0xcc, 0xa8, 0x62, 0x7e, 0xad, 0x44, 0xac, 0xc6, 0x4c, 0xab, 0x01, 0xee,
	0x75, 0x4c, 0xda, 0x5d, 0xa2, 0x02, 0x46, 0xba, 0x26, 0x4a, 0x92, 0xdc, 0x8f, 0x44, 0x09, 0x11,
	0x91, 0xb2, 0xdd, 0x61, 0x24, 0x3e, 0x44, 0xd3, 0xfe, 0x40, 0xd0, 0x3e, 0xf7, 0x6a, 0x93, 0x00,
	0xf2, 0x21, 0x80, 0x3c, 0xc4, 0x0f, 0xc6, 0x40, 0x02, 0x2a, 0x09, 0x25, 0x99, 0x27, 0x0d, 0xc3,
	0x01, 0xf1, 0x02, 0x2a, 0x7a, 0x5c, 0xf4, 0x4c, 0x17, 0x39, 0x70, 0x0e, 0x96, 0x5f, 0xe5, 0xd4,
	0x5f, 0xbe, 0xca, 0x97, 0x68, 0xae, 0x9b, 0x70, 0x26, 0xfc, 0x70, 0xd0, 0x81, 0x69, 0x4f, 0x43,
	0xe8, 0x07, 0x10, 0x7a, 0x1f, 0xdf, 0xdb, 0xce, 0x8c, 0x30, 0x30, 0x7d, 0xb5, 0xa3, 0xe2, 0x54,
	0x44, 0x8e, 0x19, 0x91, 0x41, 0x74, 0x22, 0x08, 0x17, 0x60, 0x38, 0x68, 0xdb, 0xee, 0x6c, 0x8e,
	0xb7, 0xab, 0xef, 0xe6, 0x05, 0xaa, 0x7a, 0x91, 0x50, 0xec, 0x8d, 0xea, 0x04, 0x2c, 0x8c, 0x3b,
	0x69, 0x12, 0xd6, 0x66, 0x20, 0x45, 0x13, 0x52, 0xdc, 0xc4, 0xab, 0x1b, 0xc6, 0x4e, 0xb4, 0x9d,
	0x1c, 0xb8, 0x3b, 0xe7, 0x01, 0xcf, 0x67, 0x40, 0x4f, 0x58, 0x18, 0x1f, 0x24, 0x21, 0x0e, 0xd0,
	0xb4, 0xcf, 0xba, 0x34, 0x0d, 0x55, 0xad, 0x4c, 0xac, 0x46, 0x65, 0x7d, 0xc1, 0x36, 0x0a, 0xb4,
	0x73, 0x05, 0xda, 0x8e, 0x18, 0xb4, 0xde, 0x87, 0x3c, 0xeb, 0x78, 0xc9, 0x65, 0x5e, 0xd4, 0xef,
	0x33, 0xe1, 0x33, 0x9f, 0x64, 0x81, 0x19, 0x23, 0x6f, 0x2d, 0x3c, 0x66, 0x6a, 0xd3, 0x1c, 0x01,
	0x47, 0x36, 0x42, 0x2a, 0xa5, 0x9b, 0xc3, 0x17, 0xf8, 0x8e, 0xfe, 0x16, 0xdf, 0x61, 0x4e, 0x43,
	0xbe, 0xe3, 0x1f, 0x2d, 0x34, 0x4f, 0x8d, 0xca, 0x3b, 0x90, 0x58, 0xd6, 0x2a, 0x64, 0xa2, 0x51,
	0x59, 0x5f, 0xb6, 0xff, 0x6c, 0x05, 0xb4, 0xbe, 0xb2, 0x20, 0xe7, 0x97, 0xf8, 0x8b, 0xcc, 0x89,
	0xb0, 0xa1, 0x9c, 0xa5, 0x4d, 0x1c, 0x9d, 0xd9, 0xa3, 0xc7, 0x21, 0x23, 0x91, 0x08, 0x07, 0xba,
	0x02, 0xb0, 0x43, 0x05, 0xd2, 0x36, 0xd4, 0xe4, 0x92, 0x84, 0xba, 0x60, 0x2e, 0x35, 0x6b, 0x08,
	0xeb, 0xc7, 0x6a, 0xb0, 0xa6, 0xc7, 0x2b, 0x8c, 0xd1, 0x1f, 0xa6, 0xcb, 0x7e, 0x1e, 0x33, 0x49,
	0xa8, 0x28, 0x20, 0xd9, 0xee, 0x5c, 0xd6, 0x00, 0xd4, 0x27, 0xeb, 0x5f, 0x4f, 0xa1, 0xc5, 0x82,
	0x84, 0x0b, 0xea, 0x7d, 0x77, 0x4c, 0xbd, 0x18, 0xaa, 0x9f, 0xc5, 0x68, 0x3f, 0x17, 0x5f, 0x2e,
	0xde, 0x96, 0x61, 0xac, 0xd1, 0xee, 0x5d, 0x70, 0xbb, 0x85, 0x1b, 0x4f, 0xd2, 0x3e, 0x15, 0x77,
	0x12, 0x46, 0x7d, 0xe8, 0x29, 0xaf, 0x4c, 0xd3, 0x37, 0xca, 0x5a, 0xd1, 0x02, 0xc8, 0x48, 0xfc,
	0x39, 0x2a, 0xbd, 0xe2, 0xc2, 0x07, 0xf9, 0xce, 0xaf, 0x5f, 0xb7, 0xcf, 0xac, 0xc8, 0xfe, 0x84,
	0x0b, 0xbf, 0xd5, 0x86, 0x0c, 0x1b, 0xd8, 0x69, 0x0b, 0x9f, 0x7b, 0x54, 0x31, 0x49, 0x4e, 0x02,
	0xa6, 0x02, 0x96, 0x00, 0xcf, 0xcc, 0x7a, 0xe4, 0x5a, 0x75, 0x71, 0xc2, 0xfb, 0x5c, 0xf1, 0xd7,
	0xd9, 0xe1, 0x9a, 0x16, 0x1b, 0xd5, 0xe2, 0x49, 0x3d, 0x95, 0x26, 0xba, 0x7e, 0x9d, 0xb3, 0xc8,
	0xc2, 0xd2, 0xbf, 0xcb, 0x42, 0x07, 0x4d, 0xc7, 0x34, 0x61, 0x42, 0xc9, 0xda, 0x24, 0xd0, 0x70,
	0x15, 0x30, 0x97, 0xf1, 0xff, 0xda, 0x22, 0x60, 0x09, 0x57, 0x54, 0x78, 0x4c, 0x2f, 0x08, 0x7e,
	0x7a, 0x48, 0x79, 0x1c, 0xfe, 0xc6, 0x42, 0x53, 0x86, 0x12, 0xb5, 0x29, 0x60, 0xde, 0xd8, 0xac,
	0x4e, 0x2d, 0xe0, 0xd6, 0x4b, 0xc0, 0x3f, 0xc2, 0x87, 0xa3, 0x33, 0xa9, 0x91, 0x69, 0x18, 0x8e,
	0xd6, 0x80, 0x1c, 0xcf, 0x45, 0xf6, 0x34, 0xfd, 0xe8, 0x88, 0x8e, 0x5a, 0x0b, 0x83, 0x58, 0x8f,
	0x99, 0xab, 0x80, 0xe8, 0x91, 0x7d, 0xf4, 0x7c, 0xdf, 0x3d, 0xd8, 0xd8, 0xb7, 0xdd, 0xac, 0x14,
	0xfc, 0x9d, 0x85, 0xaa, 0xa9, 0xe0, 0x91, 0xe8, 0xc0, 0x41, 0x71, 0x0f, 0x9d, 0x40, 0x09, 0x9f,
	0xe1, 0x28, 0x27, 0xf0, 0x70, 0xfe, 0xe6, 0x92, 0x20, 0x6c, 0x8d, 0x14, 0xa2, 0x09, 0xf7, 0x99,
	0x50, 0xbc, 0xcb, 0x99, 0x2c, 0xee, 0xaa, 0x80, 0x2a, 0xe2, 0x33, 0xc5, 0x92, 0x3e, 0x17, 0x70,
	0xe7, 0xdc, 0x0b, 0x48, 0x4c, 0x13, 0x95, 0xef, 0x34, 0x80, 0xd0, 0xa0, 0xa9, 0x64, 0xbe, 0xed,
	0xce, 0xc3, 0xff, 0x30, 0x11, 0xbd, 0xc7, 0xea, 0xcb, 0xa8, 0xa4, 0xf9, 0x83, 0xe7, 0x50, 0xf9,
	0x99, 0xdb, 0x7e, 0xda, 0xde, 0x6f, 0x1f, 0x6e, 0x55, 0x2f, 0x60, 0x84, 0xa6, 0x4c, 0x37, 0x55,
	0xab, 0xfe, 0xed, 0x04, 0x2a, 0x3b, 0x31, 0x7f, 0xca, 0x54, 0x10, 0xf9, 0x18, 0x17, 0xf9, 0x9f,
	0x71, 0x7d, 0x09, 0xcd, 0x68, 0xca, 0xf5, 0xa2, 0x64, 0x60, 0x08, 0xef, 0x0e, 0xff, 0xc7, 0xd5,
	0xc2, 0x47, 0xd8, 0xb0, 0xfa, 0x06, 0x42, 0x81, 0x52, 0x71, 0x27, 0x89, 0x52, 0xc5, 0x80, 0x5c,
	0x65, 0xb7, 0xac, 0x4f, 0x5c, 0x7d, 0x80, 0x97, 0xd1, 0x2c, 0x98, 0xfb, 0x90, 0x2f, 0xe3, 0x84,
	0x5b, 0xd1, 0x67, 0xa6, 0x04, 0x89, 0x9f, 0xa0, 0x05, 0x9a, 0xf4, 0x64, 0x47, 0x5f, 0x40, 0x67,
	0xa4, 0x6e, 0xf8, 0x3c, 0x54, 0xd6, 0xaf, 0x9c, 0xad, 0x13, 0x17, 0xeb, 0x18, 0xad, 0xd3, 0x82,
	0x9a, 0x1f, 0xa2, 0x4a, 0xc2, 0x64, 0x1a, 0xaa, 0x0e, 0x08, 0x6d, 0x1a, 0x84, 0xb6, 0x68, 0x0f,
	0xdb, 0xb5, 0x5d, 0xb0, 0xea, 0x11, 0xb9, 0x28, 0x19, 0xfe, 0xc6, 0x3b, 0xe8, 0x4a, 0x16, 0x77,
	0xba, 0x86, 0x99, 0x3f, 0xac, 0x61, 0xc1, 0x44, 0x8d, 0x57, 0x51, 0x7f, 0x80, 0xd0, 0x28, 0x0f,
	0x9e, 0x41, 0xa5, 0xdd, 0xbd, 0x5d, 0x7d, 0x0b, 0x65, 0x34, 0x79, 0xe8, 0xec, 0x1c, 0x6c, 0x55,
	0x2d, 0x7c, 0x09, 0xcd, 0xb5, 0xda, 0xbb, 0x8e, 0xfb, 0xa2, 0xf3, 0x7c, 0xdf, 0xdd, 0x72, 0x9e,
	0x56, 0x2f, 0xd6, 0x7f, 0x9a, 0x40, 0xd7, 0x9c, 0x98, 0xef, 0xa5, 0x2a, 0x4e, 0xd5, 0xb3, 0x30,
	0xed, 0x71, 0x51, 0xe8, 0x6c, 0x1b, 0x55, 0x62, 0x38, 0x83, 0x0a, 0x61, 0xcc, 0xf3, 0xeb, 0x2b,
	0xf6, 0xb9, 0x01, 0xb6, 0x39, 0xd0, 0x95, 0xb9, 0x28, 0x1e, 0xfe, 0xc6, 0xf7, 0xc6, 0xf6, 0xdd,
	0xf0, 0xd3, 0x6b, 0x40, 0x88, 0x71, 0x5c, 0x95, 0x63, 0xab, 0xef, 0xe8, 0xf4, 0xb7, 0x77, 0x12,
	0x62, 0xef, 0x43, 0xec, 0x1d, 0x7c, 0x1b, 0x96, 0x20, 0x19, 0x2e, 0xc1, 0xe8, 0x14, 0x54, 0x61,
	0x29, 0x9e, 0xfe, 0xea, 0x1e, 0xa0, 0x4a, 0xc1, 0x9a, 0x2d, 0xd7, 0x7f, 0x84, 0x5b, 0xc4, 0xc1,
	0x47, 0xa8, 0x3c, 0xe4, 0x53, 0xf6, 0x5c, 0x7c, 0x04, 0xa0, 0xef, 0xe1, 0xfb, 0xee, 0xe6, 0x76,
	0xf6, 0x26, 0x31, 0x7a, 0xa2, 0x49, 0x0f, 0xde, 0x1c, 0xd2, 0x68, 0x6f, 0x2c, 0x09, 0x51, 0xf4,
	0x15, 0x93, 0xb6, 0x3b, 0x93, 0x33, 0xad, 0xde, 0x44, 0x68, 0x34, 0x57, 0xad, 0xaa, 0x9d, 0xad,
	0xc7, 0xce, 0xc6, 0x8b, 0xea, 0x05, 0x5c, 0x41, 0xd3, 0xed, 0xdd, 0xe7, 0xfb, 0xce, 0xee, 0x7e,
	0xd5, 0xd2, 0x57, 0xbe, 0xa3, 0x85, 0x77, 0xb1, 0xbe, 0x87, 0xfe, 0xe3, 0xc4, 0xfc, 0x31, 0x53,
	0x6f, 0x93, 0xc7, 0x49, 0x7a, 0x12, 0x37, 0xb3, 0x37, 0xa1, 0xb9, 0x8e, 0xeb, 0x50, 0xe5, 0x22,
	0xbe, 0xfc, 0xf6, 0x23, 0x30, 0x7b, 0x03, 0xd6, 0x9f, 0xc1, 0x3b, 0x5c, 0x7f, 0xd0, 0xdf, 0x46,
	0x94, 0x86, 0x75, 0x78, 0x0d, 0x4d, 0x72, 0xc5, 0xfa, 0xb2, 0x66, 0xc1, 0xf2, 0x3c, 0x8f, 0xbc,
	0xc6, 0xa9, 0x7e, 0x17, 0x5e, 0xb7, 0x4e, 0xb7, 0xfb, 0xc0, 0x51, 0x2a, 0xe1, 0xc7, 0xa9, 0x2a,
	0x2a, 0xea, 0x8c, 0xfd, 0x50, 0xff, 0x14, 0xad, 0x64, 0x35, 0x9c, 0x13, 0x95, 0x17, 0x72, 0x6f,
	0xbc, 0x10, 0xd8, 0xe2, 0xe7, 0x84, 0xe4, 0xd5, 0x1c, 0xa1, 0x77, 0x32, 0xec, 0xb3, 0x79, 0x9d,
	0x43, 0xdf, 0x1d, 0x87, 0x5e, 0x3a, 0x5f, 0x09, 0x39, 0xf2, 0x23, 0x74, 0x35, 0xaf, 0x3a, 0x5f,
	0x07, 0x39, 0x18, 0x19, 0x07, 0x43, 0xa3, 0x85, 0x91, 0x05, 0xff, 0x1e, 0x00, 0x00, 0xff, 0xff,
	0x09, 0xad, 0x71, 0xa6, 0x55, 0x0d, 0x00, 0x00,
}
