// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/stats.proto

/*
Package stats is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/stats.proto

It has these top-level messages:
	ApiStatsStoreMetricDataPoint
	ApiStatsStoreMetric
	ApiReportDescriptor
	ApiReport
	ApiReportData
	ApiStackChartReportData
	ApiPieChartReportData
	ApiLineChartReportData
	ApiAuditChartReportData
	ApiReportDataPoint1D
	ApiReportDataSeries2D
	ApiReportDataPoint2D
	ApiReportTickSpecifier
	ApiListStatsStoreMetricsMetadataArgs
	ApiListStatsStoreMetricsMetadataResult
	ApiGetStatsStoreMetricArgs
	ApiGetReportArgs
	ApiListReportsResult
*/
package stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import jobs "github.com/google/grr_go_api_client/grrproto/grr/proto/jobs_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/knowledge_base_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/sysinfo_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiReportDescriptor_ReportType int32

const (
	ApiReportDescriptor_CLIENT     ApiReportDescriptor_ReportType = 0
	ApiReportDescriptor_FILE_STORE ApiReportDescriptor_ReportType = 1
	ApiReportDescriptor_SERVER     ApiReportDescriptor_ReportType = 2
)

var ApiReportDescriptor_ReportType_name = map[int32]string{
	0: "CLIENT",
	1: "FILE_STORE",
	2: "SERVER",
}
var ApiReportDescriptor_ReportType_value = map[string]int32{
	"CLIENT":     0,
	"FILE_STORE": 1,
	"SERVER":     2,
}

func (x ApiReportDescriptor_ReportType) Enum() *ApiReportDescriptor_ReportType {
	p := new(ApiReportDescriptor_ReportType)
	*p = x
	return p
}
func (x ApiReportDescriptor_ReportType) String() string {
	return proto.EnumName(ApiReportDescriptor_ReportType_name, int32(x))
}
func (x *ApiReportDescriptor_ReportType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiReportDescriptor_ReportType_value, data, "ApiReportDescriptor_ReportType")
	if err != nil {
		return err
	}
	*x = ApiReportDescriptor_ReportType(value)
	return nil
}
func (ApiReportDescriptor_ReportType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type ApiReportData_RepresentationType int32

const (
	ApiReportData_STACK_CHART ApiReportData_RepresentationType = 0
	ApiReportData_PIE_CHART   ApiReportData_RepresentationType = 1
	ApiReportData_LINE_CHART  ApiReportData_RepresentationType = 2
	ApiReportData_AUDIT_CHART ApiReportData_RepresentationType = 3
)

var ApiReportData_RepresentationType_name = map[int32]string{
	0: "STACK_CHART",
	1: "PIE_CHART",
	2: "LINE_CHART",
	3: "AUDIT_CHART",
}
var ApiReportData_RepresentationType_value = map[string]int32{
	"STACK_CHART": 0,
	"PIE_CHART":   1,
	"LINE_CHART":  2,
	"AUDIT_CHART": 3,
}

func (x ApiReportData_RepresentationType) Enum() *ApiReportData_RepresentationType {
	p := new(ApiReportData_RepresentationType)
	*p = x
	return p
}
func (x ApiReportData_RepresentationType) String() string {
	return proto.EnumName(ApiReportData_RepresentationType_name, int32(x))
}
func (x *ApiReportData_RepresentationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiReportData_RepresentationType_value, data, "ApiReportData_RepresentationType")
	if err != nil {
		return err
	}
	*x = ApiReportData_RepresentationType(value)
	return nil
}
func (ApiReportData_RepresentationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type ApiListStatsStoreMetricsMetadataArgs_Component int32

const (
	ApiListStatsStoreMetricsMetadataArgs_WORKER   ApiListStatsStoreMetricsMetadataArgs_Component = 0
	ApiListStatsStoreMetricsMetadataArgs_FRONTEND ApiListStatsStoreMetricsMetadataArgs_Component = 1
	ApiListStatsStoreMetricsMetadataArgs_ADMIN_UI ApiListStatsStoreMetricsMetadataArgs_Component = 2
)

var ApiListStatsStoreMetricsMetadataArgs_Component_name = map[int32]string{
	0: "WORKER",
	1: "FRONTEND",
	2: "ADMIN_UI",
}
var ApiListStatsStoreMetricsMetadataArgs_Component_value = map[string]int32{
	"WORKER":   0,
	"FRONTEND": 1,
	"ADMIN_UI": 2,
}

func (x ApiListStatsStoreMetricsMetadataArgs_Component) Enum() *ApiListStatsStoreMetricsMetadataArgs_Component {
	p := new(ApiListStatsStoreMetricsMetadataArgs_Component)
	*p = x
	return p
}
func (x ApiListStatsStoreMetricsMetadataArgs_Component) String() string {
	return proto.EnumName(ApiListStatsStoreMetricsMetadataArgs_Component_name, int32(x))
}
func (x *ApiListStatsStoreMetricsMetadataArgs_Component) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiListStatsStoreMetricsMetadataArgs_Component_value, data, "ApiListStatsStoreMetricsMetadataArgs_Component")
	if err != nil {
		return err
	}
	*x = ApiListStatsStoreMetricsMetadataArgs_Component(value)
	return nil
}
func (ApiListStatsStoreMetricsMetadataArgs_Component) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

type ApiGetStatsStoreMetricArgs_Component int32

const (
	ApiGetStatsStoreMetricArgs_WORKER   ApiGetStatsStoreMetricArgs_Component = 0
	ApiGetStatsStoreMetricArgs_FRONTEND ApiGetStatsStoreMetricArgs_Component = 1
	ApiGetStatsStoreMetricArgs_ADMIN_UI ApiGetStatsStoreMetricArgs_Component = 2
)

var ApiGetStatsStoreMetricArgs_Component_name = map[int32]string{
	0: "WORKER",
	1: "FRONTEND",
	2: "ADMIN_UI",
}
var ApiGetStatsStoreMetricArgs_Component_value = map[string]int32{
	"WORKER":   0,
	"FRONTEND": 1,
	"ADMIN_UI": 2,
}

func (x ApiGetStatsStoreMetricArgs_Component) Enum() *ApiGetStatsStoreMetricArgs_Component {
	p := new(ApiGetStatsStoreMetricArgs_Component)
	*p = x
	return p
}
func (x ApiGetStatsStoreMetricArgs_Component) String() string {
	return proto.EnumName(ApiGetStatsStoreMetricArgs_Component_name, int32(x))
}
func (x *ApiGetStatsStoreMetricArgs_Component) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetStatsStoreMetricArgs_Component_value, data, "ApiGetStatsStoreMetricArgs_Component")
	if err != nil {
		return err
	}
	*x = ApiGetStatsStoreMetricArgs_Component(value)
	return nil
}
func (ApiGetStatsStoreMetricArgs_Component) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

type ApiGetStatsStoreMetricArgs_DistributionHandlingMode int32

const (
	ApiGetStatsStoreMetricArgs_DH_SUM   ApiGetStatsStoreMetricArgs_DistributionHandlingMode = 0
	ApiGetStatsStoreMetricArgs_DH_COUNT ApiGetStatsStoreMetricArgs_DistributionHandlingMode = 1
)

var ApiGetStatsStoreMetricArgs_DistributionHandlingMode_name = map[int32]string{
	0: "DH_SUM",
	1: "DH_COUNT",
}
var ApiGetStatsStoreMetricArgs_DistributionHandlingMode_value = map[string]int32{
	"DH_SUM":   0,
	"DH_COUNT": 1,
}

func (x ApiGetStatsStoreMetricArgs_DistributionHandlingMode) Enum() *ApiGetStatsStoreMetricArgs_DistributionHandlingMode {
	p := new(ApiGetStatsStoreMetricArgs_DistributionHandlingMode)
	*p = x
	return p
}
func (x ApiGetStatsStoreMetricArgs_DistributionHandlingMode) String() string {
	return proto.EnumName(ApiGetStatsStoreMetricArgs_DistributionHandlingMode_name, int32(x))
}
func (x *ApiGetStatsStoreMetricArgs_DistributionHandlingMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetStatsStoreMetricArgs_DistributionHandlingMode_value, data, "ApiGetStatsStoreMetricArgs_DistributionHandlingMode")
	if err != nil {
		return err
	}
	*x = ApiGetStatsStoreMetricArgs_DistributionHandlingMode(value)
	return nil
}
func (ApiGetStatsStoreMetricArgs_DistributionHandlingMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 1}
}

type ApiGetStatsStoreMetricArgs_AggregationMode int32

const (
	ApiGetStatsStoreMetricArgs_AGG_SUM  ApiGetStatsStoreMetricArgs_AggregationMode = 0
	ApiGetStatsStoreMetricArgs_AGG_MEAN ApiGetStatsStoreMetricArgs_AggregationMode = 1
	ApiGetStatsStoreMetricArgs_AGG_NONE ApiGetStatsStoreMetricArgs_AggregationMode = 2
)

var ApiGetStatsStoreMetricArgs_AggregationMode_name = map[int32]string{
	0: "AGG_SUM",
	1: "AGG_MEAN",
	2: "AGG_NONE",
}
var ApiGetStatsStoreMetricArgs_AggregationMode_value = map[string]int32{
	"AGG_SUM":  0,
	"AGG_MEAN": 1,
	"AGG_NONE": 2,
}

func (x ApiGetStatsStoreMetricArgs_AggregationMode) Enum() *ApiGetStatsStoreMetricArgs_AggregationMode {
	p := new(ApiGetStatsStoreMetricArgs_AggregationMode)
	*p = x
	return p
}
func (x ApiGetStatsStoreMetricArgs_AggregationMode) String() string {
	return proto.EnumName(ApiGetStatsStoreMetricArgs_AggregationMode_name, int32(x))
}
func (x *ApiGetStatsStoreMetricArgs_AggregationMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetStatsStoreMetricArgs_AggregationMode_value, data, "ApiGetStatsStoreMetricArgs_AggregationMode")
	if err != nil {
		return err
	}
	*x = ApiGetStatsStoreMetricArgs_AggregationMode(value)
	return nil
}
func (ApiGetStatsStoreMetricArgs_AggregationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 2}
}

type ApiStatsStoreMetricDataPoint struct {
	Timestamp        *uint64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value            *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiStatsStoreMetricDataPoint) Reset()                    { *m = ApiStatsStoreMetricDataPoint{} }
func (m *ApiStatsStoreMetricDataPoint) String() string            { return proto.CompactTextString(m) }
func (*ApiStatsStoreMetricDataPoint) ProtoMessage()               {}
func (*ApiStatsStoreMetricDataPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiStatsStoreMetricDataPoint) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApiStatsStoreMetricDataPoint) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ApiStatsStoreMetric struct {
	MetricName       *string                         `protobuf:"bytes,1,opt,name=metric_name,json=metricName" json:"metric_name,omitempty"`
	Start            *uint64                         `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End              *uint64                         `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	DataPoints       []*ApiStatsStoreMetricDataPoint `protobuf:"bytes,4,rep,name=data_points,json=dataPoints" json:"data_points,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ApiStatsStoreMetric) Reset()                    { *m = ApiStatsStoreMetric{} }
func (m *ApiStatsStoreMetric) String() string            { return proto.CompactTextString(m) }
func (*ApiStatsStoreMetric) ProtoMessage()               {}
func (*ApiStatsStoreMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiStatsStoreMetric) GetMetricName() string {
	if m != nil && m.MetricName != nil {
		return *m.MetricName
	}
	return ""
}

func (m *ApiStatsStoreMetric) GetStart() uint64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *ApiStatsStoreMetric) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func (m *ApiStatsStoreMetric) GetDataPoints() []*ApiStatsStoreMetricDataPoint {
	if m != nil {
		return m.DataPoints
	}
	return nil
}

type ApiReportDescriptor struct {
	Type              *ApiReportDescriptor_ReportType `protobuf:"varint,1,opt,name=type,enum=ApiReportDescriptor_ReportType" json:"type,omitempty"`
	Name              *string                         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Title             *string                         `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Summary           *string                         `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	RequiresTimeRange *bool                           `protobuf:"varint,5,opt,name=requires_time_range,json=requiresTimeRange" json:"requires_time_range,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *ApiReportDescriptor) Reset()                    { *m = ApiReportDescriptor{} }
func (m *ApiReportDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ApiReportDescriptor) ProtoMessage()               {}
func (*ApiReportDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiReportDescriptor) GetType() ApiReportDescriptor_ReportType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ApiReportDescriptor_CLIENT
}

func (m *ApiReportDescriptor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiReportDescriptor) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ApiReportDescriptor) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

func (m *ApiReportDescriptor) GetRequiresTimeRange() bool {
	if m != nil && m.RequiresTimeRange != nil {
		return *m.RequiresTimeRange
	}
	return false
}

type ApiReport struct {
	Desc             *ApiReportDescriptor `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
	Data             *ApiReportData       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApiReport) Reset()                    { *m = ApiReport{} }
func (m *ApiReport) String() string            { return proto.CompactTextString(m) }
func (*ApiReport) ProtoMessage()               {}
func (*ApiReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiReport) GetDesc() *ApiReportDescriptor {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *ApiReport) GetData() *ApiReportData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiReportData struct {
	RepresentationType *ApiReportData_RepresentationType `protobuf:"varint,1,opt,name=representation_type,json=representationType,enum=ApiReportData_RepresentationType" json:"representation_type,omitempty"`
	StackChart         *ApiStackChartReportData          `protobuf:"bytes,2,opt,name=stack_chart,json=stackChart" json:"stack_chart,omitempty"`
	PieChart           *ApiPieChartReportData            `protobuf:"bytes,3,opt,name=pie_chart,json=pieChart" json:"pie_chart,omitempty"`
	LineChart          *ApiLineChartReportData           `protobuf:"bytes,4,opt,name=line_chart,json=lineChart" json:"line_chart,omitempty"`
	AuditChart         *ApiAuditChartReportData          `protobuf:"bytes,5,opt,name=audit_chart,json=auditChart" json:"audit_chart,omitempty"`
	XXX_unrecognized   []byte                            `json:"-"`
}

func (m *ApiReportData) Reset()                    { *m = ApiReportData{} }
func (m *ApiReportData) String() string            { return proto.CompactTextString(m) }
func (*ApiReportData) ProtoMessage()               {}
func (*ApiReportData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiReportData) GetRepresentationType() ApiReportData_RepresentationType {
	if m != nil && m.RepresentationType != nil {
		return *m.RepresentationType
	}
	return ApiReportData_STACK_CHART
}

func (m *ApiReportData) GetStackChart() *ApiStackChartReportData {
	if m != nil {
		return m.StackChart
	}
	return nil
}

func (m *ApiReportData) GetPieChart() *ApiPieChartReportData {
	if m != nil {
		return m.PieChart
	}
	return nil
}

func (m *ApiReportData) GetLineChart() *ApiLineChartReportData {
	if m != nil {
		return m.LineChart
	}
	return nil
}

func (m *ApiReportData) GetAuditChart() *ApiAuditChartReportData {
	if m != nil {
		return m.AuditChart
	}
	return nil
}

type ApiStackChartReportData struct {
	Data             []*ApiReportDataSeries2D  `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XTicks           []*ApiReportTickSpecifier `protobuf:"bytes,2,rep,name=x_ticks,json=xTicks" json:"x_ticks,omitempty"`
	YTicks           []*ApiReportTickSpecifier `protobuf:"bytes,3,rep,name=y_ticks,json=yTicks" json:"y_ticks,omitempty"`
	BarWidth         *float32                  `protobuf:"fixed32,4,opt,name=bar_width,json=barWidth" json:"bar_width,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ApiStackChartReportData) Reset()                    { *m = ApiStackChartReportData{} }
func (m *ApiStackChartReportData) String() string            { return proto.CompactTextString(m) }
func (*ApiStackChartReportData) ProtoMessage()               {}
func (*ApiStackChartReportData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApiStackChartReportData) GetData() []*ApiReportDataSeries2D {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ApiStackChartReportData) GetXTicks() []*ApiReportTickSpecifier {
	if m != nil {
		return m.XTicks
	}
	return nil
}

func (m *ApiStackChartReportData) GetYTicks() []*ApiReportTickSpecifier {
	if m != nil {
		return m.YTicks
	}
	return nil
}

func (m *ApiStackChartReportData) GetBarWidth() float32 {
	if m != nil && m.BarWidth != nil {
		return *m.BarWidth
	}
	return 0
}

type ApiPieChartReportData struct {
	Data             []*ApiReportDataPoint1D `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ApiPieChartReportData) Reset()                    { *m = ApiPieChartReportData{} }
func (m *ApiPieChartReportData) String() string            { return proto.CompactTextString(m) }
func (*ApiPieChartReportData) ProtoMessage()               {}
func (*ApiPieChartReportData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ApiPieChartReportData) GetData() []*ApiReportDataPoint1D {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiLineChartReportData struct {
	Data             []*ApiReportDataSeries2D `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ApiLineChartReportData) Reset()                    { *m = ApiLineChartReportData{} }
func (m *ApiLineChartReportData) String() string            { return proto.CompactTextString(m) }
func (*ApiLineChartReportData) ProtoMessage()               {}
func (*ApiLineChartReportData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApiLineChartReportData) GetData() []*ApiReportDataSeries2D {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiAuditChartReportData struct {
	UsedFields       []string           `protobuf:"bytes,1,rep,name=used_fields,json=usedFields" json:"used_fields,omitempty"`
	Rows             []*jobs.AuditEvent `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiAuditChartReportData) Reset()                    { *m = ApiAuditChartReportData{} }
func (m *ApiAuditChartReportData) String() string            { return proto.CompactTextString(m) }
func (*ApiAuditChartReportData) ProtoMessage()               {}
func (*ApiAuditChartReportData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApiAuditChartReportData) GetUsedFields() []string {
	if m != nil {
		return m.UsedFields
	}
	return nil
}

func (m *ApiAuditChartReportData) GetRows() []*jobs.AuditEvent {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ApiReportDataPoint1D struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Label            *string  `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiReportDataPoint1D) Reset()                    { *m = ApiReportDataPoint1D{} }
func (m *ApiReportDataPoint1D) String() string            { return proto.CompactTextString(m) }
func (*ApiReportDataPoint1D) ProtoMessage()               {}
func (*ApiReportDataPoint1D) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiReportDataPoint1D) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ApiReportDataPoint1D) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type ApiReportDataSeries2D struct {
	Label            *string                 `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Points           []*ApiReportDataPoint2D `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ApiReportDataSeries2D) Reset()                    { *m = ApiReportDataSeries2D{} }
func (m *ApiReportDataSeries2D) String() string            { return proto.CompactTextString(m) }
func (*ApiReportDataSeries2D) ProtoMessage()               {}
func (*ApiReportDataSeries2D) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApiReportDataSeries2D) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *ApiReportDataSeries2D) GetPoints() []*ApiReportDataPoint2D {
	if m != nil {
		return m.Points
	}
	return nil
}

type ApiReportDataPoint2D struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiReportDataPoint2D) Reset()                    { *m = ApiReportDataPoint2D{} }
func (m *ApiReportDataPoint2D) String() string            { return proto.CompactTextString(m) }
func (*ApiReportDataPoint2D) ProtoMessage()               {}
func (*ApiReportDataPoint2D) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiReportDataPoint2D) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ApiReportDataPoint2D) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type ApiReportTickSpecifier struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Label            *string  `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiReportTickSpecifier) Reset()                    { *m = ApiReportTickSpecifier{} }
func (m *ApiReportTickSpecifier) String() string            { return proto.CompactTextString(m) }
func (*ApiReportTickSpecifier) ProtoMessage()               {}
func (*ApiReportTickSpecifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ApiReportTickSpecifier) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ApiReportTickSpecifier) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type ApiListStatsStoreMetricsMetadataArgs struct {
	Component        *ApiListStatsStoreMetricsMetadataArgs_Component `protobuf:"varint,1,opt,name=component,enum=ApiListStatsStoreMetricsMetadataArgs_Component" json:"component,omitempty"`
	XXX_unrecognized []byte                                          `json:"-"`
}

func (m *ApiListStatsStoreMetricsMetadataArgs) Reset()         { *m = ApiListStatsStoreMetricsMetadataArgs{} }
func (m *ApiListStatsStoreMetricsMetadataArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListStatsStoreMetricsMetadataArgs) ProtoMessage()    {}
func (*ApiListStatsStoreMetricsMetadataArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13}
}

func (m *ApiListStatsStoreMetricsMetadataArgs) GetComponent() ApiListStatsStoreMetricsMetadataArgs_Component {
	if m != nil && m.Component != nil {
		return *m.Component
	}
	return ApiListStatsStoreMetricsMetadataArgs_WORKER
}

type ApiListStatsStoreMetricsMetadataResult struct {
	Items            []*jobs.MetricMetadata `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ApiListStatsStoreMetricsMetadataResult) Reset() {
	*m = ApiListStatsStoreMetricsMetadataResult{}
}
func (m *ApiListStatsStoreMetricsMetadataResult) String() string { return proto.CompactTextString(m) }
func (*ApiListStatsStoreMetricsMetadataResult) ProtoMessage()    {}
func (*ApiListStatsStoreMetricsMetadataResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14}
}

func (m *ApiListStatsStoreMetricsMetadataResult) GetItems() []*jobs.MetricMetadata {
	if m != nil {
		return m.Items
	}
	return nil
}

// Next field number: 8
type ApiGetStatsStoreMetricArgs struct {
	Component                *ApiGetStatsStoreMetricArgs_Component                `protobuf:"varint,1,opt,name=component,enum=ApiGetStatsStoreMetricArgs_Component" json:"component,omitempty"`
	MetricName               *string                                              `protobuf:"bytes,2,opt,name=metric_name,json=metricName" json:"metric_name,omitempty"`
	Start                    *uint64                                              `protobuf:"varint,3,opt,name=start" json:"start,omitempty"`
	End                      *uint64                                              `protobuf:"varint,4,opt,name=end" json:"end,omitempty"`
	Rate                     *uint64                                              `protobuf:"varint,7,opt,name=rate" json:"rate,omitempty"`
	DistributionHandlingMode *ApiGetStatsStoreMetricArgs_DistributionHandlingMode `protobuf:"varint,5,opt,name=distribution_handling_mode,json=distributionHandlingMode,enum=ApiGetStatsStoreMetricArgs_DistributionHandlingMode" json:"distribution_handling_mode,omitempty"`
	AggregationMode          *ApiGetStatsStoreMetricArgs_AggregationMode          `protobuf:"varint,6,opt,name=aggregation_mode,json=aggregationMode,enum=ApiGetStatsStoreMetricArgs_AggregationMode" json:"aggregation_mode,omitempty"`
	XXX_unrecognized         []byte                                               `json:"-"`
}

func (m *ApiGetStatsStoreMetricArgs) Reset()                    { *m = ApiGetStatsStoreMetricArgs{} }
func (m *ApiGetStatsStoreMetricArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetStatsStoreMetricArgs) ProtoMessage()               {}
func (*ApiGetStatsStoreMetricArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ApiGetStatsStoreMetricArgs) GetComponent() ApiGetStatsStoreMetricArgs_Component {
	if m != nil && m.Component != nil {
		return *m.Component
	}
	return ApiGetStatsStoreMetricArgs_WORKER
}

func (m *ApiGetStatsStoreMetricArgs) GetMetricName() string {
	if m != nil && m.MetricName != nil {
		return *m.MetricName
	}
	return ""
}

func (m *ApiGetStatsStoreMetricArgs) GetStart() uint64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *ApiGetStatsStoreMetricArgs) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func (m *ApiGetStatsStoreMetricArgs) GetRate() uint64 {
	if m != nil && m.Rate != nil {
		return *m.Rate
	}
	return 0
}

func (m *ApiGetStatsStoreMetricArgs) GetDistributionHandlingMode() ApiGetStatsStoreMetricArgs_DistributionHandlingMode {
	if m != nil && m.DistributionHandlingMode != nil {
		return *m.DistributionHandlingMode
	}
	return ApiGetStatsStoreMetricArgs_DH_SUM
}

func (m *ApiGetStatsStoreMetricArgs) GetAggregationMode() ApiGetStatsStoreMetricArgs_AggregationMode {
	if m != nil && m.AggregationMode != nil {
		return *m.AggregationMode
	}
	return ApiGetStatsStoreMetricArgs_AGG_SUM
}

type ApiGetReportArgs struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StartTime        *uint64 `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Duration         *uint64 `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	ClientLabel      *string `protobuf:"bytes,4,opt,name=client_label,json=clientLabel" json:"client_label,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetReportArgs) Reset()                    { *m = ApiGetReportArgs{} }
func (m *ApiGetReportArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetReportArgs) ProtoMessage()               {}
func (*ApiGetReportArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ApiGetReportArgs) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiGetReportArgs) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ApiGetReportArgs) GetDuration() uint64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *ApiGetReportArgs) GetClientLabel() string {
	if m != nil && m.ClientLabel != nil {
		return *m.ClientLabel
	}
	return ""
}

type ApiListReportsResult struct {
	Reports          []*ApiReport `protobuf:"bytes,1,rep,name=reports" json:"reports,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ApiListReportsResult) Reset()                    { *m = ApiListReportsResult{} }
func (m *ApiListReportsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListReportsResult) ProtoMessage()               {}
func (*ApiListReportsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ApiListReportsResult) GetReports() []*ApiReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiStatsStoreMetricDataPoint)(nil), "ApiStatsStoreMetricDataPoint")
	proto.RegisterType((*ApiStatsStoreMetric)(nil), "ApiStatsStoreMetric")
	proto.RegisterType((*ApiReportDescriptor)(nil), "ApiReportDescriptor")
	proto.RegisterType((*ApiReport)(nil), "ApiReport")
	proto.RegisterType((*ApiReportData)(nil), "ApiReportData")
	proto.RegisterType((*ApiStackChartReportData)(nil), "ApiStackChartReportData")
	proto.RegisterType((*ApiPieChartReportData)(nil), "ApiPieChartReportData")
	proto.RegisterType((*ApiLineChartReportData)(nil), "ApiLineChartReportData")
	proto.RegisterType((*ApiAuditChartReportData)(nil), "ApiAuditChartReportData")
	proto.RegisterType((*ApiReportDataPoint1D)(nil), "ApiReportDataPoint1D")
	proto.RegisterType((*ApiReportDataSeries2D)(nil), "ApiReportDataSeries2D")
	proto.RegisterType((*ApiReportDataPoint2D)(nil), "ApiReportDataPoint2D")
	proto.RegisterType((*ApiReportTickSpecifier)(nil), "ApiReportTickSpecifier")
	proto.RegisterType((*ApiListStatsStoreMetricsMetadataArgs)(nil), "ApiListStatsStoreMetricsMetadataArgs")
	proto.RegisterType((*ApiListStatsStoreMetricsMetadataResult)(nil), "ApiListStatsStoreMetricsMetadataResult")
	proto.RegisterType((*ApiGetStatsStoreMetricArgs)(nil), "ApiGetStatsStoreMetricArgs")
	proto.RegisterType((*ApiGetReportArgs)(nil), "ApiGetReportArgs")
	proto.RegisterType((*ApiListReportsResult)(nil), "ApiListReportsResult")
	proto.RegisterEnum("ApiReportDescriptor_ReportType", ApiReportDescriptor_ReportType_name, ApiReportDescriptor_ReportType_value)
	proto.RegisterEnum("ApiReportData_RepresentationType", ApiReportData_RepresentationType_name, ApiReportData_RepresentationType_value)
	proto.RegisterEnum("ApiListStatsStoreMetricsMetadataArgs_Component", ApiListStatsStoreMetricsMetadataArgs_Component_name, ApiListStatsStoreMetricsMetadataArgs_Component_value)
	proto.RegisterEnum("ApiGetStatsStoreMetricArgs_Component", ApiGetStatsStoreMetricArgs_Component_name, ApiGetStatsStoreMetricArgs_Component_value)
	proto.RegisterEnum("ApiGetStatsStoreMetricArgs_DistributionHandlingMode", ApiGetStatsStoreMetricArgs_DistributionHandlingMode_name, ApiGetStatsStoreMetricArgs_DistributionHandlingMode_value)
	proto.RegisterEnum("ApiGetStatsStoreMetricArgs_AggregationMode", ApiGetStatsStoreMetricArgs_AggregationMode_name, ApiGetStatsStoreMetricArgs_AggregationMode_value)
}

func init() { proto.RegisterFile("grr/proto/api/stats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcf, 0x6f, 0x1b, 0xc7,
	0xf5, 0xcf, 0x4a, 0x94, 0x2c, 0x0e, 0x9d, 0x98, 0x99, 0x38, 0x36, 0xa3, 0xf8, 0xeb, 0x4c, 0x88,
	0x24, 0xb6, 0x91, 0x78, 0xf5, 0x0d, 0xf3, 0x03, 0x89, 0x9b, 0x06, 0x25, 0x45, 0xca, 0x26, 0x22,
	0x51, 0xee, 0x92, 0x76, 0x12, 0x04, 0x05, 0x31, 0xdc, 0x7d, 0x24, 0x27, 0x5a, 0xee, 0x6e, 0x66,
	0x86, 0xa2, 0x09, 0x34, 0xbd, 0x24, 0x40, 0x4f, 0x29, 0x50, 0xa0, 0xe8, 0x25, 0x45, 0x2f, 0x2d,
	0x50, 0xa0, 0xa7, 0x1e, 0x7a, 0xc9, 0xa1, 0x28, 0x0a, 0xf4, 0x50, 0xb4, 0xff, 0x41, 0x81, 0x5c,
	0xda, 0x5b, 0xff, 0x86, 0x1e, 0x8a, 0x79, 0xb3, 0xcb, 0x1f, 0x12, 0x95, 0x1a, 0x49, 0x0e, 0xbd,
	0xd8, 0xe2, 0xcc, 0xfb, 0xbc, 0xf7, 0x99, 0x37, 0x9f, 0x79, 0xf3, 0x66, 0xc9, 0x53, 0x03, 0x29,
	0x77, 0x12, 0x19, 0xeb, 0x78, 0x87, 0x27, 0x62, 0x47, 0x69, 0xae, 0x95, 0x8b, 0xbf, 0xb7, 0x2f,
	0xce, 0xa7, 0x3e, 0x8c, 0x7b, 0xd9, 0xe8, 0xd5, 0xf9, 0xe8, 0x51, 0x14, 0x4f, 0x42, 0x08, 0x06,
	0xd0, 0xed, 0x71, 0x05, 0xe9, 0x7c, 0x69, 0x3e, 0xaf, 0x60, 0xc4, 0x23, 0x2d, 0xfc, 0x74, 0xe6,
	0xf2, 0xc2, 0xcc, 0x54, 0x89, 0xa8, 0x1f, 0xdb, 0x89, 0xf2, 0xef, 0x1d, 0x72, 0xa5, 0x9a, 0x88,
	0xb6, 0x89, 0xdd, 0xd6, 0xb1, 0x84, 0x03, 0xd0, 0x52, 0xf8, 0x75, 0xae, 0xf9, 0xdd, 0x58, 0x44,
	0x9a, 0x1e, 0x92, 0xbc, 0x16, 0x23, 0x50, 0x9a, 0x8f, 0x92, 0x92, 0xc3, 0x9c, 0xeb, 0xb9, 0xda,
	0xcb, 0xff, 0xf8, 0xf7, 0x3f, 0xff, 0xec, 0xbc, 0x48, 0x0a, 0x5e, 0x7d, 0xaf, 0xce, 0x35, 0x98,
	0x79, 0x7a, 0xa5, 0x93, 0x59, 0xb1, 0xb8, 0xcf, 0xf4, 0x10, 0x58, 0xc0, 0x35, 0x67, 0x89, 0x71,
	0xe2, 0x7a, 0x73, 0x1f, 0x74, 0x97, 0x6c, 0x1c, 0xf3, 0x70, 0x0c, 0xa5, 0x35, 0xe6, 0x5c, 0x77,
	0x6a, 0x37, 0xd1, 0xd9, 0x35, 0xfa, 0xfc, 0x7d, 0x33, 0xc8, 0xfc, 0x58, 0x4a, 0x50, 0x49, 0x1c,
	0x05, 0x22, 0x1a, 0x30, 0x1d, 0xa3, 0xa7, 0x19, 0xd8, 0xf5, 0x2c, 0xb6, 0xfc, 0x17, 0x87, 0x3c,
	0xb1, 0x82, 0x36, 0x7d, 0x86, 0x14, 0x46, 0xf8, 0x57, 0x37, 0xe2, 0x23, 0x40, 0xbe, 0x79, 0x8f,
	0xd8, 0xa1, 0x16, 0x1f, 0x01, 0xbd, 0x41, 0x36, 0x94, 0xe6, 0x52, 0x63, 0xf4, 0x5c, 0xed, 0x09,
	0x8c, 0xfe, 0xe8, 0xd2, 0x52, 0x3c, 0x6b, 0x41, 0x9f, 0x27, 0xeb, 0x10, 0x05, 0xa5, 0xf5, 0xb3,
	0x0d, 0xcd, 0x3c, 0x7d, 0x9b, 0x14, 0xcc, 0x4a, 0xbb, 0xb8, 0x52, 0x55, 0xca, 0xb1, 0xf5, 0xeb,
	0x85, 0xca, 0xff, 0xb9, 0x5f, 0x95, 0x54, 0x8f, 0x04, 0xd9, 0x9f, 0xaa, 0xfc, 0xf9, 0x06, 0x2e,
	0xc5, 0x83, 0x24, 0x96, 0xba, 0x0e, 0xca, 0x97, 0x22, 0xd1, 0xb1, 0xa4, 0x1f, 0x92, 0x9c, 0x9e,
	0x26, 0x76, 0x0d, 0x8f, 0x55, 0x9e, 0x71, 0x57, 0xd8, 0xb8, 0x76, 0xa0, 0x33, 0x4d, 0xa0, 0xf6,
	0x1a, 0x12, 0xdc, 0xa1, 0x37, 0x3b, 0x71, 0x72, 0x33, 0x84, 0x63, 0x08, 0x99, 0x08, 0x20, 0xd2,
	0xa2, 0x2f, 0x40, 0x32, 0x11, 0x61, 0x22, 0x25, 0xda, 0xb3, 0xa1, 0x00, 0xc9, 0xa5, 0x3f, 0x9c,
	0xba, 0x1e, 0xc6, 0xa0, 0xbf, 0x73, 0x48, 0x0e, 0x13, 0x66, 0xb2, 0x92, 0xaf, 0x7d, 0xee, 0xa0,
	0xb3, 0x9f, 0x39, 0xf4, 0xa7, 0x4e, 0x1b, 0xfc, 0x38, 0x0a, 0x1e, 0xde, 0x23, 0xab, 0x86, 0xca,
	0xee, 0x9a, 0x71, 0x98, 0x69, 0x61, 0x79, 0x5b, 0xfd, 0x90, 0x2b, 0x65, 0x3c, 0x58, 0x74, 0x37,
	0x09, 0xc7, 0x03, 0x11, 0x29, 0x37, 0x99, 0xba, 0xac, 0x31, 0x60, 0xd7, 0x76, 0x43, 0x01, 0x91,
	0x56, 0x55, 0x5f, 0x8b, 0x63, 0xa1, 0xa7, 0x76, 0x95, 0x77, 0xd1, 0xe8, 0x9a, 0xeb, 0x21, 0x53,
	0x7a, 0x8b, 0x6c, 0x68, 0xa1, 0x43, 0xc0, 0xfd, 0xc9, 0xd7, 0x9e, 0x43, 0xc6, 0x57, 0xe9, 0x95,
	0x7b, 0xcd, 0x9b, 0x7d, 0x29, 0x20, 0x0a, 0xc2, 0x29, 0x0b, 0x84, 0x4a, 0x42, 0x3e, 0x85, 0x80,
	0xa1, 0xa9, 0xeb, 0x59, 0x08, 0xfd, 0x80, 0x9c, 0x53, 0xe3, 0xd1, 0x88, 0xcb, 0x69, 0x29, 0x87,
	0xe8, 0x2a, 0xa2, 0xbf, 0x43, 0xdf, 0x5c, 0x8d, 0x4e, 0x8d, 0xcd, 0x62, 0x26, 0x43, 0xae, 0x17,
	0x17, 0x6e, 0xff, 0x53, 0xae, 0x97, 0x79, 0xa4, 0x43, 0xf2, 0x84, 0x84, 0x8f, 0xc6, 0x42, 0x82,
	0xea, 0x1a, 0x95, 0x74, 0x25, 0x8f, 0x06, 0x50, 0xda, 0x60, 0xce, 0xf5, 0xad, 0xda, 0x1b, 0x18,
	0xa8, 0x42, 0xff, 0xbf, 0x19, 0x05, 0xc2, 0xe7, 0x1a, 0x14, 0x9b, 0x0c, 0x41, 0x0f, 0x41, 0x2e,
	0x3a, 0x8d, 0x00, 0x02, 0xc5, 0x38, 0xea, 0x9e, 0x21, 0xdc, 0xf5, 0x1e, 0xcf, 0x9c, 0x9a, 0x73,
	0xe6, 0x99, 0xb1, 0x72, 0x8f, 0x90, 0xb9, 0x00, 0x68, 0x89, 0x6c, 0xee, 0xee, 0x37, 0x1b, 0xad,
	0x4e, 0xf1, 0x91, 0xed, 0xf3, 0xff, 0xfa, 0xe2, 0x6f, 0x5f, 0x38, 0x9b, 0x36, 0x8f, 0x94, 0x11,
	0xb2, 0xd7, 0xdc, 0x6f, 0x74, 0xdb, 0x9d, 0x43, 0xaf, 0x51, 0x74, 0xb6, 0x8b, 0x38, 0x4b, 0xf6,
	0x44, 0x08, 0x4c, 0x19, 0x79, 0x1a, 0x6c, 0xbb, 0xe1, 0xdd, 0x6f, 0x78, 0xc5, 0xb5, 0x0c, 0xdb,
	0x06, 0x79, 0x0c, 0xb2, 0xfc, 0x3e, 0xc9, 0xcf, 0x84, 0x47, 0xaf, 0x93, 0x5c, 0x00, 0xca, 0x47,
	0x49, 0x16, 0x2a, 0x17, 0x57, 0x49, 0xd2, 0x43, 0x0b, 0x5a, 0x26, 0x39, 0x23, 0x71, 0xd4, 0x53,
	0xa1, 0xf2, 0xd8, 0x82, 0x25, 0xd7, 0xdc, 0xc3, 0xb9, 0xf2, 0xa7, 0x39, 0xf2, 0xe8, 0xd2, 0x38,
	0xf5, 0x4c, 0xea, 0x12, 0x09, 0x0a, 0x22, 0xcd, 0xb5, 0x88, 0xa3, 0xee, 0xc2, 0x09, 0x78, 0x76,
	0xd9, 0x89, 0xd1, 0xfe, 0x82, 0xa5, 0x49, 0x81, 0x47, 0xe5, 0xa9, 0x31, 0xfa, 0x26, 0x29, 0x28,
	0xcd, 0xfd, 0xa3, 0xae, 0x3f, 0xcc, 0x8e, 0x7d, 0xa1, 0x52, 0x4a, 0x8f, 0xa7, 0x7f, 0xb4, 0x6b,
	0x46, 0x17, 0xa8, 0x11, 0x35, 0x1b, 0xa5, 0xaf, 0x90, 0x7c, 0x22, 0x20, 0x05, 0xae, 0x23, 0xf0,
	0x92, 0x01, 0xde, 0x15, 0x70, 0x12, 0xb6, 0x95, 0xa4, 0x63, 0xf4, 0x75, 0x42, 0x42, 0x11, 0x65,
	0xa8, 0x1c, 0xa2, 0x2e, 0x1b, 0xd4, 0xbe, 0x88, 0x4e, 0xc1, 0xf2, 0x61, 0x36, 0x68, 0x78, 0xf2,
	0x71, 0x20, 0x74, 0x0a, 0xdc, 0x98, 0xf3, 0xac, 0x9a, 0xe1, 0x53, 0x3c, 0xf9, 0x6c, 0xb4, 0xfc,
	0x4b, 0x87, 0xd0, 0xd3, 0xd9, 0xa0, 0x65, 0x52, 0x68, 0x77, 0xaa, 0xbb, 0xef, 0x74, 0x77, 0xef,
	0x54, 0x3d, 0xa3, 0x8a, 0xc7, 0x71, 0x67, 0x0b, 0xb8, 0x6e, 0x86, 0x61, 0xe8, 0x55, 0x92, 0xbf,
	0xdb, 0x6c, 0xa4, 0x16, 0xce, 0xf6, 0x05, 0xb4, 0xc8, 0xdf, 0x15, 0x90, 0xce, 0x33, 0x42, 0xf6,
	0x9b, 0xad, 0xcc, 0x60, 0x2d, 0x93, 0x8e, 0x59, 0x4b, 0x6a, 0x51, 0x26, 0x85, 0xea, 0xbd, 0x7a,
	0xb3, 0x93, 0x9a, 0xac, 0x67, 0x51, 0x90, 0xb5, 0xb5, 0xb9, 0xf5, 0xf4, 0xdf, 0x8d, 0xea, 0x9f,
	0xa4, 0xab, 0x76, 0xb7, 0xfc, 0xeb, 0x75, 0x72, 0xf9, 0x8c, 0xdd, 0xa0, 0x07, 0xa9, 0x8c, 0x1c,
	0x2c, 0xaa, 0x97, 0x96, 0x15, 0xd0, 0x06, 0x29, 0x40, 0x55, 0xea, 0xb5, 0x67, 0xf1, 0x50, 0x3d,
	0x4d, 0x9f, 0x7a, 0xf7, 0xc4, 0xe1, 0xf4, 0xe3, 0x48, 0x73, 0x53, 0x58, 0xac, 0xe2, 0xa8, 0x26,
	0xe7, 0x1e, 0x74, 0xb5, 0xf0, 0x8f, 0x54, 0x69, 0x0d, 0x3d, 0x5e, 0x9e, 0x7b, 0xec, 0x08, 0xff,
	0xa8, 0x9d, 0x80, 0x8f, 0xd5, 0xad, 0x56, 0x43, 0x97, 0x6f, 0xd1, 0x5b, 0xef, 0x31, 0xfe, 0x40,
	0x28, 0x86, 0x20, 0x97, 0xb5, 0x01, 0x6e, 0xb1, 0x81, 0xd0, 0xc3, 0x71, 0xcf, 0xf5, 0xe3, 0xd1,
	0x4e, 0x3f, 0x8c, 0xb5, 0xfd, 0xa7, 0x17, 0xc6, 0xbd, 0x9d, 0x11, 0x57, 0x1a, 0xe4, 0x4e, 0xf5,
	0x6e, 0xd3, 0x1d, 0x05, 0xde, 0xe6, 0x03, 0xe3, 0x53, 0x99, 0xa8, 0xd3, 0x34, 0xea, 0xfa, 0x43,
	0x46, 0x7d, 0xff, 0x1b, 0x44, 0x9d, 0xda, 0xa8, 0x2d, 0x92, 0xef, 0x71, 0xd9, 0x9d, 0x88, 0x40,
	0x0f, 0x51, 0x86, 0x6b, 0xd9, 0xbd, 0x4d, 0x6f, 0xbc, 0x6b, 0x06, 0xb3, 0xd2, 0xdc, 0xe3, 0x52,
	0x2d, 0xd4, 0xba, 0xd8, 0xd6, 0x75, 0xdc, 0x38, 0xd7, 0xdb, 0xea, 0x71, 0x89, 0xd6, 0x65, 0x20,
	0x4f, 0xae, 0x94, 0x3e, 0xdd, 0x5f, 0xda, 0xa3, 0x27, 0x97, 0xf7, 0x08, 0xef, 0xb8, 0x97, 0x1f,
	0x7e, 0x8b, 0xca, 0x03, 0x72, 0x69, 0xf5, 0x59, 0xf9, 0x96, 0xb5, 0x50, 0xfe, 0xa3, 0x83, 0xb2,
	0x5b, 0x75, 0xb8, 0xe8, 0x07, 0xa4, 0x30, 0x56, 0x10, 0x74, 0xfb, 0x02, 0xc2, 0x40, 0x61, 0xc4,
	0x7c, 0xed, 0x16, 0x7a, 0x7e, 0x95, 0x56, 0x4c, 0x1f, 0xa1, 0xb2, 0xec, 0x21, 0xbe, 0x71, 0x0c,
	0x91, 0x66, 0xd6, 0x9a, 0x19, 0x24, 0xeb, 0x4d, 0x17, 0x62, 0xbb, 0x1e, 0x31, 0x83, 0x7b, 0x38,
	0x4f, 0x6f, 0x93, 0x9c, 0x8c, 0x27, 0x99, 0x02, 0x0b, 0xee, 0xdc, 0x43, 0xed, 0x05, 0x0c, 0xc1,
	0xe8, 0x55, 0xc3, 0xc2, 0x34, 0x3f, 0x3d, 0x60, 0x6a, 0x18, 0x4f, 0xa2, 0xec, 0xb6, 0x4d, 0x77,
	0x05, 0x1d, 0x94, 0x8f, 0xc8, 0xc5, 0x55, 0xb9, 0xa6, 0xe7, 0x89, 0xf3, 0x00, 0x6b, 0xe6, 0x9a,
	0xe7, 0x3c, 0xa0, 0x0d, 0xb2, 0x11, 0xf2, 0x1e, 0x84, 0xe9, 0xd5, 0xbe, 0x83, 0x21, 0x6e, 0xd0,
	0x6b, 0x9d, 0x21, 0x30, 0x85, 0x59, 0x63, 0x42, 0x31, 0x34, 0x81, 0x80, 0x4d, 0x84, 0x1e, 0x32,
	0x3d, 0x14, 0x8a, 0x29, 0x2d, 0x45, 0x34, 0x70, 0x3d, 0x8b, 0x2e, 0x7f, 0xe6, 0xe0, 0xfe, 0x9f,
	0xce, 0xf8, 0x3c, 0x80, 0xf3, 0x4d, 0x02, 0xd0, 0x9b, 0x64, 0x33, 0xed, 0xa0, 0xd6, 0xce, 0x14,
	0x52, 0xa5, 0xee, 0xa5, 0x46, 0xe5, 0xca, 0xaa, 0xc5, 0x57, 0x4e, 0x2e, 0xfe, 0x3c, 0x71, 0xa6,
	0xb8, 0xf0, 0x35, 0xcf, 0x99, 0x96, 0xdf, 0x42, 0x6d, 0xad, 0x38, 0x78, 0x27, 0x50, 0x17, 0x97,
	0x52, 0x96, 0x65, 0xe0, 0xb7, 0x0e, 0x79, 0x0e, 0xa5, 0xa9, 0xf4, 0xc9, 0xc6, 0x4e, 0x1d, 0x80,
	0xe6, 0x46, 0x55, 0x55, 0x39, 0x50, 0xf4, 0x80, 0xe4, 0xfd, 0x78, 0x94, 0xc4, 0x11, 0x44, 0x3a,
	0xbd, 0xbb, 0x76, 0xdc, 0x87, 0x41, 0xba, 0xbb, 0x19, 0xcc, 0x9b, 0x7b, 0x28, 0xbf, 0x42, 0xf2,
	0xb3, 0x71, 0x4a, 0xc8, 0xe6, 0xbb, 0x87, 0xde, 0x3b, 0x0d, 0xaf, 0xf8, 0x08, 0x3d, 0x4f, 0xb6,
	0xf6, 0xbc, 0xc3, 0x56, 0xa7, 0xd1, 0xaa, 0x17, 0x1d, 0xf3, 0xab, 0x5a, 0x3f, 0x68, 0xb6, 0xba,
	0xf7, 0x9a, 0xc5, 0xb5, 0xf2, 0x21, 0x79, 0xe1, 0xbf, 0x45, 0xf4, 0x40, 0x8d, 0x43, 0xd3, 0xe5,
	0x6e, 0x08, 0x0d, 0x23, 0x95, 0x9e, 0xab, 0x0b, 0xae, 0x35, 0x9b, 0x59, 0xd9, 0xd9, 0xf2, 0x97,
	0x84, 0x6c, 0x57, 0x13, 0x71, 0x1b, 0x4e, 0x39, 0xc4, 0x35, 0xef, 0x9e, 0x5e, 0xf3, 0xf3, 0xee,
	0xd9, 0xf6, 0x2b, 0x57, 0x7a, 0xb2, 0x79, 0x5f, 0x3b, 0xd5, 0xbc, 0x7f, 0xe2, 0x64, 0xdd, 0xbb,
	0x6d, 0xca, 0x47, 0xa8, 0xb5, 0xc1, 0xf2, 0x43, 0xe4, 0xbd, 0x3d, 0xd0, 0xfe, 0x90, 0x59, 0x98,
	0xb2, 0xaf, 0x10, 0x04, 0x99, 0xce, 0xb3, 0x2f, 0xe3, 0x91, 0x95, 0xdf, 0xfc, 0x4d, 0xc1, 0x9a,
	0x7d, 0x16, 0xc5, 0x9a, 0x29, 0xd0, 0x2f, 0xb1, 0x89, 0x08, 0x43, 0x16, 0x40, 0x9f, 0x8f, 0x43,
	0x6d, 0x4e, 0xe0, 0xcb, 0x6c, 0x18, 0x8f, 0x25, 0xe3, 0x83, 0xd8, 0xcd, 0xde, 0x05, 0x3f, 0x77,
	0xec, 0xc3, 0x20, 0x87, 0x1c, 0x3e, 0xb1, 0xbd, 0xf2, 0xc7, 0xcb, 0x24, 0xa2, 0x15, 0x24, 0xd2,
	0xd8, 0xc0, 0x44, 0xa4, 0x41, 0x1e, 0xf3, 0x90, 0x81, 0x6d, 0x87, 0xe7, 0x67, 0xe2, 0x21, 0x49,
	0x61, 0x29, 0x18, 0x4b, 0x69, 0xaa, 0x8e, 0x81, 0xb8, 0xf6, 0x25, 0x32, 0x21, 0x39, 0xc9, 0x35,
	0x94, 0xce, 0x21, 0x31, 0x1f, 0x79, 0xfd, 0x80, 0x6c, 0xd5, 0xc7, 0x12, 0xaf, 0x5b, 0xfa, 0xfd,
	0x66, 0xdf, 0xfa, 0xb3, 0xb4, 0xae, 0x29, 0x66, 0xcc, 0x59, 0x7c, 0x0c, 0x92, 0x0d, 0xc4, 0x31,
	0x44, 0x6c, 0x22, 0xa2, 0x20, 0x9e, 0xd8, 0x78, 0x3d, 0x53, 0xbe, 0xf4, 0x58, 0x46, 0x10, 0x30,
	0x11, 0x29, 0x0d, 0x3c, 0x30, 0x45, 0x2f, 0x09, 0xb9, 0x88, 0x18, 0xbe, 0xc2, 0x4c, 0x2d, 0x35,
	0x1e, 0xe8, 0x1f, 0x1c, 0xb2, 0x1d, 0x08, 0x73, 0xa0, 0x7b, 0x63, 0xbc, 0xd8, 0x87, 0x3c, 0x0a,
	0x42, 0x11, 0x0d, 0xba, 0xa3, 0x38, 0xb0, 0xad, 0xef, 0x63, 0x95, 0x57, 0xbf, 0x4a, 0x0f, 0xf5,
	0x05, 0xf4, 0x9d, 0x14, 0x7c, 0x10, 0x07, 0x50, 0x6b, 0xe2, 0x2a, 0x76, 0x69, 0xb5, 0x0e, 0x1a,
	0xe4, 0x48, 0x44, 0xd8, 0x31, 0x0b, 0x7f, 0x98, 0x52, 0x30, 0xe9, 0xe8, 0x63, 0xae, 0x27, 0x43,
	0x88, 0x58, 0x00, 0x3c, 0x9c, 0xa5, 0x74, 0x91, 0x92, 0x72, 0xbd, 0x52, 0x70, 0x46, 0x10, 0xfa,
	0xa5, 0x43, 0x8a, 0x7c, 0x30, 0x90, 0x30, 0xb0, 0x7d, 0x09, 0xb2, 0xde, 0x44, 0xd6, 0x2f, 0x7e,
	0x15, 0xeb, 0xea, 0x1c, 0x83, 0x64, 0x3f, 0xb5, 0x5a, 0xf8, 0x11, 0xfd, 0xe1, 0xc2, 0x8c, 0xc9,
	0xf6, 0x30, 0x0e, 0x5c, 0x56, 0x55, 0x33, 0x3d, 0x70, 0x09, 0x6c, 0xac, 0xc6, 0x3c, 0x0c, 0xa7,
	0xcc, 0x8f, 0xc3, 0x10, 0x7c, 0x0d, 0x01, 0xe3, 0xbe, 0x8c, 0x95, 0x62, 0xa3, 0x71, 0xa8, 0x45,
	0x12, 0x02, 0x4b, 0x64, 0xec, 0x83, 0x52, 0xa0, 0x5e, 0x62, 0xa3, 0x58, 0xe9, 0xec, 0xca, 0xc1,
	0x57, 0x81, 0x1e, 0xc2, 0x94, 0x0d, 0xf9, 0x31, 0xa4, 0xd7, 0x44, 0x46, 0x1f, 0x02, 0xd7, 0xbb,
	0xc0, 0x97, 0x79, 0x7d, 0xbd, 0x12, 0xf2, 0x27, 0x87, 0x94, 0xce, 0xda, 0x16, 0x7a, 0x48, 0x36,
	0xeb, 0x77, 0xba, 0xed, 0x7b, 0x07, 0xc5, 0x47, 0xb6, 0x77, 0xb1, 0xe1, 0xfb, 0x6e, 0x7b, 0x3c,
	0x32, 0x0c, 0x79, 0x18, 0x66, 0x5b, 0x23, 0xc1, 0x8f, 0x65, 0x80, 0xf2, 0x61, 0x7c, 0x69, 0x37,
	0x66, 0x0a, 0xc3, 0xad, 0x83, 0xc0, 0xa5, 0x1d, 0xb2, 0x55, 0xbf, 0xd3, 0xdd, 0x3d, 0xbc, 0xd7,
	0x32, 0x7d, 0xe8, 0x1e, 0xba, 0xfc, 0x5e, 0x6b, 0x3c, 0xea, 0x81, 0xfc, 0xfa, 0x5e, 0xcb, 0xbf,
	0x71, 0xc8, 0x85, 0x13, 0x9b, 0x44, 0x6f, 0x90, 0x73, 0xd5, 0xdb, 0xb7, 0x53, 0xee, 0x57, 0x30,
	0xd0, 0xa5, 0xfb, 0xd6, 0x75, 0x86, 0x37, 0x4f, 0x39, 0x43, 0xaa, 0x42, 0xb6, 0x8c, 0xe9, 0x41,
	0xa3, 0xda, 0x2a, 0x3a, 0xdb, 0xcf, 0xa1, 0xed, 0xd5, 0x03, 0xe0, 0xa9, 0xfe, 0x67, 0xf6, 0x3e,
	0x0f, 0xfd, 0x71, 0x88, 0xc9, 0xa7, 0xaf, 0x59, 0x4c, 0xeb, 0xb0, 0xd5, 0x28, 0xae, 0x6d, 0x5f,
	0x43, 0xcc, 0xb3, 0xad, 0x98, 0x2d, 0xec, 0xc9, 0x0c, 0x97, 0x80, 0xec, 0xc7, 0xd2, 0x84, 0x2a,
	0xff, 0x35, 0x47, 0x8a, 0x56, 0x69, 0xf6, 0x7e, 0xc2, 0xaa, 0xfa, 0xab, 0xec, 0x59, 0x6e, 0xaf,
	0xd6, 0x9f, 0x58, 0x79, 0xfd, 0xd8, 0xa1, 0x9f, 0x3a, 0xcd, 0xff, 0x9d, 0x97, 0xf8, 0x2f, 0x1c,
	0x42, 0xb0, 0x32, 0xe2, 0x73, 0x37, 0xfd, 0xb0, 0xf2, 0x31, 0x52, 0x9d, 0x2c, 0x57, 0xc5, 0x61,
	0x83, 0xcb, 0x50, 0x80, 0xd2, 0xf3, 0x42, 0x67, 0x68, 0xcd, 0x3f, 0x14, 0xe1, 0x71, 0xf6, 0xe3,
	0x48, 0x89, 0x00, 0xa4, 0xcb, 0x9a, 0x83, 0x28, 0x96, 0xb6, 0x9b, 0x4a, 0xdf, 0xd9, 0xf6, 0x60,
	0xaf, 0x78, 0x5f, 0x9b, 0xc2, 0x86, 0xb5, 0x80, 0x87, 0x0a, 0x5c, 0x2f, 0x8f, 0x84, 0xcc, 0x53,
	0x99, 0x7e, 0xe6, 0x90, 0xad, 0x20, 0x2d, 0x81, 0xe9, 0xbd, 0xf1, 0x11, 0x92, 0x3b, 0x5a, 0x28,
	0x8d, 0xdd, 0x7d, 0x88, 0x06, 0xf3, 0x9e, 0x78, 0xfe, 0xf0, 0xfe, 0xb6, 0x08, 0xcd, 0x28, 0x50,
	0x4e, 0xce, 0xfb, 0x98, 0xd5, 0xae, 0x6d, 0x32, 0xec, 0x17, 0x88, 0xb7, 0x91, 0xd2, 0x1b, 0xf4,
	0x75, 0x9b, 0x71, 0xdb, 0x2f, 0xcd, 0x7a, 0x49, 0xfc, 0x75, 0x53, 0xd9, 0x7e, 0xc5, 0x9f, 0x7d,
	0x74, 0x60, 0x87, 0x89, 0x71, 0xc9, 0x43, 0xd7, 0x2b, 0x58, 0x9f, 0xfb, 0xd8, 0xaa, 0xdc, 0xc7,
	0xe6, 0xc8, 0xdc, 0xfe, 0x76, 0xc3, 0x54, 0x7a, 0xd7, 0xbf, 0x4d, 0xce, 0xa5, 0xd0, 0xf4, 0xb6,
	0x27, 0xf3, 0x26, 0xab, 0x56, 0x42, 0x06, 0x94, 0x16, 0x3b, 0x73, 0x31, 0x85, 0x42, 0x69, 0xd7,
	0xcb, 0x40, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x79, 0x87, 0xe9, 0xc1, 0xb1, 0x14, 0x00, 0x00,
}
