// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/user.proto

It has these top-level messages:
	ApiHuntApproval
	ApiCronJobApproval
	ApiClientApproval
	ApiGrrUserInterfaceTraits
	ApiGrrUser
	ApiNotificationReference
	ApiNotificationDiscoveryReference
	ApiNotificationFileDownloadReference
	ApiNotificationHuntReference
	ApiNotificationCronReference
	ApiNotificationFlowReference
	ApiNotificationVfsReference
	ApiNotificationClientApprovalReference
	ApiNotificationHuntApprovalReference
	ApiNotificationCronJobApprovalReference
	ApiNotificationUnknownReference
	ApiNotification
	ApiCreateHuntApprovalArgs
	ApiGetHuntApprovalArgs
	ApiGrantHuntApprovalArgs
	ApiListHuntApprovalsArgs
	ApiListHuntApprovalsResult
	ApiCreateCronJobApprovalArgs
	ApiGetCronJobApprovalArgs
	ApiGrantCronJobApprovalArgs
	ApiListCronJobApprovalsArgs
	ApiListCronJobApprovalsResult
	ApiCreateClientApprovalArgs
	ApiGetClientApprovalArgs
	ApiGrantClientApprovalArgs
	ApiListClientApprovalsArgs
	ApiListClientApprovalsResult
	ApiListPendingGlobalNotificationsResult
	ApiDeletePendingGlobalNotificationArgs
	ApiGetPendingUserNotificationsCountResult
	ApiDeletePendingUserNotificationArgs
	ApiListAndResetUserNotificationsArgs
	ApiListAndResetUserNotificationsResult
	ApiListPendingUserNotificationsArgs
	ApiListPendingUserNotificationsResult
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cron "github.com/google/grr_go_api_client/grrproto/grr/proto/api/cron_proto"
import hunt "github.com/google/grr_go_api_client/grrproto/grr/proto/api/hunt_proto"
import client "github.com/google/grr_go_api_client/grrproto/grr/proto/api/client_proto"
import flows "github.com/google/grr_go_api_client/grrproto/grr/proto/flows_proto"
import jobs "github.com/google/grr_go_api_client/grrproto/grr/proto/jobs_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiNotificationReference_Type int32

const (
	ApiNotificationReference_DISCOVERY         ApiNotificationReference_Type = 0
	ApiNotificationReference_HUNT              ApiNotificationReference_Type = 3
	ApiNotificationReference_CRON              ApiNotificationReference_Type = 4
	ApiNotificationReference_FLOW              ApiNotificationReference_Type = 5
	ApiNotificationReference_VFS               ApiNotificationReference_Type = 6
	ApiNotificationReference_CLIENT_APPROVAL   ApiNotificationReference_Type = 10
	ApiNotificationReference_HUNT_APPROVAL     ApiNotificationReference_Type = 11
	ApiNotificationReference_CRON_JOB_APPROVAL ApiNotificationReference_Type = 12
	ApiNotificationReference_UNKNOWN           ApiNotificationReference_Type = 13
)

var ApiNotificationReference_Type_name = map[int32]string{
	0:  "DISCOVERY",
	3:  "HUNT",
	4:  "CRON",
	5:  "FLOW",
	6:  "VFS",
	10: "CLIENT_APPROVAL",
	11: "HUNT_APPROVAL",
	12: "CRON_JOB_APPROVAL",
	13: "UNKNOWN",
}
var ApiNotificationReference_Type_value = map[string]int32{
	"DISCOVERY":         0,
	"HUNT":              3,
	"CRON":              4,
	"FLOW":              5,
	"VFS":               6,
	"CLIENT_APPROVAL":   10,
	"HUNT_APPROVAL":     11,
	"CRON_JOB_APPROVAL": 12,
	"UNKNOWN":           13,
}

func (x ApiNotificationReference_Type) Enum() *ApiNotificationReference_Type {
	p := new(ApiNotificationReference_Type)
	*p = x
	return p
}
func (x ApiNotificationReference_Type) String() string {
	return proto.EnumName(ApiNotificationReference_Type_name, int32(x))
}
func (x *ApiNotificationReference_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiNotificationReference_Type_value, data, "ApiNotificationReference_Type")
	if err != nil {
		return err
	}
	*x = ApiNotificationReference_Type(value)
	return nil
}
func (ApiNotificationReference_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type ApiListClientApprovalsArgs_State int32

const (
	ApiListClientApprovalsArgs_ANY     ApiListClientApprovalsArgs_State = 0
	ApiListClientApprovalsArgs_VALID   ApiListClientApprovalsArgs_State = 1
	ApiListClientApprovalsArgs_INVALID ApiListClientApprovalsArgs_State = 2
)

var ApiListClientApprovalsArgs_State_name = map[int32]string{
	0: "ANY",
	1: "VALID",
	2: "INVALID",
}
var ApiListClientApprovalsArgs_State_value = map[string]int32{
	"ANY":     0,
	"VALID":   1,
	"INVALID": 2,
}

func (x ApiListClientApprovalsArgs_State) Enum() *ApiListClientApprovalsArgs_State {
	p := new(ApiListClientApprovalsArgs_State)
	*p = x
	return p
}
func (x ApiListClientApprovalsArgs_State) String() string {
	return proto.EnumName(ApiListClientApprovalsArgs_State_name, int32(x))
}
func (x *ApiListClientApprovalsArgs_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiListClientApprovalsArgs_State_value, data, "ApiListClientApprovalsArgs_State")
	if err != nil {
		return err
	}
	*x = ApiListClientApprovalsArgs_State(value)
	return nil
}
func (ApiListClientApprovalsArgs_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{30, 0}
}

type ApiHuntApproval struct {
	Subject          *hunt.ApiHunt `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Id               *string       `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	Reason           *string       `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	IsValid          *bool         `protobuf:"varint,3,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	IsValidMessage   *string       `protobuf:"bytes,4,opt,name=is_valid_message,json=isValidMessage" json:"is_valid_message,omitempty"`
	NotifiedUsers    []string      `protobuf:"bytes,5,rep,name=notified_users,json=notifiedUsers" json:"notified_users,omitempty"`
	EmailCcAddresses []string      `protobuf:"bytes,6,rep,name=email_cc_addresses,json=emailCcAddresses" json:"email_cc_addresses,omitempty"`
	Approvers        []string      `protobuf:"bytes,7,rep,name=approvers" json:"approvers,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ApiHuntApproval) Reset()                    { *m = ApiHuntApproval{} }
func (m *ApiHuntApproval) String() string            { return proto.CompactTextString(m) }
func (*ApiHuntApproval) ProtoMessage()               {}
func (*ApiHuntApproval) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiHuntApproval) GetSubject() *hunt.ApiHunt {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *ApiHuntApproval) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ApiHuntApproval) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *ApiHuntApproval) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

func (m *ApiHuntApproval) GetIsValidMessage() string {
	if m != nil && m.IsValidMessage != nil {
		return *m.IsValidMessage
	}
	return ""
}

func (m *ApiHuntApproval) GetNotifiedUsers() []string {
	if m != nil {
		return m.NotifiedUsers
	}
	return nil
}

func (m *ApiHuntApproval) GetEmailCcAddresses() []string {
	if m != nil {
		return m.EmailCcAddresses
	}
	return nil
}

func (m *ApiHuntApproval) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

type ApiCronJobApproval struct {
	Subject          *cron.ApiCronJob `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Id               *string          `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	Reason           *string          `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	IsValid          *bool            `protobuf:"varint,3,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	IsValidMessage   *string          `protobuf:"bytes,4,opt,name=is_valid_message,json=isValidMessage" json:"is_valid_message,omitempty"`
	NotifiedUsers    []string         `protobuf:"bytes,5,rep,name=notified_users,json=notifiedUsers" json:"notified_users,omitempty"`
	EmailCcAddresses []string         `protobuf:"bytes,6,rep,name=email_cc_addresses,json=emailCcAddresses" json:"email_cc_addresses,omitempty"`
	Approvers        []string         `protobuf:"bytes,7,rep,name=approvers" json:"approvers,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ApiCronJobApproval) Reset()                    { *m = ApiCronJobApproval{} }
func (m *ApiCronJobApproval) String() string            { return proto.CompactTextString(m) }
func (*ApiCronJobApproval) ProtoMessage()               {}
func (*ApiCronJobApproval) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiCronJobApproval) GetSubject() *cron.ApiCronJob {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *ApiCronJobApproval) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ApiCronJobApproval) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *ApiCronJobApproval) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

func (m *ApiCronJobApproval) GetIsValidMessage() string {
	if m != nil && m.IsValidMessage != nil {
		return *m.IsValidMessage
	}
	return ""
}

func (m *ApiCronJobApproval) GetNotifiedUsers() []string {
	if m != nil {
		return m.NotifiedUsers
	}
	return nil
}

func (m *ApiCronJobApproval) GetEmailCcAddresses() []string {
	if m != nil {
		return m.EmailCcAddresses
	}
	return nil
}

func (m *ApiCronJobApproval) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

type ApiClientApproval struct {
	Subject          *client.ApiClient `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Id               *string           `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	Reason           *string           `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	IsValid          *bool             `protobuf:"varint,3,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	IsValidMessage   *string           `protobuf:"bytes,4,opt,name=is_valid_message,json=isValidMessage" json:"is_valid_message,omitempty"`
	NotifiedUsers    []string          `protobuf:"bytes,5,rep,name=notified_users,json=notifiedUsers" json:"notified_users,omitempty"`
	EmailCcAddresses []string          `protobuf:"bytes,6,rep,name=email_cc_addresses,json=emailCcAddresses" json:"email_cc_addresses,omitempty"`
	Approvers        []string          `protobuf:"bytes,7,rep,name=approvers" json:"approvers,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ApiClientApproval) Reset()                    { *m = ApiClientApproval{} }
func (m *ApiClientApproval) String() string            { return proto.CompactTextString(m) }
func (*ApiClientApproval) ProtoMessage()               {}
func (*ApiClientApproval) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiClientApproval) GetSubject() *client.ApiClient {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *ApiClientApproval) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ApiClientApproval) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *ApiClientApproval) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

func (m *ApiClientApproval) GetIsValidMessage() string {
	if m != nil && m.IsValidMessage != nil {
		return *m.IsValidMessage
	}
	return ""
}

func (m *ApiClientApproval) GetNotifiedUsers() []string {
	if m != nil {
		return m.NotifiedUsers
	}
	return nil
}

func (m *ApiClientApproval) GetEmailCcAddresses() []string {
	if m != nil {
		return m.EmailCcAddresses
	}
	return nil
}

func (m *ApiClientApproval) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

// These traits are used by the AdminUI Angular app to disable certain UI
// elements.
type ApiGrrUserInterfaceTraits struct {
	CronJobsNavItemEnabled                *bool  `protobuf:"varint,1,opt,name=cron_jobs_nav_item_enabled,json=cronJobsNavItemEnabled" json:"cron_jobs_nav_item_enabled,omitempty"`
	CreateCronJobActionEnabled            *bool  `protobuf:"varint,2,opt,name=create_cron_job_action_enabled,json=createCronJobActionEnabled" json:"create_cron_job_action_enabled,omitempty"`
	HuntManagerNavItemEnabled             *bool  `protobuf:"varint,3,opt,name=hunt_manager_nav_item_enabled,json=huntManagerNavItemEnabled" json:"hunt_manager_nav_item_enabled,omitempty"`
	CreateHuntActionEnabled               *bool  `protobuf:"varint,4,opt,name=create_hunt_action_enabled,json=createHuntActionEnabled" json:"create_hunt_action_enabled,omitempty"`
	ShowStatisticsNavItemEnabled          *bool  `protobuf:"varint,5,opt,name=show_statistics_nav_item_enabled,json=showStatisticsNavItemEnabled" json:"show_statistics_nav_item_enabled,omitempty"`
	StartGlobalFlowsNavItemEnabled        *bool  `protobuf:"varint,6,opt,name=start_global_flows_nav_item_enabled,json=startGlobalFlowsNavItemEnabled" json:"start_global_flows_nav_item_enabled,omitempty"`
	ServerLoadNavItemEnabled              *bool  `protobuf:"varint,7,opt,name=server_load_nav_item_enabled,json=serverLoadNavItemEnabled" json:"server_load_nav_item_enabled,omitempty"`
	ManageBinariesNavItemEnabled          *bool  `protobuf:"varint,9,opt,name=manage_binaries_nav_item_enabled,json=manageBinariesNavItemEnabled" json:"manage_binaries_nav_item_enabled,omitempty"`
	UploadBinaryActionEnabled             *bool  `protobuf:"varint,10,opt,name=upload_binary_action_enabled,json=uploadBinaryActionEnabled" json:"upload_binary_action_enabled,omitempty"`
	SettingsNavItemEnabled                *bool  `protobuf:"varint,11,opt,name=settings_nav_item_enabled,json=settingsNavItemEnabled" json:"settings_nav_item_enabled,omitempty"`
	ArtifactManagerNavItemEnabled         *bool  `protobuf:"varint,12,opt,name=artifact_manager_nav_item_enabled,json=artifactManagerNavItemEnabled" json:"artifact_manager_nav_item_enabled,omitempty"`
	UploadArtifactActionEnabled           *bool  `protobuf:"varint,13,opt,name=upload_artifact_action_enabled,json=uploadArtifactActionEnabled" json:"upload_artifact_action_enabled,omitempty"`
	SearchClientsActionEnabled            *bool  `protobuf:"varint,14,opt,name=search_clients_action_enabled,json=searchClientsActionEnabled" json:"search_clients_action_enabled,omitempty"`
	BrowseVirtualFileSystemNavItemEnabled *bool  `protobuf:"varint,15,opt,name=browse_virtual_file_system_nav_item_enabled,json=browseVirtualFileSystemNavItemEnabled" json:"browse_virtual_file_system_nav_item_enabled,omitempty"`
	StartClientFlowNavItemEnabled         *bool  `protobuf:"varint,16,opt,name=start_client_flow_nav_item_enabled,json=startClientFlowNavItemEnabled" json:"start_client_flow_nav_item_enabled,omitempty"`
	ManageClientFlowsNavItemEnabled       *bool  `protobuf:"varint,17,opt,name=manage_client_flows_nav_item_enabled,json=manageClientFlowsNavItemEnabled" json:"manage_client_flows_nav_item_enabled,omitempty"`
	ModifyClientLabelsActionEnabled       *bool  `protobuf:"varint,18,opt,name=modify_client_labels_action_enabled,json=modifyClientLabelsActionEnabled" json:"modify_client_labels_action_enabled,omitempty"`
	XXX_unrecognized                      []byte `json:"-"`
}

func (m *ApiGrrUserInterfaceTraits) Reset()                    { *m = ApiGrrUserInterfaceTraits{} }
func (m *ApiGrrUserInterfaceTraits) String() string            { return proto.CompactTextString(m) }
func (*ApiGrrUserInterfaceTraits) ProtoMessage()               {}
func (*ApiGrrUserInterfaceTraits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiGrrUserInterfaceTraits) GetCronJobsNavItemEnabled() bool {
	if m != nil && m.CronJobsNavItemEnabled != nil {
		return *m.CronJobsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateCronJobActionEnabled() bool {
	if m != nil && m.CreateCronJobActionEnabled != nil {
		return *m.CreateCronJobActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetHuntManagerNavItemEnabled() bool {
	if m != nil && m.HuntManagerNavItemEnabled != nil {
		return *m.HuntManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateHuntActionEnabled() bool {
	if m != nil && m.CreateHuntActionEnabled != nil {
		return *m.CreateHuntActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetShowStatisticsNavItemEnabled() bool {
	if m != nil && m.ShowStatisticsNavItemEnabled != nil {
		return *m.ShowStatisticsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetStartGlobalFlowsNavItemEnabled() bool {
	if m != nil && m.StartGlobalFlowsNavItemEnabled != nil {
		return *m.StartGlobalFlowsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetServerLoadNavItemEnabled() bool {
	if m != nil && m.ServerLoadNavItemEnabled != nil {
		return *m.ServerLoadNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageBinariesNavItemEnabled() bool {
	if m != nil && m.ManageBinariesNavItemEnabled != nil {
		return *m.ManageBinariesNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadBinaryActionEnabled() bool {
	if m != nil && m.UploadBinaryActionEnabled != nil {
		return *m.UploadBinaryActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSettingsNavItemEnabled() bool {
	if m != nil && m.SettingsNavItemEnabled != nil {
		return *m.SettingsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetArtifactManagerNavItemEnabled() bool {
	if m != nil && m.ArtifactManagerNavItemEnabled != nil {
		return *m.ArtifactManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadArtifactActionEnabled() bool {
	if m != nil && m.UploadArtifactActionEnabled != nil {
		return *m.UploadArtifactActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSearchClientsActionEnabled() bool {
	if m != nil && m.SearchClientsActionEnabled != nil {
		return *m.SearchClientsActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetBrowseVirtualFileSystemNavItemEnabled() bool {
	if m != nil && m.BrowseVirtualFileSystemNavItemEnabled != nil {
		return *m.BrowseVirtualFileSystemNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetStartClientFlowNavItemEnabled() bool {
	if m != nil && m.StartClientFlowNavItemEnabled != nil {
		return *m.StartClientFlowNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageClientFlowsNavItemEnabled() bool {
	if m != nil && m.ManageClientFlowsNavItemEnabled != nil {
		return *m.ManageClientFlowsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetModifyClientLabelsActionEnabled() bool {
	if m != nil && m.ModifyClientLabelsActionEnabled != nil {
		return *m.ModifyClientLabelsActionEnabled
	}
	return false
}

type ApiGrrUser struct {
	Username         *string                    `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Settings         *flows.GUISettings         `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	InterfaceTraits  *ApiGrrUserInterfaceTraits `protobuf:"bytes,3,opt,name=interface_traits,json=interfaceTraits" json:"interface_traits,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ApiGrrUser) Reset()                    { *m = ApiGrrUser{} }
func (m *ApiGrrUser) String() string            { return proto.CompactTextString(m) }
func (*ApiGrrUser) ProtoMessage()               {}
func (*ApiGrrUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiGrrUser) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *ApiGrrUser) GetSettings() *flows.GUISettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ApiGrrUser) GetInterfaceTraits() *ApiGrrUserInterfaceTraits {
	if m != nil {
		return m.InterfaceTraits
	}
	return nil
}

type ApiNotificationReference struct {
	Type             *ApiNotificationReference_Type           `protobuf:"varint,1,opt,name=type,enum=ApiNotificationReference_Type" json:"type,omitempty"`
	Discovery        *ApiNotificationDiscoveryReference       `protobuf:"bytes,2,opt,name=discovery" json:"discovery,omitempty"`
	Hunt             *ApiNotificationHuntReference            `protobuf:"bytes,5,opt,name=hunt" json:"hunt,omitempty"`
	Cron             *ApiNotificationCronReference            `protobuf:"bytes,6,opt,name=cron" json:"cron,omitempty"`
	Flow             *ApiNotificationFlowReference            `protobuf:"bytes,7,opt,name=flow" json:"flow,omitempty"`
	Vfs              *ApiNotificationVfsReference             `protobuf:"bytes,8,opt,name=vfs" json:"vfs,omitempty"`
	ClientApproval   *ApiNotificationClientApprovalReference  `protobuf:"bytes,11,opt,name=client_approval,json=clientApproval" json:"client_approval,omitempty"`
	HuntApproval     *ApiNotificationHuntApprovalReference    `protobuf:"bytes,12,opt,name=hunt_approval,json=huntApproval" json:"hunt_approval,omitempty"`
	CronJobApproval  *ApiNotificationCronJobApprovalReference `protobuf:"bytes,13,opt,name=cron_job_approval,json=cronJobApproval" json:"cron_job_approval,omitempty"`
	Unknown          *ApiNotificationUnknownReference         `protobuf:"bytes,14,opt,name=unknown" json:"unknown,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *ApiNotificationReference) Reset()                    { *m = ApiNotificationReference{} }
func (m *ApiNotificationReference) String() string            { return proto.CompactTextString(m) }
func (*ApiNotificationReference) ProtoMessage()               {}
func (*ApiNotificationReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApiNotificationReference) GetType() ApiNotificationReference_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ApiNotificationReference_DISCOVERY
}

func (m *ApiNotificationReference) GetDiscovery() *ApiNotificationDiscoveryReference {
	if m != nil {
		return m.Discovery
	}
	return nil
}

func (m *ApiNotificationReference) GetHunt() *ApiNotificationHuntReference {
	if m != nil {
		return m.Hunt
	}
	return nil
}

func (m *ApiNotificationReference) GetCron() *ApiNotificationCronReference {
	if m != nil {
		return m.Cron
	}
	return nil
}

func (m *ApiNotificationReference) GetFlow() *ApiNotificationFlowReference {
	if m != nil {
		return m.Flow
	}
	return nil
}

func (m *ApiNotificationReference) GetVfs() *ApiNotificationVfsReference {
	if m != nil {
		return m.Vfs
	}
	return nil
}

func (m *ApiNotificationReference) GetClientApproval() *ApiNotificationClientApprovalReference {
	if m != nil {
		return m.ClientApproval
	}
	return nil
}

func (m *ApiNotificationReference) GetHuntApproval() *ApiNotificationHuntApprovalReference {
	if m != nil {
		return m.HuntApproval
	}
	return nil
}

func (m *ApiNotificationReference) GetCronJobApproval() *ApiNotificationCronJobApprovalReference {
	if m != nil {
		return m.CronJobApproval
	}
	return nil
}

func (m *ApiNotificationReference) GetUnknown() *ApiNotificationUnknownReference {
	if m != nil {
		return m.Unknown
	}
	return nil
}

type ApiNotificationDiscoveryReference struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationDiscoveryReference) Reset()         { *m = ApiNotificationDiscoveryReference{} }
func (m *ApiNotificationDiscoveryReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationDiscoveryReference) ProtoMessage()    {}
func (*ApiNotificationDiscoveryReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func (m *ApiNotificationDiscoveryReference) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

type ApiNotificationFileDownloadReference struct {
	Path             *string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationFileDownloadReference) Reset()         { *m = ApiNotificationFileDownloadReference{} }
func (m *ApiNotificationFileDownloadReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationFileDownloadReference) ProtoMessage()    {}
func (*ApiNotificationFileDownloadReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func (m *ApiNotificationFileDownloadReference) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type ApiNotificationHuntReference struct {
	HuntUrn          *string `protobuf:"bytes,1,opt,name=hunt_urn,json=huntUrn" json:"hunt_urn,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationHuntReference) Reset()                    { *m = ApiNotificationHuntReference{} }
func (m *ApiNotificationHuntReference) String() string            { return proto.CompactTextString(m) }
func (*ApiNotificationHuntReference) ProtoMessage()               {}
func (*ApiNotificationHuntReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApiNotificationHuntReference) GetHuntUrn() string {
	if m != nil && m.HuntUrn != nil {
		return *m.HuntUrn
	}
	return ""
}

type ApiNotificationCronReference struct {
	CronJobUrn       *string `protobuf:"bytes,1,opt,name=cron_job_urn,json=cronJobUrn" json:"cron_job_urn,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationCronReference) Reset()                    { *m = ApiNotificationCronReference{} }
func (m *ApiNotificationCronReference) String() string            { return proto.CompactTextString(m) }
func (*ApiNotificationCronReference) ProtoMessage()               {}
func (*ApiNotificationCronReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiNotificationCronReference) GetCronJobUrn() string {
	if m != nil && m.CronJobUrn != nil {
		return *m.CronJobUrn
	}
	return ""
}

type ApiNotificationFlowReference struct {
	ClientId         *string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FlowId           *string `protobuf:"bytes,3,opt,name=flow_id,json=flowId" json:"flow_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationFlowReference) Reset()                    { *m = ApiNotificationFlowReference{} }
func (m *ApiNotificationFlowReference) String() string            { return proto.CompactTextString(m) }
func (*ApiNotificationFlowReference) ProtoMessage()               {}
func (*ApiNotificationFlowReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApiNotificationFlowReference) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiNotificationFlowReference) GetFlowId() string {
	if m != nil && m.FlowId != nil {
		return *m.FlowId
	}
	return ""
}

type ApiNotificationVfsReference struct {
	VfsPath          *string `protobuf:"bytes,1,opt,name=vfs_path,json=vfsPath" json:"vfs_path,omitempty"`
	ClientId         *string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationVfsReference) Reset()                    { *m = ApiNotificationVfsReference{} }
func (m *ApiNotificationVfsReference) String() string            { return proto.CompactTextString(m) }
func (*ApiNotificationVfsReference) ProtoMessage()               {}
func (*ApiNotificationVfsReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiNotificationVfsReference) GetVfsPath() string {
	if m != nil && m.VfsPath != nil {
		return *m.VfsPath
	}
	return ""
}

func (m *ApiNotificationVfsReference) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

type ApiNotificationClientApprovalReference struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationClientApprovalReference) Reset() {
	*m = ApiNotificationClientApprovalReference{}
}
func (m *ApiNotificationClientApprovalReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationClientApprovalReference) ProtoMessage()    {}
func (*ApiNotificationClientApprovalReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

func (m *ApiNotificationClientApprovalReference) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiNotificationClientApprovalReference) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiNotificationClientApprovalReference) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiNotificationHuntApprovalReference struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationHuntApprovalReference) Reset()         { *m = ApiNotificationHuntApprovalReference{} }
func (m *ApiNotificationHuntApprovalReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationHuntApprovalReference) ProtoMessage()    {}
func (*ApiNotificationHuntApprovalReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13}
}

func (m *ApiNotificationHuntApprovalReference) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiNotificationHuntApprovalReference) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiNotificationHuntApprovalReference) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiNotificationCronJobApprovalReference struct {
	CronJobId        *string `protobuf:"bytes,1,opt,name=cron_job_id,json=cronJobId" json:"cron_job_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationCronJobApprovalReference) Reset() {
	*m = ApiNotificationCronJobApprovalReference{}
}
func (m *ApiNotificationCronJobApprovalReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationCronJobApprovalReference) ProtoMessage()    {}
func (*ApiNotificationCronJobApprovalReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14}
}

func (m *ApiNotificationCronJobApprovalReference) GetCronJobId() string {
	if m != nil && m.CronJobId != nil {
		return *m.CronJobId
	}
	return ""
}

func (m *ApiNotificationCronJobApprovalReference) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiNotificationCronJobApprovalReference) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiNotificationUnknownReference struct {
	SourceUrn        *string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn" json:"source_urn,omitempty"`
	SubjectUrn       *string `protobuf:"bytes,2,opt,name=subject_urn,json=subjectUrn" json:"subject_urn,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiNotificationUnknownReference) Reset()         { *m = ApiNotificationUnknownReference{} }
func (m *ApiNotificationUnknownReference) String() string { return proto.CompactTextString(m) }
func (*ApiNotificationUnknownReference) ProtoMessage()    {}
func (*ApiNotificationUnknownReference) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

func (m *ApiNotificationUnknownReference) GetSourceUrn() string {
	if m != nil && m.SourceUrn != nil {
		return *m.SourceUrn
	}
	return ""
}

func (m *ApiNotificationUnknownReference) GetSubjectUrn() string {
	if m != nil && m.SubjectUrn != nil {
		return *m.SubjectUrn
	}
	return ""
}

type ApiNotification struct {
	Timestamp        *uint64                   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string                   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Reference        *ApiNotificationReference `protobuf:"bytes,3,opt,name=reference" json:"reference,omitempty"`
	IsPending        *bool                     `protobuf:"varint,4,opt,name=is_pending,json=isPending" json:"is_pending,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ApiNotification) Reset()                    { *m = ApiNotification{} }
func (m *ApiNotification) String() string            { return proto.CompactTextString(m) }
func (*ApiNotification) ProtoMessage()               {}
func (*ApiNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ApiNotification) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApiNotification) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ApiNotification) GetReference() *ApiNotificationReference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *ApiNotification) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

type ApiCreateHuntApprovalArgs struct {
	HuntId           *string          `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	Approval         *ApiHuntApproval `protobuf:"bytes,2,opt,name=approval" json:"approval,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ApiCreateHuntApprovalArgs) Reset()                    { *m = ApiCreateHuntApprovalArgs{} }
func (m *ApiCreateHuntApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiCreateHuntApprovalArgs) ProtoMessage()               {}
func (*ApiCreateHuntApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ApiCreateHuntApprovalArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiCreateHuntApprovalArgs) GetApproval() *ApiHuntApproval {
	if m != nil {
		return m.Approval
	}
	return nil
}

type ApiGetHuntApprovalArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetHuntApprovalArgs) Reset()                    { *m = ApiGetHuntApprovalArgs{} }
func (m *ApiGetHuntApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetHuntApprovalArgs) ProtoMessage()               {}
func (*ApiGetHuntApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ApiGetHuntApprovalArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGetHuntApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGetHuntApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiGrantHuntApprovalArgs struct {
	HuntId           *string `protobuf:"bytes,1,opt,name=hunt_id,json=huntId" json:"hunt_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGrantHuntApprovalArgs) Reset()                    { *m = ApiGrantHuntApprovalArgs{} }
func (m *ApiGrantHuntApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGrantHuntApprovalArgs) ProtoMessage()               {}
func (*ApiGrantHuntApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ApiGrantHuntApprovalArgs) GetHuntId() string {
	if m != nil && m.HuntId != nil {
		return *m.HuntId
	}
	return ""
}

func (m *ApiGrantHuntApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGrantHuntApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiListHuntApprovalsArgs struct {
	Offset           *int64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Count            *int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApiListHuntApprovalsArgs) Reset()                    { *m = ApiListHuntApprovalsArgs{} }
func (m *ApiListHuntApprovalsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntApprovalsArgs) ProtoMessage()               {}
func (*ApiListHuntApprovalsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ApiListHuntApprovalsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListHuntApprovalsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiListHuntApprovalsResult struct {
	Items            []*ApiHuntApproval `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiListHuntApprovalsResult) Reset()                    { *m = ApiListHuntApprovalsResult{} }
func (m *ApiListHuntApprovalsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListHuntApprovalsResult) ProtoMessage()               {}
func (*ApiListHuntApprovalsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ApiListHuntApprovalsResult) GetItems() []*ApiHuntApproval {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiCreateCronJobApprovalArgs struct {
	CronJobId        *string             `protobuf:"bytes,1,opt,name=cron_job_id,json=cronJobId" json:"cron_job_id,omitempty"`
	Approval         *ApiCronJobApproval `protobuf:"bytes,2,opt,name=approval" json:"approval,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApiCreateCronJobApprovalArgs) Reset()                    { *m = ApiCreateCronJobApprovalArgs{} }
func (m *ApiCreateCronJobApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiCreateCronJobApprovalArgs) ProtoMessage()               {}
func (*ApiCreateCronJobApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ApiCreateCronJobApprovalArgs) GetCronJobId() string {
	if m != nil && m.CronJobId != nil {
		return *m.CronJobId
	}
	return ""
}

func (m *ApiCreateCronJobApprovalArgs) GetApproval() *ApiCronJobApproval {
	if m != nil {
		return m.Approval
	}
	return nil
}

type ApiGetCronJobApprovalArgs struct {
	CronJobId        *string `protobuf:"bytes,1,opt,name=cron_job_id,json=cronJobId" json:"cron_job_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetCronJobApprovalArgs) Reset()                    { *m = ApiGetCronJobApprovalArgs{} }
func (m *ApiGetCronJobApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetCronJobApprovalArgs) ProtoMessage()               {}
func (*ApiGetCronJobApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ApiGetCronJobApprovalArgs) GetCronJobId() string {
	if m != nil && m.CronJobId != nil {
		return *m.CronJobId
	}
	return ""
}

func (m *ApiGetCronJobApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGetCronJobApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiGrantCronJobApprovalArgs struct {
	CronJobId        *string `protobuf:"bytes,1,opt,name=cron_job_id,json=cronJobId" json:"cron_job_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGrantCronJobApprovalArgs) Reset()                    { *m = ApiGrantCronJobApprovalArgs{} }
func (m *ApiGrantCronJobApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGrantCronJobApprovalArgs) ProtoMessage()               {}
func (*ApiGrantCronJobApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ApiGrantCronJobApprovalArgs) GetCronJobId() string {
	if m != nil && m.CronJobId != nil {
		return *m.CronJobId
	}
	return ""
}

func (m *ApiGrantCronJobApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGrantCronJobApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiListCronJobApprovalsArgs struct {
	Offset           *int64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Count            *int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApiListCronJobApprovalsArgs) Reset()                    { *m = ApiListCronJobApprovalsArgs{} }
func (m *ApiListCronJobApprovalsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListCronJobApprovalsArgs) ProtoMessage()               {}
func (*ApiListCronJobApprovalsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ApiListCronJobApprovalsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListCronJobApprovalsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiListCronJobApprovalsResult struct {
	Items            []*ApiCronJobApproval `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ApiListCronJobApprovalsResult) Reset()                    { *m = ApiListCronJobApprovalsResult{} }
func (m *ApiListCronJobApprovalsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListCronJobApprovalsResult) ProtoMessage()               {}
func (*ApiListCronJobApprovalsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ApiListCronJobApprovalsResult) GetItems() []*ApiCronJobApproval {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiCreateClientApprovalArgs struct {
	ClientId         *string            `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Approval         *ApiClientApproval `protobuf:"bytes,2,opt,name=approval" json:"approval,omitempty"`
	KeepClientAlive  *bool              `protobuf:"varint,3,opt,name=keep_client_alive,json=keepClientAlive" json:"keep_client_alive,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiCreateClientApprovalArgs) Reset()                    { *m = ApiCreateClientApprovalArgs{} }
func (m *ApiCreateClientApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiCreateClientApprovalArgs) ProtoMessage()               {}
func (*ApiCreateClientApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ApiCreateClientApprovalArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiCreateClientApprovalArgs) GetApproval() *ApiClientApproval {
	if m != nil {
		return m.Approval
	}
	return nil
}

func (m *ApiCreateClientApprovalArgs) GetKeepClientAlive() bool {
	if m != nil && m.KeepClientAlive != nil {
		return *m.KeepClientAlive
	}
	return false
}

type ApiGetClientApprovalArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetClientApprovalArgs) Reset()                    { *m = ApiGetClientApprovalArgs{} }
func (m *ApiGetClientApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetClientApprovalArgs) ProtoMessage()               {}
func (*ApiGetClientApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ApiGetClientApprovalArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetClientApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGetClientApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiGrantClientApprovalArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ApprovalId       *string `protobuf:"bytes,2,opt,name=approval_id,json=approvalId" json:"approval_id,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGrantClientApprovalArgs) Reset()                    { *m = ApiGrantClientApprovalArgs{} }
func (m *ApiGrantClientApprovalArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGrantClientApprovalArgs) ProtoMessage()               {}
func (*ApiGrantClientApprovalArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ApiGrantClientApprovalArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGrantClientApprovalArgs) GetApprovalId() string {
	if m != nil && m.ApprovalId != nil {
		return *m.ApprovalId
	}
	return ""
}

func (m *ApiGrantClientApprovalArgs) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type ApiListClientApprovalsArgs struct {
	Offset           *int64                            `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Count            *int64                            `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	ClientId         *string                           `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	State            *ApiListClientApprovalsArgs_State `protobuf:"varint,4,opt,name=state,enum=ApiListClientApprovalsArgs_State" json:"state,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *ApiListClientApprovalsArgs) Reset()                    { *m = ApiListClientApprovalsArgs{} }
func (m *ApiListClientApprovalsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListClientApprovalsArgs) ProtoMessage()               {}
func (*ApiListClientApprovalsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ApiListClientApprovalsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListClientApprovalsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListClientApprovalsArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiListClientApprovalsArgs) GetState() ApiListClientApprovalsArgs_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiListClientApprovalsArgs_ANY
}

type ApiListClientApprovalsResult struct {
	Items            []*ApiClientApproval `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApiListClientApprovalsResult) Reset()                    { *m = ApiListClientApprovalsResult{} }
func (m *ApiListClientApprovalsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListClientApprovalsResult) ProtoMessage()               {}
func (*ApiListClientApprovalsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ApiListClientApprovalsResult) GetItems() []*ApiClientApproval {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiListPendingGlobalNotificationsResult struct {
	Items            []*jobs.GlobalNotification `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ApiListPendingGlobalNotificationsResult) Reset() {
	*m = ApiListPendingGlobalNotificationsResult{}
}
func (m *ApiListPendingGlobalNotificationsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListPendingGlobalNotificationsResult) ProtoMessage()    {}
func (*ApiListPendingGlobalNotificationsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32}
}

func (m *ApiListPendingGlobalNotificationsResult) GetItems() []*jobs.GlobalNotification {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiDeletePendingGlobalNotificationArgs struct {
	Type             *jobs.GlobalNotification_Type `protobuf:"varint,1,opt,name=type,enum=GlobalNotification_Type" json:"type,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ApiDeletePendingGlobalNotificationArgs) Reset() {
	*m = ApiDeletePendingGlobalNotificationArgs{}
}
func (m *ApiDeletePendingGlobalNotificationArgs) String() string { return proto.CompactTextString(m) }
func (*ApiDeletePendingGlobalNotificationArgs) ProtoMessage()    {}
func (*ApiDeletePendingGlobalNotificationArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33}
}

func (m *ApiDeletePendingGlobalNotificationArgs) GetType() jobs.GlobalNotification_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return jobs.GlobalNotification_INFO
}

type ApiGetPendingUserNotificationsCountResult struct {
	Count            *int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApiGetPendingUserNotificationsCountResult) Reset() {
	*m = ApiGetPendingUserNotificationsCountResult{}
}
func (m *ApiGetPendingUserNotificationsCountResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetPendingUserNotificationsCountResult) ProtoMessage()    {}
func (*ApiGetPendingUserNotificationsCountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{34}
}

func (m *ApiGetPendingUserNotificationsCountResult) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ApiDeletePendingUserNotificationArgs struct {
	Timestamp        *uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiDeletePendingUserNotificationArgs) Reset()         { *m = ApiDeletePendingUserNotificationArgs{} }
func (m *ApiDeletePendingUserNotificationArgs) String() string { return proto.CompactTextString(m) }
func (*ApiDeletePendingUserNotificationArgs) ProtoMessage()    {}
func (*ApiDeletePendingUserNotificationArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{35}
}

func (m *ApiDeletePendingUserNotificationArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiListAndResetUserNotificationsArgs struct {
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListAndResetUserNotificationsArgs) Reset()         { *m = ApiListAndResetUserNotificationsArgs{} }
func (m *ApiListAndResetUserNotificationsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListAndResetUserNotificationsArgs) ProtoMessage()    {}
func (*ApiListAndResetUserNotificationsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{36}
}

func (m *ApiListAndResetUserNotificationsArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListAndResetUserNotificationsArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListAndResetUserNotificationsArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

type ApiListAndResetUserNotificationsResult struct {
	Items            []*ApiNotification `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	TotalCount       *int64             `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiListAndResetUserNotificationsResult) Reset() {
	*m = ApiListAndResetUserNotificationsResult{}
}
func (m *ApiListAndResetUserNotificationsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListAndResetUserNotificationsResult) ProtoMessage()    {}
func (*ApiListAndResetUserNotificationsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{37}
}

func (m *ApiListAndResetUserNotificationsResult) GetItems() []*ApiNotification {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ApiListAndResetUserNotificationsResult) GetTotalCount() int64 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type ApiListPendingUserNotificationsArgs struct {
	Timestamp        *uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListPendingUserNotificationsArgs) Reset()         { *m = ApiListPendingUserNotificationsArgs{} }
func (m *ApiListPendingUserNotificationsArgs) String() string { return proto.CompactTextString(m) }
func (*ApiListPendingUserNotificationsArgs) ProtoMessage()    {}
func (*ApiListPendingUserNotificationsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{38}
}

func (m *ApiListPendingUserNotificationsArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiListPendingUserNotificationsResult struct {
	Items            []*ApiNotification `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApiListPendingUserNotificationsResult) Reset()         { *m = ApiListPendingUserNotificationsResult{} }
func (m *ApiListPendingUserNotificationsResult) String() string { return proto.CompactTextString(m) }
func (*ApiListPendingUserNotificationsResult) ProtoMessage()    {}
func (*ApiListPendingUserNotificationsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{39}
}

func (m *ApiListPendingUserNotificationsResult) GetItems() []*ApiNotification {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiHuntApproval)(nil), "ApiHuntApproval")
	proto.RegisterType((*ApiCronJobApproval)(nil), "ApiCronJobApproval")
	proto.RegisterType((*ApiClientApproval)(nil), "ApiClientApproval")
	proto.RegisterType((*ApiGrrUserInterfaceTraits)(nil), "ApiGrrUserInterfaceTraits")
	proto.RegisterType((*ApiGrrUser)(nil), "ApiGrrUser")
	proto.RegisterType((*ApiNotificationReference)(nil), "ApiNotificationReference")
	proto.RegisterType((*ApiNotificationDiscoveryReference)(nil), "ApiNotificationDiscoveryReference")
	proto.RegisterType((*ApiNotificationFileDownloadReference)(nil), "ApiNotificationFileDownloadReference")
	proto.RegisterType((*ApiNotificationHuntReference)(nil), "ApiNotificationHuntReference")
	proto.RegisterType((*ApiNotificationCronReference)(nil), "ApiNotificationCronReference")
	proto.RegisterType((*ApiNotificationFlowReference)(nil), "ApiNotificationFlowReference")
	proto.RegisterType((*ApiNotificationVfsReference)(nil), "ApiNotificationVfsReference")
	proto.RegisterType((*ApiNotificationClientApprovalReference)(nil), "ApiNotificationClientApprovalReference")
	proto.RegisterType((*ApiNotificationHuntApprovalReference)(nil), "ApiNotificationHuntApprovalReference")
	proto.RegisterType((*ApiNotificationCronJobApprovalReference)(nil), "ApiNotificationCronJobApprovalReference")
	proto.RegisterType((*ApiNotificationUnknownReference)(nil), "ApiNotificationUnknownReference")
	proto.RegisterType((*ApiNotification)(nil), "ApiNotification")
	proto.RegisterType((*ApiCreateHuntApprovalArgs)(nil), "ApiCreateHuntApprovalArgs")
	proto.RegisterType((*ApiGetHuntApprovalArgs)(nil), "ApiGetHuntApprovalArgs")
	proto.RegisterType((*ApiGrantHuntApprovalArgs)(nil), "ApiGrantHuntApprovalArgs")
	proto.RegisterType((*ApiListHuntApprovalsArgs)(nil), "ApiListHuntApprovalsArgs")
	proto.RegisterType((*ApiListHuntApprovalsResult)(nil), "ApiListHuntApprovalsResult")
	proto.RegisterType((*ApiCreateCronJobApprovalArgs)(nil), "ApiCreateCronJobApprovalArgs")
	proto.RegisterType((*ApiGetCronJobApprovalArgs)(nil), "ApiGetCronJobApprovalArgs")
	proto.RegisterType((*ApiGrantCronJobApprovalArgs)(nil), "ApiGrantCronJobApprovalArgs")
	proto.RegisterType((*ApiListCronJobApprovalsArgs)(nil), "ApiListCronJobApprovalsArgs")
	proto.RegisterType((*ApiListCronJobApprovalsResult)(nil), "ApiListCronJobApprovalsResult")
	proto.RegisterType((*ApiCreateClientApprovalArgs)(nil), "ApiCreateClientApprovalArgs")
	proto.RegisterType((*ApiGetClientApprovalArgs)(nil), "ApiGetClientApprovalArgs")
	proto.RegisterType((*ApiGrantClientApprovalArgs)(nil), "ApiGrantClientApprovalArgs")
	proto.RegisterType((*ApiListClientApprovalsArgs)(nil), "ApiListClientApprovalsArgs")
	proto.RegisterType((*ApiListClientApprovalsResult)(nil), "ApiListClientApprovalsResult")
	proto.RegisterType((*ApiListPendingGlobalNotificationsResult)(nil), "ApiListPendingGlobalNotificationsResult")
	proto.RegisterType((*ApiDeletePendingGlobalNotificationArgs)(nil), "ApiDeletePendingGlobalNotificationArgs")
	proto.RegisterType((*ApiGetPendingUserNotificationsCountResult)(nil), "ApiGetPendingUserNotificationsCountResult")
	proto.RegisterType((*ApiDeletePendingUserNotificationArgs)(nil), "ApiDeletePendingUserNotificationArgs")
	proto.RegisterType((*ApiListAndResetUserNotificationsArgs)(nil), "ApiListAndResetUserNotificationsArgs")
	proto.RegisterType((*ApiListAndResetUserNotificationsResult)(nil), "ApiListAndResetUserNotificationsResult")
	proto.RegisterType((*ApiListPendingUserNotificationsArgs)(nil), "ApiListPendingUserNotificationsArgs")
	proto.RegisterType((*ApiListPendingUserNotificationsResult)(nil), "ApiListPendingUserNotificationsResult")
	proto.RegisterEnum("ApiNotificationReference_Type", ApiNotificationReference_Type_name, ApiNotificationReference_Type_value)
	proto.RegisterEnum("ApiListClientApprovalsArgs_State", ApiListClientApprovalsArgs_State_name, ApiListClientApprovalsArgs_State_value)
}

func init() { proto.RegisterFile("grr/proto/api/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5a, 0xcd, 0x8f, 0x1b, 0xc7,
	0x95, 0x37, 0x39, 0x9f, 0x2c, 0x6a, 0xbe, 0x4a, 0x96, 0x4d, 0xd1, 0xfa, 0x28, 0xd3, 0xfa, 0x18,
	0xd9, 0xe3, 0x96, 0x3d, 0x6b, 0xef, 0xae, 0xa5, 0x5d, 0x59, 0xe4, 0x8c, 0x46, 0xa2, 0x34, 0x9a,
	0xd1, 0xf6, 0xcc, 0xc8, 0xb6, 0xe0, 0x5d, 0x6e, 0xb1, 0xbb, 0x38, 0x2c, 0x89, 0xec, 0xa6, 0xbb,
	0x8a, 0x33, 0x1e, 0x27, 0x41, 0xec, 0x4b, 0x9c, 0x93, 0x13, 0xc0, 0x40, 0x72, 0x72, 0x0e, 0x41,
	0xfe, 0x80, 0x1c, 0x72, 0xf1, 0x3d, 0x97, 0x38, 0xb9, 0x04, 0x41, 0x10, 0x20, 0xa7, 0xc0, 0xc9,
	0x29, 0x08, 0x90, 0x73, 0x80, 0x1c, 0x82, 0x7a, 0x55, 0xdd, 0xcd, 0xee, 0xe6, 0x8c, 0xac, 0x48,
	0x8e, 0x61, 0x40, 0x47, 0x76, 0xfd, 0xde, 0x7b, 0xbf, 0x7a, 0xf5, 0xde, 0xab, 0x57, 0x55, 0x44,
	0xa5, 0xed, 0x20, 0x38, 0xdf, 0x0b, 0x7c, 0xe9, 0x9f, 0xa7, 0x3d, 0x7e, 0xbe, 0x2f, 0x58, 0x60,
	0xc1, 0xcf, 0x72, 0x6a, 0xc4, 0x09, 0x7c, 0x6f, 0xf8, 0x48, 0xbb, 0xef, 0x49, 0x33, 0x52, 0x4e,
	0xc9, 0x74, 0x38, 0x8b, 0xc6, 0x8e, 0xc4, 0x63, 0xad, 0x8e, 0xbf, 0x2b, 0xcc, 0xe7, 0x27, 0xe3,
	0xcf, 0x77, 0xfd, 0xa6, 0xc8, 0x9a, 0x10, 0xac, 0x4b, 0x3d, 0xc9, 0x1d, 0x3d, 0x52, 0xf9, 0xeb,
	0x04, 0x9a, 0xa9, 0xf6, 0xf8, 0xb5, 0xbe, 0x27, 0xab, 0xbd, 0x5e, 0xe0, 0xef, 0xd0, 0x0e, 0xbe,
	0x8b, 0x26, 0x44, 0xbf, 0x79, 0x97, 0x39, 0xb2, 0x94, 0x23, 0xb9, 0xf9, 0xe2, 0xe2, 0xa4, 0x65,
	0x20, 0xb5, 0x95, 0xcf, 0xff, 0xfe, 0xc7, 0x9f, 0xe7, 0x2e, 0xe3, 0x4b, 0x55, 0xa2, 0x78, 0x12,
	0xd9, 0xa6, 0x92, 0xb4, 0xa9, 0x20, 0xd2, 0x27, 0x4d, 0x46, 0xa8, 0xe3, 0x30, 0x21, 0x98, 0x4b,
	0x68, 0x4b, 0xb2, 0x80, 0xc8, 0x36, 0x17, 0x84, 0x1a, 0xb5, 0x84, 0x0b, 0xb2, 0x1d, 0x50, 0x4f,
	0x32, 0xd7, 0xb2, 0x43, 0x03, 0xb8, 0x8f, 0xf2, 0xdc, 0x2d, 0x4d, 0x92, 0xdc, 0x7c, 0xa1, 0xc6,
	0x40, 0x79, 0x03, 0xff, 0x6f, 0x35, 0x12, 0x71, 0x2d, 0x52, 0x1d, 0x90, 0xe7, 0x2e, 0xf3, 0x24,
	0x6f, 0x71, 0xe6, 0x92, 0xe6, 0x1e, 0x91, 0x6d, 0xa6, 0x59, 0x70, 0x77, 0x81, 0x04, 0xec, 0x9d,
	0x3e, 0x13, 0xd2, 0x0f, 0xce, 0x0a, 0xa2, 0xdc, 0xee, 0xd1, 0x2e, 0x23, 0xd4, 0x73, 0x01, 0x45,
	0x07, 0x14, 0xda, 0x79, 0xee, 0xe2, 0xcb, 0x68, 0x3c, 0x60, 0x54, 0xf8, 0x5e, 0x29, 0x0f, 0xa6,
	0xe7, 0xc1, 0x74, 0x05, 0x93, 0x2a, 0xd1, 0xdf, 0x49, 0xcb, 0x0f, 0xcc, 0x74, 0xb8, 0xb7, 0x1d,
	0x99, 0xb2, 0x6c, 0x23, 0x87, 0xbf, 0x81, 0x26, 0xb9, 0x68, 0xec, 0xd0, 0x0e, 0x77, 0x4b, 0x23,
	0x24, 0x37, 0x3f, 0x59, 0xfb, 0x7f, 0xd0, 0x71, 0x07, 0xbf, 0x59, 0x6f, 0x91, 0xcd, 0xa0, 0xcf,
	0x16, 0xb2, 0xf3, 0x17, 0x92, 0x77, 0x3a, 0x04, 0x84, 0x2c, 0x52, 0x6f, 0x91, 0x15, 0xda, 0x11,
	0x80, 0x63, 0x1e, 0xe1, 0x92, 0xec, 0x52, 0xe1, 0x9d, 0x95, 0x46, 0x82, 0xb9, 0xc4, 0x0f, 0xc8,
	0xb6, 0x2f, 0x09, 0x7b, 0xb7, 0xc7, 0x03, 0xf0, 0x1a, 0x17, 0xb7, 0x95, 0x2c, 0xfe, 0x49, 0x0e,
	0xcd, 0x86, 0xd6, 0x1b, 0x5d, 0x26, 0x04, 0xdd, 0x66, 0xa5, 0x51, 0x98, 0xc9, 0x7b, 0xc0, 0x42,
	0xe2, 0xa0, 0xde, 0x22, 0x21, 0x44, 0x99, 0x36, 0xa6, 0xd2, 0x52, 0x64, 0x57, 0x31, 0x72, 0x7c,
	0x4f, 0x52, 0xee, 0x11, 0x4a, 0xda, 0xfd, 0x2e, 0xf5, 0x5e, 0x0c, 0x18, 0x75, 0x69, 0xb3, 0xc3,
	0x88, 0xcb, 0x84, 0x13, 0xf0, 0x9e, 0xe4, 0xbe, 0x47, 0xfc, 0x16, 0xd9, 0x6d, 0xef, 0xa5, 0xfc,
	0x29, 0x88, 0xe7, 0x4b, 0x33, 0x23, 0x7b, 0xda, 0xf0, 0xbb, 0xa9, 0x75, 0xe3, 0x00, 0x4d, 0x7b,
	0xbe, 0x5e, 0xaf, 0x86, 0x5a, 0x13, 0x51, 0x1a, 0x23, 0x23, 0xf3, 0x85, 0xda, 0x0d, 0xe0, 0x78,
	0x05, 0x2f, 0x5d, 0xb5, 0x6d, 0x58, 0x2c, 0xa1, 0x03, 0x09, 0xb8, 0x34, 0x19, 0x09, 0x85, 0x08,
	0x6d, 0xfa, 0x7d, 0x99, 0xb4, 0xd8, 0x64, 0x6a, 0x3d, 0xcc, 0x6a, 0x2b, 0xa7, 0x4c, 0x85, 0xe8,
	0x2d, 0xa5, 0x08, 0x7f, 0x37, 0x87, 0x30, 0xeb, 0x52, 0xde, 0x69, 0x38, 0x4e, 0x83, 0xba, 0x6e,
	0xa0, 0x02, 0x52, 0x94, 0xc6, 0xc1, 0xf0, 0x1d, 0x30, 0xbc, 0x89, 0xed, 0x55, 0x2e, 0xa4, 0x9a,
	0x10, 0x20, 0x21, 0x60, 0x5c, 0x15, 0xc2, 0x82, 0x79, 0x2e, 0xa1, 0xc6, 0xbe, 0x43, 0x61, 0xda,
	0xd2, 0x8f, 0x68, 0x0c, 0xae, 0x66, 0x86, 0xc7, 0x2c, 0xe8, 0x5a, 0x72, 0xaa, 0xa1, 0x4d, 0xfc,
	0x71, 0x0e, 0x15, 0xcc, 0x5a, 0x06, 0xa2, 0x34, 0x01, 0x0c, 0xfa, 0xc0, 0xc0, 0xc7, 0xdd, 0x90,
	0x41, 0xec, 0x82, 0xdd, 0xb6, 0x1f, 0x26, 0x48, 0xd2, 0x96, 0x45, 0xd6, 0x7c, 0xc9, 0x2e, 0xe8,
	0x8f, 0x1d, 0x25, 0x47, 0x3b, 0xbb, 0x74, 0x4f, 0x10, 0xee, 0x39, 0x9d, 0xbe, 0xcb, 0x04, 0x78,
	0xc8, 0x0f, 0xf8, 0x36, 0xf7, 0x68, 0x27, 0xa6, 0x18, 0xa5, 0x84, 0x65, 0xc7, 0x3c, 0x2a, 0x1f,
	0x4c, 0x22, 0x5c, 0xed, 0xf1, 0xa5, 0xc0, 0xf7, 0xae, 0xfb, 0xcd, 0x28, 0xe9, 0xdf, 0x49, 0x27,
	0x7d, 0xd1, 0x8a, 0x51, 0xb5, 0xeb, 0x40, 0x7b, 0x19, 0xd7, 0xaa, 0x44, 0x55, 0x2e, 0x72, 0xd7,
	0x6f, 0x3e, 0x7c, 0xee, 0xef, 0x0d, 0xe4, 0x3e, 0x07, 0x03, 0x0e, 0xa6, 0x0f, 0x90, 0xfb, 0x11,
	0x93, 0x07, 0xcf, 0xff, 0xe5, 0x54, 0xfe, 0x2f, 0x80, 0xf9, 0x33, 0xf8, 0xd4, 0x01, 0xf9, 0x1f,
	0x9a, 0x7b, 0x5c, 0x03, 0x1e, 0xd7, 0x80, 0xaf, 0x79, 0x0d, 0xf8, 0xdb, 0x04, 0x9a, 0x53, 0xd9,
	0x0d, 0x0d, 0x45, 0x54, 0x02, 0xbc, 0x74, 0x09, 0x40, 0x56, 0x04, 0xaa, 0x5d, 0x03, 0xd2, 0x35,
	0x7c, 0xb9, 0x4a, 0x74, 0x1f, 0xf2, 0xf0, 0xf9, 0xbf, 0x3b, 0x90, 0xff, 0xdb, 0xa0, 0x9e, 0xe2,
	0xc6, 0x83, 0xe4, 0xbf, 0xe6, 0xf1, 0xe0, 0xd9, 0x5f, 0x4b, 0x65, 0xff, 0xf3, 0x60, 0xfc, 0x14,
	0xae, 0x1c, 0x94, 0xfd, 0xba, 0xf9, 0x7a, 0x9c, 0xfb, 0x8f, 0x73, 0xff, 0xeb, 0x9d, 0xfb, 0xbf,
	0x28, 0xa0, 0xa3, 0xd5, 0x1e, 0xbf, 0x1a, 0x04, 0xca, 0x61, 0x75, 0x4f, 0xb2, 0xa0, 0x45, 0x1d,
	0xb6, 0x19, 0x50, 0x2e, 0x05, 0xbe, 0x80, 0xca, 0x6a, 0x9f, 0x6b, 0xa8, 0xc3, 0x43, 0xc3, 0xa3,
	0x3b, 0x0d, 0x2e, 0x59, 0xb7, 0xc1, 0x3c, 0x15, 0x0d, 0x2e, 0x94, 0x85, 0x49, 0xfb, 0x29, 0x47,
	0x77, 0x05, 0x62, 0x8d, 0xee, 0xd4, 0x25, 0xeb, 0x5e, 0xd1, 0xa3, 0xb8, 0x86, 0x4e, 0x38, 0x01,
	0xa3, 0x92, 0x35, 0x42, 0x15, 0x0d, 0xea, 0x28, 0x1f, 0x46, 0xf2, 0x79, 0x90, 0x2f, 0x6b, 0x54,
	0xd8, 0x81, 0x00, 0x24, 0xd4, 0x71, 0x19, 0x1d, 0x57, 0x7d, 0x76, 0xa3, 0x4b, 0x3d, 0xba, 0xcd,
	0x82, 0x2c, 0x05, 0xc8, 0x35, 0xfb, 0xa8, 0x02, 0xdd, 0xd4, 0x98, 0x14, 0x8b, 0x8b, 0xc8, 0xe8,
	0x6f, 0x80, 0xa2, 0x14, 0x83, 0x51, 0x10, 0x7f, 0x5a, 0x23, 0xe0, 0xd4, 0x93, 0x30, 0xbf, 0x82,
	0x88, 0x68, 0xfb, 0xbb, 0x0d, 0x21, 0xa9, 0xe4, 0x42, 0x72, 0x67, 0x88, 0x13, 0xc6, 0x40, 0xc5,
	0x31, 0x85, 0xdb, 0x88, 0x60, 0x29, 0x12, 0x37, 0xd0, 0x73, 0x42, 0xd2, 0x40, 0x36, 0xb6, 0x3b,
	0x7e, 0x93, 0x76, 0x1a, 0x70, 0x44, 0xcb, 0xaa, 0x1a, 0x07, 0x55, 0x27, 0x00, 0x7a, 0x15, 0x90,
	0x2b, 0x0a, 0x98, 0x52, 0x76, 0x09, 0x1d, 0x13, 0x2c, 0xd8, 0x61, 0x41, 0xa3, 0xe3, 0x53, 0x37,
	0xab, 0x65, 0x02, 0xb4, 0x94, 0x34, 0x66, 0xd5, 0xa7, 0x6e, 0x4a, 0x7e, 0x05, 0x11, 0xed, 0xce,
	0x46, 0x93, 0x7b, 0x34, 0xe0, 0x6c, 0x08, 0x93, 0x82, 0x9e, 0x94, 0xc6, 0xd5, 0x0c, 0x2c, 0xa5,
	0xe7, 0x75, 0x74, 0xac, 0xdf, 0x03, 0x0a, 0xa0, 0x67, 0x2f, 0xed, 0x5b, 0xa4, 0x97, 0x46, 0x63,
	0x40, 0xc7, 0x5e, 0xd2, 0xbb, 0xaf, 0xa1, 0xa3, 0x82, 0x49, 0xc9, 0xbd, 0xed, 0x21, 0x0c, 0x8a,
	0x3a, 0xb6, 0x42, 0x40, 0xca, 0xf6, 0x35, 0xf4, 0x2c, 0x0d, 0x24, 0x6f, 0x51, 0xe7, 0x80, 0xd8,
	0x38, 0x04, 0x2a, 0x8e, 0x87, 0xc0, 0xe1, 0xf1, 0xb1, 0x84, 0x4e, 0x98, 0x59, 0x44, 0x0a, 0x53,
	0xf3, 0x98, 0x02, 0x35, 0xcf, 0x68, 0x54, 0xd5, 0x80, 0x92, 0x33, 0xa9, 0xa2, 0xe3, 0x82, 0xd1,
	0xc0, 0x69, 0x37, 0xf4, 0xbe, 0x20, 0xd2, 0x3a, 0xa6, 0x75, 0xa4, 0x6b, 0x90, 0xde, 0x42, 0x45,
	0x52, 0xc5, 0x1d, 0xf4, 0x42, 0x33, 0xf0, 0x77, 0x05, 0x6b, 0xec, 0xf0, 0x40, 0xf6, 0x55, 0x90,
	0xf0, 0x0e, 0x6b, 0x88, 0x3d, 0xa1, 0xa6, 0x94, 0x99, 0xdb, 0x0c, 0x28, 0x3c, 0xad, 0x45, 0x6e,
	0x6b, 0x89, 0x15, 0xde, 0x61, 0x1b, 0x80, 0x4f, 0xcd, 0xb1, 0x8e, 0x2a, 0x3a, 0xfc, 0x34, 0x3b,
	0x08, 0xbf, 0xac, 0xca, 0x59, 0xed, 0x2e, 0x40, 0x6a, 0x8a, 0x2a, 0xfa, 0x52, 0xaa, 0x6e, 0xa2,
	0x53, 0x26, 0x78, 0x06, 0x74, 0x0d, 0x59, 0xbe, 0x39, 0x50, 0x76, 0x52, 0x63, 0x63, 0x6d, 0xe9,
	0x75, 0x5c, 0x45, 0xcf, 0x75, 0x7d, 0x97, 0xb7, 0xf6, 0x42, 0x75, 0x1d, 0xda, 0x64, 0x9d, 0x8c,
	0xfb, 0xb0, 0xd1, 0x06, 0x50, 0xad, 0x6d, 0x15, 0x80, 0x09, 0x1f, 0x56, 0x3e, 0xc9, 0x23, 0x14,
	0xd7, 0x32, 0xfc, 0x1a, 0x9a, 0x0c, 0x37, 0x7f, 0x28, 0x55, 0x85, 0xda, 0x71, 0x28, 0xb7, 0x4f,
	0xe3, 0x23, 0x9b, 0x6d, 0x46, 0xa0, 0x29, 0xf0, 0x5b, 0x50, 0x2d, 0xe1, 0x66, 0xc6, 0x8e, 0xe0,
	0x78, 0x09, 0x4d, 0x86, 0x91, 0x07, 0x55, 0xaa, 0xb8, 0x78, 0xc8, 0xba, 0xba, 0x55, 0xdf, 0x30,
	0xdf, 0x6a, 0x47, 0x41, 0xd1, 0x61, 0x3c, 0xa7, 0x0c, 0x91, 0xad, 0x3a, 0x09, 0xd1, 0x96, 0x1d,
	0x09, 0xe2, 0x8f, 0xd4, 0xb6, 0x1c, 0x16, 0xd4, 0x86, 0x84, 0x8a, 0x0a, 0x05, 0xab, 0xb8, 0x58,
	0xb6, 0xf6, 0xad, 0xb9, 0xb5, 0xab, 0xa0, 0xbb, 0x8a, 0x5f, 0x57, 0x83, 0x67, 0x55, 0x59, 0x37,
	0xe3, 0x44, 0xab, 0x20, 0xf3, 0xbb, 0x6a, 0x77, 0x94, 0x6d, 0xb6, 0x47, 0x1c, 0xea, 0x41, 0x5f,
	0xe3, 0x50, 0xd5, 0x29, 0xb8, 0x3e, 0xe1, 0x1e, 0xcc, 0x67, 0xab, 0x7e, 0xce, 0xb2, 0x67, 0x78,
	0x52, 0x73, 0xe5, 0xb3, 0x09, 0x54, 0xaa, 0xf6, 0xf8, 0xda, 0xc0, 0x7e, 0x66, 0xb3, 0x16, 0x0b,
	0x98, 0xe7, 0x30, 0xbc, 0x88, 0x46, 0xe5, 0x5e, 0x4f, 0x7b, 0x6a, 0x7a, 0xf1, 0x84, 0xb5, 0x1f,
	0xd0, 0xda, 0xdc, 0xeb, 0x31, 0x1b, 0xb0, 0xf8, 0x32, 0x2a, 0xb8, 0x5c, 0x38, 0x6a, 0x27, 0xd9,
	0x33, 0x7e, 0xaa, 0xa4, 0x05, 0x97, 0x43, 0x40, 0xa4, 0xc1, 0x8e, 0x85, 0xf0, 0xcb, 0x68, 0x54,
	0xd5, 0x65, 0xa8, 0xa2, 0xc5, 0xc5, 0xe3, 0x69, 0x61, 0x55, 0x92, 0x63, 0x39, 0x80, 0x2a, 0x11,
	0xb5, 0xa1, 0x40, 0xb5, 0x1c, 0x22, 0xa2, 0xf6, 0x91, 0x01, 0x11, 0x05, 0x55, 0x22, 0x2a, 0x4e,
	0xa1, 0x34, 0x0e, 0x11, 0x51, 0x91, 0x39, 0x20, 0xa2, 0xa0, 0xd8, 0x42, 0x23, 0x3b, 0x2d, 0x01,
	0xed, 0x68, 0x71, 0xf1, 0x58, 0x5a, 0xe2, 0x76, 0x4b, 0xc4, 0x02, 0x0a, 0x88, 0x6f, 0xa1, 0x19,
	0x13, 0xc2, 0xe1, 0x86, 0x0b, 0x25, 0xac, 0xb8, 0x78, 0x36, 0x43, 0x30, 0xd1, 0x66, 0xc7, 0x6a,
	0xa6, 0x9d, 0x64, 0xff, 0x7d, 0x1d, 0x4d, 0xe9, 0x2d, 0x2b, 0xd4, 0x77, 0x08, 0xf4, 0x9d, 0x1e,
	0xe6, 0xa3, 0xac, 0xb6, 0x43, 0xed, 0xc1, 0x3b, 0xbc, 0x4d, 0x34, 0x17, 0x6f, 0xc2, 0xa1, 0xbe,
	0x29, 0xd0, 0x37, 0x3f, 0xcc, 0x81, 0x03, 0x57, 0x01, 0xb1, 0xca, 0x19, 0x27, 0x75, 0x49, 0x70,
	0x01, 0x4d, 0xf4, 0xbd, 0x7b, 0x9e, 0xbf, 0xeb, 0x41, 0x81, 0x2b, 0x2e, 0x92, 0xb4, 0xae, 0x2d,
	0x3d, 0x1c, 0xeb, 0x08, 0x05, 0x2a, 0x3f, 0xcd, 0xa3, 0x51, 0x15, 0x49, 0xf8, 0x04, 0x2a, 0x2c,
	0xd7, 0x37, 0x96, 0xd6, 0x6f, 0x5f, 0xb1, 0xdf, 0x9a, 0x7d, 0xa2, 0x3c, 0xf3, 0xe7, 0x4f, 0x7f,
	0xf9, 0x69, 0xae, 0x10, 0x45, 0x0d, 0x7e, 0x12, 0x8d, 0x5e, 0xdb, 0x5a, 0xdb, 0x9c, 0x1d, 0x29,
	0x23, 0x18, 0x1a, 0x55, 0xf3, 0xc5, 0x25, 0x34, 0xba, 0x64, 0xaf, 0xaf, 0xcd, 0x8e, 0x96, 0xa7,
	0xe1, 0xeb, 0xe4, 0x92, 0x39, 0x8e, 0x2b, 0xfc, 0xca, 0xea, 0xfa, 0x1b, 0xb3, 0x63, 0x21, 0x5e,
	0xad, 0x2e, 0xae, 0xa0, 0x91, 0xdb, 0x2b, 0x1b, 0xb3, 0xe3, 0xe5, 0xa3, 0xf0, 0xf1, 0xb0, 0x29,
	0x99, 0x44, 0x15, 0x59, 0xa2, 0x8b, 0x2c, 0x7e, 0x1e, 0xcd, 0x2c, 0xad, 0xd6, 0xaf, 0xac, 0x6d,
	0x36, 0xaa, 0xb7, 0x6e, 0xd9, 0xeb, 0xb7, 0xab, 0xab, 0xb3, 0xa8, 0x7c, 0x04, 0xf0, 0x33, 0x7a,
	0xd1, 0xa2, 0x66, 0x0a, 0x9f, 0x41, 0x53, 0x8a, 0x55, 0x8c, 0x2c, 0x96, 0x0f, 0x03, 0x72, 0x4a,
	0xd1, 0x8b, 0x71, 0x16, 0x9a, 0x53, 0x3c, 0x1b, 0xd7, 0xd7, 0x6b, 0x31, 0xf6, 0x50, 0xf9, 0x69,
	0xc0, 0xce, 0x85, 0xa4, 0x63, 0x7c, 0x19, 0x4d, 0x6c, 0xad, 0xdd, 0x58, 0x5b, 0x7f, 0x63, 0x6d,
	0x76, 0xaa, 0x3c, 0x05, 0xa8, 0x09, 0xe3, 0xc4, 0x0b, 0x87, 0x7e, 0xaf, 0x0a, 0xc3, 0x38, 0x86,
	0xdc, 0xab, 0x7c, 0x0b, 0x3d, 0x7b, 0xdf, 0x4c, 0xc3, 0x6f, 0xa2, 0x82, 0x89, 0x4a, 0xee, 0x9a,
	0x1a, 0x78, 0x11, 0xca, 0xcb, 0xab, 0xa8, 0x18, 0x1d, 0xe6, 0xea, 0x2e, 0x3e, 0xb3, 0x19, 0x1f,
	0xa0, 0xa0, 0xaf, 0x4c, 0xf4, 0xbc, 0xaa, 0xf9, 0x54, 0x3d, 0xaf, 0x65, 0x4f, 0x3a, 0x46, 0xa2,
	0x72, 0x0f, 0x9d, 0x4a, 0x67, 0x11, 0xef, 0xb0, 0x65, 0x7f, 0xd7, 0x53, 0xdb, 0x64, 0xcc, 0x60,
	0x09, 0x8d, 0xf6, 0xa8, 0x6c, 0x1b, 0xe3, 0xe7, 0xc1, 0xf8, 0x39, 0x34, 0x6e, 0x2f, 0xaf, 0x6c,
	0xd9, 0x6b, 0xf8, 0xa4, 0xb2, 0xeb, 0x1a, 0x21, 0xa2, 0x80, 0x70, 0xd6, 0x52, 0x25, 0x4c, 0xad,
	0x8c, 0x65, 0x83, 0x70, 0xc5, 0x47, 0xc7, 0x0e, 0x2a, 0x0c, 0x78, 0x1d, 0x4d, 0x42, 0xaa, 0xf4,
	0x03, 0xcf, 0x18, 0x7a, 0x05, 0x0c, 0x59, 0x91, 0xa1, 0x53, 0x9b, 0xe1, 0xed, 0xf0, 0x41, 0xd3,
	0x9b, 0x50, 0x88, 0xad, 0xc0, 0xab, 0xbc, 0x97, 0x31, 0x98, 0x28, 0x2b, 0xf8, 0x0e, 0x3a, 0x14,
	0xe5, 0x53, 0x6c, 0xf4, 0x3f, 0xc1, 0xe8, 0x62, 0x64, 0x74, 0x7e, 0x73, 0xf0, 0x5a, 0xea, 0x20,
	0xc3, 0xc8, 0xa4, 0x96, 0xb2, 0xfd, 0x59, 0x2e, 0x63, 0x3c, 0x51, 0xa0, 0x92, 0x8b, 0x9a, 0x7f,
	0x84, 0x8b, 0x8a, 0x6f, 0xa1, 0x09, 0xe8, 0x0d, 0xcc, 0x21, 0xb6, 0x50, 0xfb, 0x0f, 0xd0, 0xfb,
	0x32, 0x2a, 0x54, 0x7b, 0x5c, 0x91, 0xa8, 0xbb, 0xda, 0x93, 0x0a, 0x75, 0xa0, 0xce, 0xf1, 0x16,
	0xa0, 0x2b, 0xbf, 0xca, 0xa1, 0x67, 0x0e, 0xa8, 0x9d, 0x78, 0x03, 0x4d, 0xee, 0xb4, 0x44, 0x63,
	0x20, 0x44, 0xfe, 0x79, 0x27, 0x4e, 0xec, 0xb4, 0xc4, 0x2d, 0x2a, 0xdb, 0x5f, 0x9e, 0x83, 0x2a,
	0x3f, 0xcc, 0xa1, 0x33, 0x5f, 0xac, 0x9c, 0xe3, 0x97, 0xb2, 0xa9, 0x77, 0x18, 0x48, 0x4c, 0x25,
	0x48, 0x0c, 0x78, 0xff, 0x24, 0x2a, 0x86, 0x75, 0x20, 0x22, 0x6e, 0xa3, 0xf0, 0x53, 0xdd, 0xc5,
	0xe5, 0x81, 0x86, 0x06, 0xd6, 0x27, 0xee, 0x58, 0x2a, 0xdf, 0xcb, 0x65, 0x12, 0x72, 0xe8, 0xc6,
	0x80, 0x9f, 0x47, 0x10, 0xe5, 0x31, 0xab, 0x39, 0x60, 0x55, 0x84, 0x35, 0x56, 0x22, 0x75, 0xd7,
	0x1e, 0x6f, 0xf7, 0x1f, 0x9e, 0xd1, 0x77, 0x72, 0xe8, 0xec, 0x17, 0xdc, 0x5a, 0xf0, 0x09, 0x54,
	0x8c, 0xf2, 0x29, 0x24, 0x66, 0x17, 0x4c, 0x52, 0x3c, 0x2c, 0x91, 0x0f, 0x72, 0xe8, 0xe4, 0x7d,
	0xf6, 0x25, 0xfc, 0x22, 0x42, 0xc2, 0xef, 0x07, 0x0e, 0x1b, 0x48, 0xe7, 0x69, 0x70, 0xcc, 0x64,
	0x18, 0x89, 0x76, 0x41, 0x23, 0xb6, 0x02, 0x0f, 0x9f, 0x47, 0x45, 0x73, 0x6d, 0x05, 0xf8, 0xfc,
	0x50, 0x3c, 0x32, 0x10, 0x95, 0xd4, 0x7f, 0xc9, 0xc3, 0xc3, 0xda, 0x20, 0x07, 0xbc, 0x81, 0x0a,
	0x92, 0x77, 0x99, 0x90, 0xb4, 0xdb, 0x03, 0x93, 0xa3, 0xb5, 0x57, 0x41, 0xc5, 0x79, 0x54, 0xb4,
	0x97, 0x57, 0x96, 0xa9, 0x64, 0x6a, 0x1c, 0x93, 0x4d, 0xde, 0x65, 0x50, 0x13, 0x13, 0xf1, 0xb9,
	0x4b, 0x05, 0xa1, 0xae, 0xcb, 0x5c, 0xcb, 0x8e, 0xf5, 0xe0, 0x1b, 0x68, 0x22, 0xbc, 0x01, 0xd2,
	0xac, 0x5e, 0x06, 0x95, 0x2f, 0xe0, 0x73, 0x10, 0xec, 0xbe, 0x27, 0x55, 0xb4, 0x87, 0xd7, 0x3d,
	0xd0, 0xfe, 0xa6, 0x02, 0xdf, 0xb2, 0x43, 0x0d, 0xd8, 0x41, 0x85, 0x20, 0x74, 0x91, 0xe9, 0x5c,
	0x8f, 0xee, 0xdb, 0x18, 0xc6, 0xf7, 0x66, 0xca, 0x52, 0x24, 0x17, 0xb6, 0xd8, 0x49, 0x13, 0xb1,
	0x5e, 0x6c, 0x23, 0xc4, 0x45, 0xa3, 0xc7, 0x3c, 0x97, 0x7b, 0xdb, 0xfa, 0x44, 0x5e, 0xfb, 0x37,
	0x50, 0xf5, 0x22, 0x7e, 0xe1, 0x8d, 0x36, 0x93, 0x6d, 0x16, 0x64, 0x67, 0xcf, 0x05, 0x31, 0x22,
	0xc4, 0x0f, 0xd4, 0x90, 0x65, 0x17, 0xb8, 0xb8, 0xa5, 0x3f, 0x55, 0xbe, 0x0d, 0x97, 0x1a, 0x4b,
	0xf1, 0xb1, 0xde, 0x44, 0x4a, 0x35, 0xd8, 0x16, 0xf8, 0x95, 0x74, 0x06, 0x3c, 0x03, 0xd6, 0x8e,
	0x0c, 0x64, 0x00, 0x9e, 0xbc, 0xa6, 0x5f, 0x12, 0xad, 0x28, 0x17, 0x16, 0xd0, 0x64, 0xd4, 0x39,
	0xe9, 0x56, 0x77, 0xd6, 0x4a, 0x3d, 0x95, 0xda, 0x11, 0xa2, 0xf2, 0xeb, 0x3c, 0x7a, 0x4a, 0xb5,
	0xf8, 0x4c, 0x3e, 0x22, 0xf3, 0x9f, 0xe4, 0x86, 0xa4, 0x40, 0xed, 0x9b, 0x20, 0xba, 0x83, 0x65,
	0xa2, 0xeb, 0x10, 0x84, 0x06, 0x8c, 0xf4, 0x3d, 0xfe, 0x4e, 0x9f, 0x75, 0xf6, 0x86, 0x5c, 0x95,
	0xaa, 0xd4, 0x80, 0x0b, 0xa6, 0xe8, 0xc2, 0x4a, 0x7d, 0xee, 0x2e, 0x0c, 0xbe, 0xa1, 0xaa, 0xa3,
	0x04, 0x0c, 0x72, 0xdf, 0x5b, 0x18, 0x7e, 0x79, 0x3a, 0x98, 0x80, 0x34, 0x9d, 0x80, 0xb5, 0x2b,
	0xc0, 0xed, 0x75, 0xfc, 0xdf, 0x5b, 0xe1, 0x0d, 0xec, 0xc0, 0x61, 0x6b, 0x41, 0x99, 0x17, 0xc6,
	0xd8, 0xe0, 0xfd, 0x61, 0xe6, 0x22, 0x2d, 0xce, 0xe3, 0xdf, 0xe4, 0xe1, 0xf8, 0x72, 0x35, 0xa0,
	0xde, 0x63, 0xaf, 0x3e, 0x32, 0xaf, 0x7e, 0x9c, 0x03, 0xaf, 0xae, 0x72, 0x91, 0x70, 0xaa, 0x00,
	0xaf, 0x5e, 0x40, 0xe3, 0x7e, 0xab, 0x25, 0x98, 0x7e, 0x02, 0x18, 0xa9, 0x55, 0xc0, 0xfa, 0x31,
	0x5c, 0x8e, 0x60, 0x04, 0xee, 0x0b, 0x20, 0x0d, 0x01, 0x68, 0xd9, 0x46, 0x02, 0x5f, 0x44, 0x63,
	0x8e, 0xaf, 0xce, 0x76, 0x79, 0x10, 0x3d, 0x0d, 0xa2, 0x27, 0xf1, 0xf1, 0xb5, 0x7e, 0xb7, 0xc9,
	0x02, 0x45, 0x3b, 0xf6, 0xac, 0xf4, 0x49, 0x8b, 0x49, 0xa7, 0x6d, 0xd9, 0x5a, 0xa6, 0xb2, 0x8c,
	0xca, 0xc3, 0x48, 0xd9, 0x4c, 0xf4, 0x3b, 0x12, 0x9f, 0x41, 0x63, 0x5c, 0xb2, 0xae, 0x28, 0xe5,
	0xc8, 0xc8, 0xd0, 0x44, 0xd4, 0xc3, 0xaa, 0xf2, 0x1f, 0x8b, 0xea, 0x40, 0x6a, 0xf3, 0x81, 0xf9,
	0xbd, 0x34, 0x64, 0xdf, 0xa9, 0xcd, 0x02, 0x53, 0x84, 0xf5, 0x99, 0x42, 0x2d, 0xc9, 0xc0, 0x4e,
	0x74, 0x3e, 0x53, 0x06, 0x0e, 0x5b, 0xd9, 0xf7, 0xd3, 0x81, 0x4a, 0xf0, 0xdb, 0xbc, 0xbe, 0x60,
	0x65, 0xf2, 0xd1, 0x10, 0xf8, 0xf1, 0xd0, 0x90, 0x7d, 0x3f, 0x07, 0x32, 0xef, 0xe1, 0x77, 0x33,
	0x67, 0x8a, 0x87, 0x8b, 0x5b, 0x47, 0x53, 0xf8, 0xd7, 0xc4, 0x2d, 0x18, 0xfb, 0x82, 0x71, 0xfb,
	0xbb, 0x3c, 0x74, 0x96, 0x50, 0x0d, 0x1e, 0x7b, 0xf6, 0x51, 0x7a, 0xf6, 0x07, 0xba, 0x67, 0x57,
	0xc9, 0x97, 0x72, 0xec, 0x57, 0x5c, 0x14, 0xae, 0xa3, 0xe3, 0xfb, 0xf0, 0x32, 0x75, 0xe1, 0x5c,
	0xb2, 0x2e, 0x0c, 0xcd, 0x4c, 0x53, 0x1a, 0x7e, 0xa4, 0xc3, 0xc7, 0x94, 0x86, 0x44, 0x0f, 0x0f,
	0x93, 0xfc, 0xaf, 0x6c, 0xfb, 0x7e, 0x12, 0xc8, 0x1e, 0x4d, 0x9e, 0x21, 0xd0, 0x52, 0xf8, 0xec,
	0x38, 0x78, 0x90, 0xb2, 0x32, 0x55, 0x02, 0x5b, 0x99, 0x17, 0xd6, 0xb8, 0x48, 0xe0, 0xef, 0xe7,
	0xd0, 0xdc, 0x3d, 0xc6, 0x7a, 0xe1, 0x35, 0x28, 0xed, 0xf0, 0x1d, 0x66, 0x1e, 0x12, 0x5d, 0x30,
	0xfb, 0x7f, 0xf8, 0xed, 0x7a, 0x8b, 0x48, 0xf3, 0x90, 0x18, 0x1d, 0x5b, 0xc2, 0x37, 0xb2, 0x7b,
	0xac, 0x27, 0x09, 0x48, 0xe9, 0xc7, 0x4a, 0x8f, 0xb4, 0xfd, 0x7e, 0x40, 0x02, 0xbe, 0xdd, 0x96,
	0xd1, 0x13, 0x2c, 0xcb, 0x3c, 0x06, 0xc1, 0x2b, 0x24, 0x3c, 0x64, 0xce, 0x28, 0xf3, 0x86, 0x9f,
	0x52, 0x53, 0xf9, 0xdc, 0xec, 0xb6, 0x4c, 0x3e, 0x72, 0xef, 0xdc, 0x37, 0xd1, 0x92, 0x97, 0x2d,
	0x0f, 0x99, 0x66, 0x21, 0x83, 0x07, 0x4c, 0x34, 0x27, 0x93, 0x68, 0x89, 0x8b, 0xd9, 0x7d, 0x13,
	0x2d, 0xc9, 0xfd, 0x3e, 0xa9, 0xf6, 0xa7, 0x3c, 0xec, 0x73, 0xba, 0x88, 0x3d, 0x76, 0xf3, 0x97,
	0xe5, 0xe6, 0x3f, 0xe4, 0xa3, 0x76, 0x22, 0xe9, 0xe5, 0xaf, 0xb6, 0xa0, 0x25, 0xd7, 0x77, 0xe4,
	0x41, 0xd7, 0x97, 0xa2, 0x31, 0x21, 0xa9, 0xd4, 0x4f, 0xfd, 0xd3, 0x8b, 0xcf, 0x5a, 0xfb, 0x4f,
	0xd1, 0xda, 0x50, 0xc0, 0xf8, 0x7f, 0x8d, 0xea, 0x84, 0x06, 0xb2, 0xfb, 0x12, 0x84, 0xd1, 0xca,
	0x3c, 0x1a, 0x03, 0x49, 0x3c, 0x81, 0x46, 0xaa, 0x6b, 0x6f, 0xcd, 0x3e, 0x81, 0x0b, 0x68, 0xec,
	0x76, 0x75, 0xb5, 0xbe, 0x3c, 0x9b, 0xc3, 0x45, 0x34, 0x51, 0x5f, 0xd3, 0x3f, 0xf2, 0x95, 0x6b,
	0xd0, 0x69, 0x0d, 0x31, 0x6f, 0x4a, 0xf3, 0x7c, 0xb2, 0x34, 0x0f, 0x2b, 0x87, 0xa6, 0x32, 0x7f,
	0xa8, 0xef, 0x0d, 0x94, 0x2a, 0x73, 0x9c, 0xd3, 0x6f, 0xa1, 0x83, 0x87, 0xce, 0x50, 0xeb, 0xdb,
	0xe9, 0x82, 0x9f, 0x85, 0x26, 0x0f, 0xc0, 0x1d, 0xf3, 0xce, 0x1e, 0x9e, 0x1d, 0xf5, 0x83, 0x6c,
	0xe2, 0x68, 0x29, 0xac, 0x90, 0xc9, 0x47, 0xfa, 0xb6, 0x67, 0x99, 0x75, 0x98, 0x64, 0xfb, 0x72,
	0x81, 0x10, 0x72, 0x13, 0xaf, 0x27, 0xa5, 0x21, 0x3c, 0xe0, 0xdd, 0xa4, 0xf6, 0xef, 0x40, 0xe6,
	0x25, 0x6c, 0x29, 0x32, 0x4a, 0x22, 0x0c, 0xee, 0x21, 0x44, 0xd4, 0x72, 0xb8, 0x60, 0xdb, 0xd2,
	0xef, 0x2d, 0x95, 0x7b, 0xe8, 0x9c, 0x2e, 0xc9, 0x86, 0x8c, 0xca, 0x90, 0x84, 0x5b, 0x96, 0x7c,
	0xb8, 0x17, 0x05, 0xdf, 0x5c, 0x0a, 0x23, 0x53, 0x07, 0x75, 0xb4, 0xf6, 0x71, 0x64, 0x86, 0x4e,
	0x48, 0xcf, 0x5e, 0xef, 0xb6, 0x1f, 0xea, 0x1b, 0xa5, 0xc4, 0xec, 0xd3, 0x06, 0x61, 0xee, 0x8d,
	0xec, 0x3d, 0x46, 0x15, 0x8c, 0x5d, 0x4c, 0xde, 0x63, 0x2c, 0xc0, 0x9c, 0x43, 0xe4, 0xb0, 0x7b,
	0x81, 0xc1, 0x19, 0xc7, 0x3a, 0x2b, 0xef, 0xe7, 0x81, 0x89, 0x8a, 0x88, 0xaa, 0xe7, 0xda, 0x4c,
	0x30, 0x99, 0x99, 0xb9, 0xe9, 0xf9, 0xc2, 0x44, 0xd6, 0xd9, 0x58, 0x02, 0x1a, 0x18, 0xcf, 0x6e,
	0xdc, 0x37, 0x7d, 0x47, 0x92, 0xe9, 0x7b, 0x93, 0xbe, 0x4b, 0xbc, 0xc8, 0x51, 0x10, 0x0e, 0xd9,
	0xf4, 0xe5, 0x68, 0xbc, 0xc5, 0x3b, 0x92, 0x05, 0xe6, 0xcf, 0x36, 0xff, 0x03, 0xd2, 0x37, 0x70,
	0xdd, 0x66, 0xb2, 0x1f, 0x78, 0xc4, 0xf7, 0x3a, 0x7b, 0x24, 0x80, 0xd5, 0x10, 0xa6, 0x6e, 0x09,
	0x19, 0xe8, 0x2a, 0xd5, 0x0b, 0x98, 0xda, 0x78, 0xf5, 0xb4, 0xcd, 0x1f, 0x6e, 0x04, 0xd9, 0xe6,
	0x3b, 0xcc, 0x23, 0xa2, 0xdf, 0xd4, 0x38, 0xcb, 0x36, 0x06, 0x2a, 0x3f, 0xd3, 0xa1, 0x78, 0xa0,
	0x0b, 0xcc, 0xba, 0x5f, 0x1f, 0x72, 0x38, 0x4a, 0x24, 0x44, 0x54, 0xde, 0x06, 0x13, 0x62, 0x68,
	0x06, 0xe0, 0x4b, 0xa8, 0x28, 0x7d, 0x49, 0x3b, 0x8d, 0xc1, 0x1a, 0x17, 0xbf, 0xa2, 0xaa, 0x21,
	0x02, 0x43, 0x91, 0x97, 0x2c, 0x1b, 0x81, 0x04, 0x44, 0xa2, 0x3a, 0x5c, 0x3e, 0x97, 0xcc, 0xe5,
	0xe1, 0x0b, 0xd7, 0xc9, 0x86, 0xd0, 0x1a, 0x58, 0xb9, 0x96, 0x0c, 0xa1, 0xd7, 0xd6, 0x95, 0x4b,
	0x13, 0x5c, 0x07, 0xff, 0x60, 0x16, 0x07, 0x57, 0xd8, 0x17, 0x05, 0xb0, 0x12, 0xc9, 0x3b, 0xb2,
	0x8a, 0x40, 0xa7, 0xef, 0x43, 0xea, 0xd1, 0xbb, 0xf2, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59,
	0xd5, 0xc7, 0xbc, 0x0c, 0x30, 0x00, 0x00,
}
