// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grr/proto/api/vfs.proto

/*
Package vfs is a generated protocol buffer package.

It is generated from these files:
	grr/proto/api/vfs.proto

It has these top-level messages:
	ApiFile
	ApiAff4ObjectRepresentation
	ApiAff4ObjectType
	ApiAff4ObjectAttribute
	ApiAff4ObjectAttributeValue
	ApiVfsTimelineItem
	ApiGetFileDetailsArgs
	ApiGetFileDetailsResult
	ApiListFilesArgs
	ApiListFilesResult
	ApiGetVfsFilesArchiveArgs
	ApiGetFileTextArgs
	ApiGetFileTextResult
	ApiGetFileBlobArgs
	ApiGetFileVersionTimesArgs
	ApiGetFileVersionTimesResult
	ApiGetFileDownloadCommandArgs
	ApiGetFileDownloadCommandResult
	ApiCreateVfsRefreshOperationArgs
	ApiGetVfsTimelineArgs
	ApiGetVfsTimelineResult
	ApiGetVfsTimelineAsCsvArgs
	ApiCreateVfsRefreshOperationResult
	ApiGetVfsRefreshOperationStateArgs
	ApiGetVfsRefreshOperationStateResult
	ApiUpdateVfsFileContentArgs
	ApiUpdateVfsFileContentResult
	ApiGetVfsFileContentUpdateStateArgs
	ApiGetVfsFileContentUpdateStateResult
	ApiListKnownEncodingsResult
*/
package vfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import jobs "github.com/google/grr_go_api_client/grrproto/grr/proto/jobs_proto"
import _ "github.com/google/grr_go_api_client/grrproto/grr/proto/semantic_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiVfsTimelineItem_FileActionType int32

const (
	ApiVfsTimelineItem_MODIFICATION     ApiVfsTimelineItem_FileActionType = 0
	ApiVfsTimelineItem_ACCESS           ApiVfsTimelineItem_FileActionType = 1
	ApiVfsTimelineItem_METADATA_CHANGED ApiVfsTimelineItem_FileActionType = 2
)

var ApiVfsTimelineItem_FileActionType_name = map[int32]string{
	0: "MODIFICATION",
	1: "ACCESS",
	2: "METADATA_CHANGED",
}
var ApiVfsTimelineItem_FileActionType_value = map[string]int32{
	"MODIFICATION":     0,
	"ACCESS":           1,
	"METADATA_CHANGED": 2,
}

func (x ApiVfsTimelineItem_FileActionType) Enum() *ApiVfsTimelineItem_FileActionType {
	p := new(ApiVfsTimelineItem_FileActionType)
	*p = x
	return p
}
func (x ApiVfsTimelineItem_FileActionType) String() string {
	return proto.EnumName(ApiVfsTimelineItem_FileActionType_name, int32(x))
}
func (x *ApiVfsTimelineItem_FileActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiVfsTimelineItem_FileActionType_value, data, "ApiVfsTimelineItem_FileActionType")
	if err != nil {
		return err
	}
	*x = ApiVfsTimelineItem_FileActionType(value)
	return nil
}
func (ApiVfsTimelineItem_FileActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type ApiGetFileTextArgs_Encoding int32

const (
	ApiGetFileTextArgs_BASE64_CODEC ApiGetFileTextArgs_Encoding = 0
	ApiGetFileTextArgs_BIG5         ApiGetFileTextArgs_Encoding = 1
	ApiGetFileTextArgs_BIG5HKSCS    ApiGetFileTextArgs_Encoding = 2
	ApiGetFileTextArgs_CP037        ApiGetFileTextArgs_Encoding = 3
	ApiGetFileTextArgs_CP1006       ApiGetFileTextArgs_Encoding = 4
	ApiGetFileTextArgs_CP1026       ApiGetFileTextArgs_Encoding = 5
	ApiGetFileTextArgs_CP1140       ApiGetFileTextArgs_Encoding = 6
	ApiGetFileTextArgs_CP1250       ApiGetFileTextArgs_Encoding = 7
	ApiGetFileTextArgs_CP1251       ApiGetFileTextArgs_Encoding = 8
	ApiGetFileTextArgs_CP1252       ApiGetFileTextArgs_Encoding = 9
	ApiGetFileTextArgs_CP1253       ApiGetFileTextArgs_Encoding = 10
	ApiGetFileTextArgs_CP1254       ApiGetFileTextArgs_Encoding = 11
	ApiGetFileTextArgs_CP1255       ApiGetFileTextArgs_Encoding = 12
	ApiGetFileTextArgs_CP1256       ApiGetFileTextArgs_Encoding = 13
	ApiGetFileTextArgs_CP1257       ApiGetFileTextArgs_Encoding = 14
	ApiGetFileTextArgs_CP1258       ApiGetFileTextArgs_Encoding = 15
	ApiGetFileTextArgs_CP424        ApiGetFileTextArgs_Encoding = 16
	ApiGetFileTextArgs_CP437        ApiGetFileTextArgs_Encoding = 17
	ApiGetFileTextArgs_CP500        ApiGetFileTextArgs_Encoding = 18
	ApiGetFileTextArgs_CP737        ApiGetFileTextArgs_Encoding = 19
	ApiGetFileTextArgs_CP775        ApiGetFileTextArgs_Encoding = 20
	ApiGetFileTextArgs_CP850        ApiGetFileTextArgs_Encoding = 21
	ApiGetFileTextArgs_CP852        ApiGetFileTextArgs_Encoding = 22
	ApiGetFileTextArgs_CP855        ApiGetFileTextArgs_Encoding = 23
	ApiGetFileTextArgs_CP856        ApiGetFileTextArgs_Encoding = 24
	ApiGetFileTextArgs_CP857        ApiGetFileTextArgs_Encoding = 25
	ApiGetFileTextArgs_CP860        ApiGetFileTextArgs_Encoding = 26
	ApiGetFileTextArgs_CP861        ApiGetFileTextArgs_Encoding = 27
	ApiGetFileTextArgs_CP862        ApiGetFileTextArgs_Encoding = 28
	ApiGetFileTextArgs_CP863        ApiGetFileTextArgs_Encoding = 29
	ApiGetFileTextArgs_CP864        ApiGetFileTextArgs_Encoding = 30
	ApiGetFileTextArgs_CP865        ApiGetFileTextArgs_Encoding = 31
	ApiGetFileTextArgs_CP866        ApiGetFileTextArgs_Encoding = 32
	ApiGetFileTextArgs_CP869        ApiGetFileTextArgs_Encoding = 33
	ApiGetFileTextArgs_CP874        ApiGetFileTextArgs_Encoding = 34
	ApiGetFileTextArgs_CP875        ApiGetFileTextArgs_Encoding = 35
	ApiGetFileTextArgs_CP932        ApiGetFileTextArgs_Encoding = 36
	ApiGetFileTextArgs_CP949        ApiGetFileTextArgs_Encoding = 37
	ApiGetFileTextArgs_CP950        ApiGetFileTextArgs_Encoding = 38
	ApiGetFileTextArgs_IDNA         ApiGetFileTextArgs_Encoding = 39
	ApiGetFileTextArgs_ROT_13       ApiGetFileTextArgs_Encoding = 40
	ApiGetFileTextArgs_UTF_16       ApiGetFileTextArgs_Encoding = 41
	ApiGetFileTextArgs_UTF_16_BE    ApiGetFileTextArgs_Encoding = 42
	ApiGetFileTextArgs_UTF_16_LE    ApiGetFileTextArgs_Encoding = 43
	ApiGetFileTextArgs_UTF_32       ApiGetFileTextArgs_Encoding = 44
	ApiGetFileTextArgs_UTF_32_BE    ApiGetFileTextArgs_Encoding = 45
	ApiGetFileTextArgs_UTF_32_LE    ApiGetFileTextArgs_Encoding = 46
	ApiGetFileTextArgs_UTF_7        ApiGetFileTextArgs_Encoding = 47
	ApiGetFileTextArgs_UTF_8        ApiGetFileTextArgs_Encoding = 48
	ApiGetFileTextArgs_UTF_8_SIG    ApiGetFileTextArgs_Encoding = 49
	ApiGetFileTextArgs_UU_CODEC     ApiGetFileTextArgs_Encoding = 50
	ApiGetFileTextArgs_ZLIB_CODEC   ApiGetFileTextArgs_Encoding = 51
)

var ApiGetFileTextArgs_Encoding_name = map[int32]string{
	0:  "BASE64_CODEC",
	1:  "BIG5",
	2:  "BIG5HKSCS",
	3:  "CP037",
	4:  "CP1006",
	5:  "CP1026",
	6:  "CP1140",
	7:  "CP1250",
	8:  "CP1251",
	9:  "CP1252",
	10: "CP1253",
	11: "CP1254",
	12: "CP1255",
	13: "CP1256",
	14: "CP1257",
	15: "CP1258",
	16: "CP424",
	17: "CP437",
	18: "CP500",
	19: "CP737",
	20: "CP775",
	21: "CP850",
	22: "CP852",
	23: "CP855",
	24: "CP856",
	25: "CP857",
	26: "CP860",
	27: "CP861",
	28: "CP862",
	29: "CP863",
	30: "CP864",
	31: "CP865",
	32: "CP866",
	33: "CP869",
	34: "CP874",
	35: "CP875",
	36: "CP932",
	37: "CP949",
	38: "CP950",
	39: "IDNA",
	40: "ROT_13",
	41: "UTF_16",
	42: "UTF_16_BE",
	43: "UTF_16_LE",
	44: "UTF_32",
	45: "UTF_32_BE",
	46: "UTF_32_LE",
	47: "UTF_7",
	48: "UTF_8",
	49: "UTF_8_SIG",
	50: "UU_CODEC",
	51: "ZLIB_CODEC",
}
var ApiGetFileTextArgs_Encoding_value = map[string]int32{
	"BASE64_CODEC": 0,
	"BIG5":         1,
	"BIG5HKSCS":    2,
	"CP037":        3,
	"CP1006":       4,
	"CP1026":       5,
	"CP1140":       6,
	"CP1250":       7,
	"CP1251":       8,
	"CP1252":       9,
	"CP1253":       10,
	"CP1254":       11,
	"CP1255":       12,
	"CP1256":       13,
	"CP1257":       14,
	"CP1258":       15,
	"CP424":        16,
	"CP437":        17,
	"CP500":        18,
	"CP737":        19,
	"CP775":        20,
	"CP850":        21,
	"CP852":        22,
	"CP855":        23,
	"CP856":        24,
	"CP857":        25,
	"CP860":        26,
	"CP861":        27,
	"CP862":        28,
	"CP863":        29,
	"CP864":        30,
	"CP865":        31,
	"CP866":        32,
	"CP869":        33,
	"CP874":        34,
	"CP875":        35,
	"CP932":        36,
	"CP949":        37,
	"CP950":        38,
	"IDNA":         39,
	"ROT_13":       40,
	"UTF_16":       41,
	"UTF_16_BE":    42,
	"UTF_16_LE":    43,
	"UTF_32":       44,
	"UTF_32_BE":    45,
	"UTF_32_LE":    46,
	"UTF_7":        47,
	"UTF_8":        48,
	"UTF_8_SIG":    49,
	"UU_CODEC":     50,
	"ZLIB_CODEC":   51,
}

func (x ApiGetFileTextArgs_Encoding) Enum() *ApiGetFileTextArgs_Encoding {
	p := new(ApiGetFileTextArgs_Encoding)
	*p = x
	return p
}
func (x ApiGetFileTextArgs_Encoding) String() string {
	return proto.EnumName(ApiGetFileTextArgs_Encoding_name, int32(x))
}
func (x *ApiGetFileTextArgs_Encoding) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetFileTextArgs_Encoding_value, data, "ApiGetFileTextArgs_Encoding")
	if err != nil {
		return err
	}
	*x = ApiGetFileTextArgs_Encoding(value)
	return nil
}
func (ApiGetFileTextArgs_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type ApiGetVfsRefreshOperationStateResult_State int32

const (
	ApiGetVfsRefreshOperationStateResult_RUNNING  ApiGetVfsRefreshOperationStateResult_State = 0
	ApiGetVfsRefreshOperationStateResult_FINISHED ApiGetVfsRefreshOperationStateResult_State = 1
)

var ApiGetVfsRefreshOperationStateResult_State_name = map[int32]string{
	0: "RUNNING",
	1: "FINISHED",
}
var ApiGetVfsRefreshOperationStateResult_State_value = map[string]int32{
	"RUNNING":  0,
	"FINISHED": 1,
}

func (x ApiGetVfsRefreshOperationStateResult_State) Enum() *ApiGetVfsRefreshOperationStateResult_State {
	p := new(ApiGetVfsRefreshOperationStateResult_State)
	*p = x
	return p
}
func (x ApiGetVfsRefreshOperationStateResult_State) String() string {
	return proto.EnumName(ApiGetVfsRefreshOperationStateResult_State_name, int32(x))
}
func (x *ApiGetVfsRefreshOperationStateResult_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetVfsRefreshOperationStateResult_State_value, data, "ApiGetVfsRefreshOperationStateResult_State")
	if err != nil {
		return err
	}
	*x = ApiGetVfsRefreshOperationStateResult_State(value)
	return nil
}
func (ApiGetVfsRefreshOperationStateResult_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{24, 0}
}

type ApiGetVfsFileContentUpdateStateResult_State int32

const (
	ApiGetVfsFileContentUpdateStateResult_RUNNING  ApiGetVfsFileContentUpdateStateResult_State = 0
	ApiGetVfsFileContentUpdateStateResult_FINISHED ApiGetVfsFileContentUpdateStateResult_State = 1
)

var ApiGetVfsFileContentUpdateStateResult_State_name = map[int32]string{
	0: "RUNNING",
	1: "FINISHED",
}
var ApiGetVfsFileContentUpdateStateResult_State_value = map[string]int32{
	"RUNNING":  0,
	"FINISHED": 1,
}

func (x ApiGetVfsFileContentUpdateStateResult_State) Enum() *ApiGetVfsFileContentUpdateStateResult_State {
	p := new(ApiGetVfsFileContentUpdateStateResult_State)
	*p = x
	return p
}
func (x ApiGetVfsFileContentUpdateStateResult_State) String() string {
	return proto.EnumName(ApiGetVfsFileContentUpdateStateResult_State_name, int32(x))
}
func (x *ApiGetVfsFileContentUpdateStateResult_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApiGetVfsFileContentUpdateStateResult_State_value, data, "ApiGetVfsFileContentUpdateStateResult_State")
	if err != nil {
		return err
	}
	*x = ApiGetVfsFileContentUpdateStateResult_State(value)
	return nil
}
func (ApiGetVfsFileContentUpdateStateResult_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{28, 0}
}

// Next id: 12
type ApiFile struct {
	Name              *string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path              *string         `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Type              *string         `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Stat              *jobs.StatEntry `protobuf:"bytes,11,opt,name=stat" json:"stat,omitempty"`
	Age               *uint64         `protobuf:"varint,5,opt,name=age" json:"age,omitempty"`
	IsDirectory       *bool           `protobuf:"varint,6,opt,name=is_directory,json=isDirectory" json:"is_directory,omitempty"`
	Hash              *jobs.Hash      `protobuf:"bytes,7,opt,name=hash" json:"hash,omitempty"`
	LastCollected     *uint64         `protobuf:"varint,8,opt,name=last_collected,json=lastCollected" json:"last_collected,omitempty"`
	LastCollectedSize *uint64         `protobuf:"varint,10,opt,name=last_collected_size,json=lastCollectedSize" json:"last_collected_size,omitempty"`
	// Details of an ApiFile.
	Details          *ApiAff4ObjectRepresentation `protobuf:"bytes,9,opt,name=details" json:"details,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ApiFile) Reset()                    { *m = ApiFile{} }
func (m *ApiFile) String() string            { return proto.CompactTextString(m) }
func (*ApiFile) ProtoMessage()               {}
func (*ApiFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiFile) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiFile) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *ApiFile) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ApiFile) GetStat() *jobs.StatEntry {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *ApiFile) GetAge() uint64 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *ApiFile) GetIsDirectory() bool {
	if m != nil && m.IsDirectory != nil {
		return *m.IsDirectory
	}
	return false
}

func (m *ApiFile) GetHash() *jobs.Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ApiFile) GetLastCollected() uint64 {
	if m != nil && m.LastCollected != nil {
		return *m.LastCollected
	}
	return 0
}

func (m *ApiFile) GetLastCollectedSize() uint64 {
	if m != nil && m.LastCollectedSize != nil {
		return *m.LastCollectedSize
	}
	return 0
}

func (m *ApiFile) GetDetails() *ApiAff4ObjectRepresentation {
	if m != nil {
		return m.Details
	}
	return nil
}

type ApiAff4ObjectRepresentation struct {
	Types            []*ApiAff4ObjectType `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApiAff4ObjectRepresentation) Reset()                    { *m = ApiAff4ObjectRepresentation{} }
func (m *ApiAff4ObjectRepresentation) String() string            { return proto.CompactTextString(m) }
func (*ApiAff4ObjectRepresentation) ProtoMessage()               {}
func (*ApiAff4ObjectRepresentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiAff4ObjectRepresentation) GetTypes() []*ApiAff4ObjectType {
	if m != nil {
		return m.Types
	}
	return nil
}

type ApiAff4ObjectType struct {
	Name             *string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attributes       []*ApiAff4ObjectAttribute `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ApiAff4ObjectType) Reset()                    { *m = ApiAff4ObjectType{} }
func (m *ApiAff4ObjectType) String() string            { return proto.CompactTextString(m) }
func (*ApiAff4ObjectType) ProtoMessage()               {}
func (*ApiAff4ObjectType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiAff4ObjectType) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiAff4ObjectType) GetAttributes() []*ApiAff4ObjectAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type ApiAff4ObjectAttribute struct {
	Name             *string                        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Values           []*ApiAff4ObjectAttributeValue `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *ApiAff4ObjectAttribute) Reset()                    { *m = ApiAff4ObjectAttribute{} }
func (m *ApiAff4ObjectAttribute) String() string            { return proto.CompactTextString(m) }
func (*ApiAff4ObjectAttribute) ProtoMessage()               {}
func (*ApiAff4ObjectAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiAff4ObjectAttribute) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApiAff4ObjectAttribute) GetValues() []*ApiAff4ObjectAttributeValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApiAff4ObjectAttributeValue struct {
	Type             *string              `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Age              *uint64              `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Value            *google_protobuf.Any `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApiAff4ObjectAttributeValue) Reset()                    { *m = ApiAff4ObjectAttributeValue{} }
func (m *ApiAff4ObjectAttributeValue) String() string            { return proto.CompactTextString(m) }
func (*ApiAff4ObjectAttributeValue) ProtoMessage()               {}
func (*ApiAff4ObjectAttributeValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApiAff4ObjectAttributeValue) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ApiAff4ObjectAttributeValue) GetAge() uint64 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *ApiAff4ObjectAttributeValue) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type ApiVfsTimelineItem struct {
	Timestamp        *uint64                            `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	FilePath         *string                            `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Action           *ApiVfsTimelineItem_FileActionType `protobuf:"varint,3,opt,name=action,enum=ApiVfsTimelineItem_FileActionType" json:"action,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *ApiVfsTimelineItem) Reset()                    { *m = ApiVfsTimelineItem{} }
func (m *ApiVfsTimelineItem) String() string            { return proto.CompactTextString(m) }
func (*ApiVfsTimelineItem) ProtoMessage()               {}
func (*ApiVfsTimelineItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApiVfsTimelineItem) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApiVfsTimelineItem) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiVfsTimelineItem) GetAction() ApiVfsTimelineItem_FileActionType {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ApiVfsTimelineItem_MODIFICATION
}

type ApiGetFileDetailsArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileDetailsArgs) Reset()                    { *m = ApiGetFileDetailsArgs{} }
func (m *ApiGetFileDetailsArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileDetailsArgs) ProtoMessage()               {}
func (*ApiGetFileDetailsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ApiGetFileDetailsArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetFileDetailsArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiGetFileDetailsArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiGetFileDetailsResult struct {
	File             *ApiFile `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiGetFileDetailsResult) Reset()                    { *m = ApiGetFileDetailsResult{} }
func (m *ApiGetFileDetailsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileDetailsResult) ProtoMessage()               {}
func (*ApiGetFileDetailsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApiGetFileDetailsResult) GetFile() *ApiFile {
	if m != nil {
		return m.File
	}
	return nil
}

type ApiListFilesArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Offset           *int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Count            *int64  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Filter           *string `protobuf:"bytes,5,opt,name=filter" json:"filter,omitempty"`
	DirectoriesOnly  *bool   `protobuf:"varint,6,opt,name=directories_only,json=directoriesOnly" json:"directories_only,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiListFilesArgs) Reset()                    { *m = ApiListFilesArgs{} }
func (m *ApiListFilesArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiListFilesArgs) ProtoMessage()               {}
func (*ApiListFilesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApiListFilesArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiListFilesArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiListFilesArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiListFilesArgs) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ApiListFilesArgs) GetFilter() string {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ""
}

func (m *ApiListFilesArgs) GetDirectoriesOnly() bool {
	if m != nil && m.DirectoriesOnly != nil {
		return *m.DirectoriesOnly
	}
	return false
}

type ApiListFilesResult struct {
	Items            []*ApiFile `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ApiListFilesResult) Reset()                    { *m = ApiListFilesResult{} }
func (m *ApiListFilesResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListFilesResult) ProtoMessage()               {}
func (*ApiListFilesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiListFilesResult) GetItems() []*ApiFile {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiGetVfsFilesArchiveArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetVfsFilesArchiveArgs) Reset()                    { *m = ApiGetVfsFilesArchiveArgs{} }
func (m *ApiGetVfsFilesArchiveArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetVfsFilesArchiveArgs) ProtoMessage()               {}
func (*ApiGetVfsFilesArchiveArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApiGetVfsFilesArchiveArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetVfsFilesArchiveArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiGetFileTextArgs struct {
	ClientId         *string                      `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string                      `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Offset           *int64                       `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length           *int64                       `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Encoding         *ApiGetFileTextArgs_Encoding `protobuf:"varint,5,opt,name=encoding,enum=ApiGetFileTextArgs_Encoding" json:"encoding,omitempty"`
	Timestamp        *uint64                      `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ApiGetFileTextArgs) Reset()                    { *m = ApiGetFileTextArgs{} }
func (m *ApiGetFileTextArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileTextArgs) ProtoMessage()               {}
func (*ApiGetFileTextArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiGetFileTextArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetFileTextArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiGetFileTextArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiGetFileTextArgs) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ApiGetFileTextArgs) GetEncoding() ApiGetFileTextArgs_Encoding {
	if m != nil && m.Encoding != nil {
		return *m.Encoding
	}
	return ApiGetFileTextArgs_BASE64_CODEC
}

func (m *ApiGetFileTextArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiGetFileTextResult struct {
	Content          *string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	TotalSize        *int64  `protobuf:"varint,2,opt,name=total_size,json=totalSize" json:"total_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileTextResult) Reset()                    { *m = ApiGetFileTextResult{} }
func (m *ApiGetFileTextResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileTextResult) ProtoMessage()               {}
func (*ApiGetFileTextResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ApiGetFileTextResult) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *ApiGetFileTextResult) GetTotalSize() int64 {
	if m != nil && m.TotalSize != nil {
		return *m.TotalSize
	}
	return 0
}

type ApiGetFileBlobArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Offset           *int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length           *int64  `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileBlobArgs) Reset()                    { *m = ApiGetFileBlobArgs{} }
func (m *ApiGetFileBlobArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileBlobArgs) ProtoMessage()               {}
func (*ApiGetFileBlobArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ApiGetFileBlobArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetFileBlobArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiGetFileBlobArgs) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ApiGetFileBlobArgs) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ApiGetFileBlobArgs) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ApiGetFileVersionTimesArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileVersionTimesArgs) Reset()                    { *m = ApiGetFileVersionTimesArgs{} }
func (m *ApiGetFileVersionTimesArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileVersionTimesArgs) ProtoMessage()               {}
func (*ApiGetFileVersionTimesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ApiGetFileVersionTimesArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetFileVersionTimesArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiGetFileVersionTimesResult struct {
	Times            []uint64 `protobuf:"varint,1,rep,name=times" json:"times,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiGetFileVersionTimesResult) Reset()                    { *m = ApiGetFileVersionTimesResult{} }
func (m *ApiGetFileVersionTimesResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileVersionTimesResult) ProtoMessage()               {}
func (*ApiGetFileVersionTimesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ApiGetFileVersionTimesResult) GetTimes() []uint64 {
	if m != nil {
		return m.Times
	}
	return nil
}

type ApiGetFileDownloadCommandArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileDownloadCommandArgs) Reset()                    { *m = ApiGetFileDownloadCommandArgs{} }
func (m *ApiGetFileDownloadCommandArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetFileDownloadCommandArgs) ProtoMessage()               {}
func (*ApiGetFileDownloadCommandArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ApiGetFileDownloadCommandArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetFileDownloadCommandArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiGetFileDownloadCommandResult struct {
	Command          *string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetFileDownloadCommandResult) Reset()         { *m = ApiGetFileDownloadCommandResult{} }
func (m *ApiGetFileDownloadCommandResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetFileDownloadCommandResult) ProtoMessage()    {}
func (*ApiGetFileDownloadCommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17}
}

func (m *ApiGetFileDownloadCommandResult) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

type ApiCreateVfsRefreshOperationArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	MaxDepth         *uint64 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth" json:"max_depth,omitempty"`
	NotifyUser       *bool   `protobuf:"varint,4,opt,name=notify_user,json=notifyUser" json:"notify_user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiCreateVfsRefreshOperationArgs) Reset()         { *m = ApiCreateVfsRefreshOperationArgs{} }
func (m *ApiCreateVfsRefreshOperationArgs) String() string { return proto.CompactTextString(m) }
func (*ApiCreateVfsRefreshOperationArgs) ProtoMessage()    {}
func (*ApiCreateVfsRefreshOperationArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

func (m *ApiCreateVfsRefreshOperationArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiCreateVfsRefreshOperationArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *ApiCreateVfsRefreshOperationArgs) GetMaxDepth() uint64 {
	if m != nil && m.MaxDepth != nil {
		return *m.MaxDepth
	}
	return 0
}

func (m *ApiCreateVfsRefreshOperationArgs) GetNotifyUser() bool {
	if m != nil && m.NotifyUser != nil {
		return *m.NotifyUser
	}
	return false
}

type ApiGetVfsTimelineArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetVfsTimelineArgs) Reset()                    { *m = ApiGetVfsTimelineArgs{} }
func (m *ApiGetVfsTimelineArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetVfsTimelineArgs) ProtoMessage()               {}
func (*ApiGetVfsTimelineArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ApiGetVfsTimelineArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetVfsTimelineArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiGetVfsTimelineResult struct {
	Items            []*ApiVfsTimelineItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ApiGetVfsTimelineResult) Reset()                    { *m = ApiGetVfsTimelineResult{} }
func (m *ApiGetVfsTimelineResult) String() string            { return proto.CompactTextString(m) }
func (*ApiGetVfsTimelineResult) ProtoMessage()               {}
func (*ApiGetVfsTimelineResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ApiGetVfsTimelineResult) GetItems() []*ApiVfsTimelineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ApiGetVfsTimelineAsCsvArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetVfsTimelineAsCsvArgs) Reset()                    { *m = ApiGetVfsTimelineAsCsvArgs{} }
func (m *ApiGetVfsTimelineAsCsvArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiGetVfsTimelineAsCsvArgs) ProtoMessage()               {}
func (*ApiGetVfsTimelineAsCsvArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ApiGetVfsTimelineAsCsvArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetVfsTimelineAsCsvArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiCreateVfsRefreshOperationResult struct {
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiCreateVfsRefreshOperationResult) Reset()         { *m = ApiCreateVfsRefreshOperationResult{} }
func (m *ApiCreateVfsRefreshOperationResult) String() string { return proto.CompactTextString(m) }
func (*ApiCreateVfsRefreshOperationResult) ProtoMessage()    {}
func (*ApiCreateVfsRefreshOperationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *ApiCreateVfsRefreshOperationResult) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetVfsRefreshOperationStateArgs struct {
	ClientId         *string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetVfsRefreshOperationStateArgs) Reset()         { *m = ApiGetVfsRefreshOperationStateArgs{} }
func (m *ApiGetVfsRefreshOperationStateArgs) String() string { return proto.CompactTextString(m) }
func (*ApiGetVfsRefreshOperationStateArgs) ProtoMessage()    {}
func (*ApiGetVfsRefreshOperationStateArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{23}
}

func (m *ApiGetVfsRefreshOperationStateArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetVfsRefreshOperationStateArgs) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetVfsRefreshOperationStateResult struct {
	State            *ApiGetVfsRefreshOperationStateResult_State `protobuf:"varint,1,opt,name=state,enum=ApiGetVfsRefreshOperationStateResult_State" json:"state,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *ApiGetVfsRefreshOperationStateResult) Reset()         { *m = ApiGetVfsRefreshOperationStateResult{} }
func (m *ApiGetVfsRefreshOperationStateResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetVfsRefreshOperationStateResult) ProtoMessage()    {}
func (*ApiGetVfsRefreshOperationStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{24}
}

func (m *ApiGetVfsRefreshOperationStateResult) GetState() ApiGetVfsRefreshOperationStateResult_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiGetVfsRefreshOperationStateResult_RUNNING
}

type ApiUpdateVfsFileContentArgs struct {
	ClientId         *string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FilePath         *string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiUpdateVfsFileContentArgs) Reset()                    { *m = ApiUpdateVfsFileContentArgs{} }
func (m *ApiUpdateVfsFileContentArgs) String() string            { return proto.CompactTextString(m) }
func (*ApiUpdateVfsFileContentArgs) ProtoMessage()               {}
func (*ApiUpdateVfsFileContentArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ApiUpdateVfsFileContentArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiUpdateVfsFileContentArgs) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

type ApiUpdateVfsFileContentResult struct {
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiUpdateVfsFileContentResult) Reset()                    { *m = ApiUpdateVfsFileContentResult{} }
func (m *ApiUpdateVfsFileContentResult) String() string            { return proto.CompactTextString(m) }
func (*ApiUpdateVfsFileContentResult) ProtoMessage()               {}
func (*ApiUpdateVfsFileContentResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ApiUpdateVfsFileContentResult) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetVfsFileContentUpdateStateArgs struct {
	ClientId         *string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	OperationId      *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApiGetVfsFileContentUpdateStateArgs) Reset()         { *m = ApiGetVfsFileContentUpdateStateArgs{} }
func (m *ApiGetVfsFileContentUpdateStateArgs) String() string { return proto.CompactTextString(m) }
func (*ApiGetVfsFileContentUpdateStateArgs) ProtoMessage()    {}
func (*ApiGetVfsFileContentUpdateStateArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{27}
}

func (m *ApiGetVfsFileContentUpdateStateArgs) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ApiGetVfsFileContentUpdateStateArgs) GetOperationId() string {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return ""
}

type ApiGetVfsFileContentUpdateStateResult struct {
	State            *ApiGetVfsFileContentUpdateStateResult_State `protobuf:"varint,1,opt,name=state,enum=ApiGetVfsFileContentUpdateStateResult_State" json:"state,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *ApiGetVfsFileContentUpdateStateResult) Reset()         { *m = ApiGetVfsFileContentUpdateStateResult{} }
func (m *ApiGetVfsFileContentUpdateStateResult) String() string { return proto.CompactTextString(m) }
func (*ApiGetVfsFileContentUpdateStateResult) ProtoMessage()    {}
func (*ApiGetVfsFileContentUpdateStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{28}
}

func (m *ApiGetVfsFileContentUpdateStateResult) GetState() ApiGetVfsFileContentUpdateStateResult_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ApiGetVfsFileContentUpdateStateResult_RUNNING
}

type ApiListKnownEncodingsResult struct {
	Encodings        []string `protobuf:"bytes,1,rep,name=encodings" json:"encodings,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApiListKnownEncodingsResult) Reset()                    { *m = ApiListKnownEncodingsResult{} }
func (m *ApiListKnownEncodingsResult) String() string            { return proto.CompactTextString(m) }
func (*ApiListKnownEncodingsResult) ProtoMessage()               {}
func (*ApiListKnownEncodingsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ApiListKnownEncodingsResult) GetEncodings() []string {
	if m != nil {
		return m.Encodings
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiFile)(nil), "ApiFile")
	proto.RegisterType((*ApiAff4ObjectRepresentation)(nil), "ApiAff4ObjectRepresentation")
	proto.RegisterType((*ApiAff4ObjectType)(nil), "ApiAff4ObjectType")
	proto.RegisterType((*ApiAff4ObjectAttribute)(nil), "ApiAff4ObjectAttribute")
	proto.RegisterType((*ApiAff4ObjectAttributeValue)(nil), "ApiAff4ObjectAttributeValue")
	proto.RegisterType((*ApiVfsTimelineItem)(nil), "ApiVfsTimelineItem")
	proto.RegisterType((*ApiGetFileDetailsArgs)(nil), "ApiGetFileDetailsArgs")
	proto.RegisterType((*ApiGetFileDetailsResult)(nil), "ApiGetFileDetailsResult")
	proto.RegisterType((*ApiListFilesArgs)(nil), "ApiListFilesArgs")
	proto.RegisterType((*ApiListFilesResult)(nil), "ApiListFilesResult")
	proto.RegisterType((*ApiGetVfsFilesArchiveArgs)(nil), "ApiGetVfsFilesArchiveArgs")
	proto.RegisterType((*ApiGetFileTextArgs)(nil), "ApiGetFileTextArgs")
	proto.RegisterType((*ApiGetFileTextResult)(nil), "ApiGetFileTextResult")
	proto.RegisterType((*ApiGetFileBlobArgs)(nil), "ApiGetFileBlobArgs")
	proto.RegisterType((*ApiGetFileVersionTimesArgs)(nil), "ApiGetFileVersionTimesArgs")
	proto.RegisterType((*ApiGetFileVersionTimesResult)(nil), "ApiGetFileVersionTimesResult")
	proto.RegisterType((*ApiGetFileDownloadCommandArgs)(nil), "ApiGetFileDownloadCommandArgs")
	proto.RegisterType((*ApiGetFileDownloadCommandResult)(nil), "ApiGetFileDownloadCommandResult")
	proto.RegisterType((*ApiCreateVfsRefreshOperationArgs)(nil), "ApiCreateVfsRefreshOperationArgs")
	proto.RegisterType((*ApiGetVfsTimelineArgs)(nil), "ApiGetVfsTimelineArgs")
	proto.RegisterType((*ApiGetVfsTimelineResult)(nil), "ApiGetVfsTimelineResult")
	proto.RegisterType((*ApiGetVfsTimelineAsCsvArgs)(nil), "ApiGetVfsTimelineAsCsvArgs")
	proto.RegisterType((*ApiCreateVfsRefreshOperationResult)(nil), "ApiCreateVfsRefreshOperationResult")
	proto.RegisterType((*ApiGetVfsRefreshOperationStateArgs)(nil), "ApiGetVfsRefreshOperationStateArgs")
	proto.RegisterType((*ApiGetVfsRefreshOperationStateResult)(nil), "ApiGetVfsRefreshOperationStateResult")
	proto.RegisterType((*ApiUpdateVfsFileContentArgs)(nil), "ApiUpdateVfsFileContentArgs")
	proto.RegisterType((*ApiUpdateVfsFileContentResult)(nil), "ApiUpdateVfsFileContentResult")
	proto.RegisterType((*ApiGetVfsFileContentUpdateStateArgs)(nil), "ApiGetVfsFileContentUpdateStateArgs")
	proto.RegisterType((*ApiGetVfsFileContentUpdateStateResult)(nil), "ApiGetVfsFileContentUpdateStateResult")
	proto.RegisterType((*ApiListKnownEncodingsResult)(nil), "ApiListKnownEncodingsResult")
	proto.RegisterEnum("ApiVfsTimelineItem_FileActionType", ApiVfsTimelineItem_FileActionType_name, ApiVfsTimelineItem_FileActionType_value)
	proto.RegisterEnum("ApiGetFileTextArgs_Encoding", ApiGetFileTextArgs_Encoding_name, ApiGetFileTextArgs_Encoding_value)
	proto.RegisterEnum("ApiGetVfsRefreshOperationStateResult_State", ApiGetVfsRefreshOperationStateResult_State_name, ApiGetVfsRefreshOperationStateResult_State_value)
	proto.RegisterEnum("ApiGetVfsFileContentUpdateStateResult_State", ApiGetVfsFileContentUpdateStateResult_State_name, ApiGetVfsFileContentUpdateStateResult_State_value)
}

func init() { proto.RegisterFile("grr/proto/api/vfs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0x4d, 0x53, 0x1b, 0xc9,
	0xf9, 0x5f, 0x01, 0x02, 0xa9, 0x85, 0xd9, 0x76, 0x9b, 0x5d, 0x0b, 0x8c, 0xd7, 0xed, 0xb1, 0xbd,
	0xc6, 0x6f, 0x83, 0x10, 0x02, 0xec, 0x5d, 0xef, 0xbf, 0xfe, 0x33, 0x92, 0xc0, 0x5a, 0x63, 0xf0,
	0x8e, 0x80, 0xa4, 0x9c, 0x4a, 0xb4, 0x83, 0xd4, 0x42, 0xbd, 0x3b, 0x9a, 0x51, 0xa6, 0x5b, 0x60,
	0xf6, 0x03, 0xe4, 0x90, 0x54, 0xe5, 0x23, 0xe4, 0x94, 0x53, 0x92, 0xaa, 0x1c, 0x53, 0xb5, 0xb9,
	0xe6, 0x9e, 0x8f, 0x90, 0x54, 0x72, 0xc9, 0x47, 0x48, 0xa5, 0x72, 0x48, 0xf5, 0x33, 0x2f, 0xd2,
	0x80, 0x4c, 0xd6, 0x55, 0xde, 0xe2, 0x90, 0x93, 0x7e, 0xa3, 0xe7, 0xbd, 0xfb, 0x79, 0x9e, 0x7e,
	0xba, 0xd1, 0xd5, 0x43, 0xdf, 0x5f, 0xea, 0xf9, 0x9e, 0xf4, 0x96, 0xec, 0x1e, 0x5f, 0x3a, 0x6a,
	0x0b, 0x1d, 0xbe, 0xe6, 0xe7, 0x0e, 0x3d, 0xef, 0xd0, 0x61, 0x01, 0xed, 0xa0, 0xdf, 0x5e, 0xb2,
	0xdd, 0x93, 0x90, 0x34, 0x3b, 0x90, 0xf9, 0xca, 0x3b, 0x88, 0x04, 0xf2, 0x83, 0x7f, 0x05, 0xeb,
	0xda, 0xae, 0xe4, 0xcd, 0x80, 0xa2, 0xfd, 0x25, 0x8d, 0xa6, 0x8c, 0x1e, 0xdf, 0xe0, 0x0e, 0x23,
	0x1f, 0xa3, 0x09, 0xd7, 0xee, 0xb2, 0x7c, 0x8a, 0xa6, 0x16, 0xb3, 0x26, 0xf9, 0xdb, 0xbf, 0xff,
	0xfe, 0xa7, 0xd4, 0x34, 0x41, 0x8a, 0x46, 0x15, 0x41, 0xb7, 0x80, 0x4e, 0x0c, 0x34, 0xd1, 0xb3,
	0x65, 0x27, 0x3f, 0x06, 0x7c, 0x8f, 0x80, 0xef, 0x2e, 0xb9, 0x03, 0x7c, 0x8a, 0x40, 0x85, 0xb4,
	0x7d, 0xc9, 0xdd, 0x43, 0xda, 0xf6, 0xbd, 0x2e, 0x95, 0x1d, 0x46, 0xf7, 0x37, 0xea, 0xd4, 0xf7,
	0x3c, 0xa9, 0x5b, 0x20, 0xaa, 0x4c, 0xc9, 0x93, 0x1e, 0xcb, 0x8f, 0x8f, 0x30, 0xa5, 0x08, 0xba,
	0x05, 0x74, 0xf2, 0x29, 0x9a, 0x10, 0xd2, 0x96, 0xf9, 0x1c, 0x4d, 0x2d, 0xe6, 0x8a, 0x48, 0xaf,
	0x4b, 0x5b, 0x56, 0x5d, 0xe9, 0x9f, 0x98, 0xd7, 0x40, 0xe6, 0x03, 0x72, 0x05, 0x64, 0x9a, 0x3e,
	0xb3, 0x25, 0xf7, 0x5c, 0x2a, 0x39, 0xf8, 0xa9, 0x84, 0xc8, 0x3e, 0x1a, 0xb7, 0x0f, 0x59, 0x3e,
	0x4d, 0x53, 0x8b, 0x13, 0x66, 0x05, 0xf8, 0xff, 0x0f, 0xe5, 0xac, 0xca, 0x46, 0xc5, 0x96, 0x4c,
	0x31, 0x92, 0x25, 0x10, 0xb6, 0x0f, 0x19, 0x5d, 0x3c, 0xee, 0x30, 0x97, 0xb6, 0xd5, 0xa7, 0x77,
	0xf0, 0x15, 0x6b, 0x4a, 0x7a, 0x6c, 0x0b, 0xda, 0xef, 0xb5, 0x6c, 0xc9, 0x5a, 0x94, 0xbb, 0x74,
	0xd3, 0xb2, 0xee, 0xe9, 0x96, 0x52, 0x48, 0x9e, 0xa3, 0x69, 0x2e, 0x1a, 0x2d, 0xee, 0xb3, 0xa6,
	0xf4, 0xfc, 0x93, 0xfc, 0x24, 0x4d, 0x2d, 0x66, 0xcc, 0x45, 0x30, 0xa0, 0x11, 0xba, 0xeb, 0xf7,
	0x19, 0xe5, 0x6d, 0x88, 0x1b, 0x14, 0x72, 0x41, 0x6d, 0x1a, 0xb3, 0xeb, 0x56, 0x8e, 0x8b, 0x4a,
	0xf4, 0xa5, 0x22, 0xec, 0xd8, 0xa2, 0x93, 0x9f, 0x82, 0x08, 0xd3, 0xfa, 0x33, 0x5b, 0x74, 0x4c,
	0x0a, 0xba, 0xe6, 0x49, 0x5e, 0x7d, 0xd1, 0x23, 0xdb, 0xe9, 0x33, 0x41, 0xbd, 0x81, 0x4a, 0xdd,
	0x02, 0x21, 0xc2, 0xd1, 0x8c, 0x63, 0x0b, 0xd9, 0x68, 0x7a, 0x8e, 0xc3, 0x9a, 0x92, 0xb5, 0xf2,
	0x19, 0x08, 0xd6, 0x04, 0xf9, 0xa7, 0xc9, 0x60, 0x1f, 0x6d, 0xd9, 0x42, 0xc2, 0x02, 0x05, 0x6e,
	0xa9, 0x00, 0x63, 0xc1, 0xc1, 0x56, 0x35, 0x1d, 0xce, 0x5c, 0xa9, 0x5b, 0x97, 0x94, 0xe6, 0x72,
	0x44, 0x27, 0x2d, 0x74, 0x25, 0x69, 0xaa, 0x21, 0xf8, 0x37, 0x2c, 0x8f, 0xc0, 0x5e, 0x09, 0xec,
	0xe9, 0xe4, 0x61, 0x9d, 0x7f, 0xc3, 0x86, 0x1d, 0xa5, 0x4e, 0x6c, 0x93, 0xcb, 0xa4, 0x45, 0xdd,
	0xba, 0x9c, 0xb0, 0xa0, 0x44, 0xc9, 0x17, 0x68, 0xaa, 0xc5, 0xa4, 0xcd, 0x1d, 0x91, 0xcf, 0xc2,
	0x82, 0x2c, 0xe8, 0x46, 0x8f, 0x1b, 0xed, 0x76, 0x69, 0x07, 0x76, 0xc5, 0x62, 0x3d, 0x9f, 0x09,
	0xe6, 0x4a, 0xd8, 0x6d, 0x73, 0x0e, 0xec, 0x5e, 0x21, 0x97, 0x77, 0x23, 0x7b, 0xa1, 0xb4, 0x6e,
	0x45, 0x7a, 0xb4, 0x26, 0xba, 0x76, 0x8e, 0x0a, 0x52, 0x41, 0x69, 0x95, 0x69, 0x22, 0x9f, 0xa2,
	0xe3, 0x8b, 0xb9, 0x22, 0x49, 0xda, 0xdb, 0x3d, 0xe9, 0x31, 0x73, 0x1e, 0xac, 0xcc, 0x12, 0xa2,
	0xac, 0x38, 0x5c, 0x48, 0x88, 0x50, 0x09, 0xe9, 0x56, 0x20, 0xac, 0xfd, 0x3a, 0x85, 0x2e, 0x9f,
	0x11, 0x24, 0xab, 0x89, 0x82, 0xba, 0x09, 0x6a, 0xae, 0x91, 0x39, 0xa5, 0x46, 0xfd, 0x1f, 0x2d,
	0x54, 0xd3, 0x96, 0xec, 0x10, 0x32, 0x23, 0xa8, 0xaf, 0x1f, 0x22, 0x64, 0x4b, 0xe9, 0xf3, 0x83,
	0xbe, 0x64, 0x22, 0x3f, 0x06, 0x7e, 0x5d, 0x4d, 0xfa, 0x65, 0x44, 0x74, 0xf3, 0x06, 0x68, 0x9d,
	0x23, 0x57, 0x87, 0x9d, 0x1b, 0x88, 0xeb, 0xd6, 0x90, 0x2e, 0xed, 0x77, 0x29, 0xf4, 0xe1, 0x68,
	0x3d, 0x64, 0x2d, 0xe1, 0xab, 0x06, 0x5a, 0x17, 0xc8, 0xfc, 0x69, 0x5f, 0x63, 0x65, 0x91, 0xb3,
	0xaf, 0xd0, 0x64, 0x90, 0x9f, 0xa1, 0xa3, 0x0b, 0x6f, 0x70, 0x74, 0x5f, 0x31, 0x99, 0xb7, 0x41,
	0xef, 0x47, 0x64, 0x41, 0xe9, 0x4d, 0xe6, 0xf5, 0x90, 0xe6, 0x50, 0xa3, 0xf6, 0xcf, 0xd4, 0xa9,
	0xbd, 0x4b, 0x6a, 0x53, 0x3e, 0x43, 0x17, 0x19, 0xe1, 0xb3, 0xfa, 0x7f, 0x94, 0xcf, 0xd0, 0x55,
	0xfe, 0x3f, 0x68, 0x0c, 0x63, 0x90, 0xbb, 0x3a, 0x88, 0x2d, 0x26, 0x6b, 0x05, 0xf6, 0x48, 0xf5,
	0x85, 0xb3, 0x2a, 0xa0, 0x05, 0x34, 0x50, 0x1a, 0x7c, 0x84, 0x06, 0x96, 0x2b, 0xce, 0xea, 0x41,
	0x47, 0xd6, 0xa3, 0x8e, 0xac, 0x1b, 0xee, 0x89, 0xb9, 0x02, 0x9a, 0x1f, 0x0d, 0x05, 0x7b, 0x46,
	0x9d, 0xd0, 0xef, 0x5f, 0xda, 0x64, 0x12, 0xc2, 0x29, 0x3b, 0xb6, 0x10, 0x56, 0xa0, 0x57, 0xfb,
	0xed, 0x18, 0x22, 0x46, 0x8f, 0xef, 0xb7, 0xc5, 0x2e, 0xef, 0x32, 0x87, 0xbb, 0xac, 0x26, 0x59,
	0x97, 0x6c, 0xa2, 0xac, 0xf2, 0x4f, 0x48, 0xbb, 0xdb, 0x83, 0xb0, 0x27, 0xcc, 0x7b, 0x60, 0xe5,
	0x56, 0xd2, 0xff, 0x59, 0x65, 0x92, 0x1d, 0x31, 0x37, 0x28, 0x3e, 0xe0, 0xd7, 0xad, 0x81, 0x2c,
	0x59, 0x42, 0x59, 0x55, 0x2f, 0x8d, 0xa1, 0x46, 0x9e, 0xec, 0xc2, 0x8a, 0xa0, 0x5b, 0x19, 0xc5,
	0xf4, 0x52, 0x75, 0xec, 0x3d, 0x34, 0x69, 0x37, 0x55, 0xc5, 0x40, 0xc8, 0x33, 0x45, 0x4d, 0x3f,
	0xeb, 0x9e, 0xae, 0x24, 0x0d, 0xe0, 0x82, 0xc2, 0x89, 0xcb, 0x33, 0x68, 0xb3, 0xcd, 0xa0, 0x43,
	0x43, 0x7b, 0x0f, 0x95, 0x69, 0x15, 0x34, 0x93, 0x14, 0x22, 0x18, 0x4d, 0xbf, 0xd8, 0xa9, 0xd4,
	0x36, 0x6a, 0x65, 0x63, 0xb7, 0xb6, 0xb3, 0x8d, 0xdf, 0x23, 0x08, 0x4d, 0x1a, 0xe5, 0x72, 0xb5,
	0x5e, 0xc7, 0x29, 0x32, 0x8b, 0xf0, 0x8b, 0xea, 0xae, 0x51, 0x31, 0x76, 0x8d, 0x46, 0xf9, 0x99,
	0xb1, 0xbd, 0x59, 0xad, 0xe0, 0x31, 0xed, 0x1f, 0x29, 0xf4, 0x81, 0xd1, 0xe3, 0x9b, 0x4c, 0x2a,
	0x65, 0x95, 0xa0, 0xf2, 0x0d, 0xff, 0x50, 0x90, 0xa7, 0x28, 0x1b, 0x34, 0xb4, 0x06, 0x6f, 0x85,
	0x79, 0x12, 0x56, 0x0c, 0xca, 0x19, 0x3d, 0x5e, 0x06, 0x5a, 0xad, 0x45, 0x50, 0x80, 0x28, 0x6f,
	0xe9, 0x56, 0xa6, 0x19, 0xfd, 0xfb, 0xd6, 0xab, 0xf4, 0xe5, 0xf0, 0xfe, 0x8c, 0x9f, 0xd3, 0x8b,
	0xa3, 0xfc, 0x12, 0x3d, 0xd6, 0xe4, 0xed, 0x13, 0x75, 0x58, 0x1e, 0x77, 0x78, 0xb3, 0x43, 0x8f,
	0x98, 0x2f, 0x60, 0x99, 0x3c, 0xea, 0x33, 0xe9, 0x73, 0x76, 0xc4, 0x86, 0x37, 0x4e, 0xfb, 0x1a,
	0x5d, 0x3d, 0x13, 0xa9, 0xc5, 0x44, 0xdf, 0x91, 0xe4, 0x25, 0x9a, 0x50, 0x8e, 0x40, 0x98, 0xb9,
	0x62, 0x46, 0x0f, 0xcf, 0x75, 0xb3, 0x08, 0x1e, 0x3c, 0x24, 0xf7, 0xe3, 0x2e, 0xd9, 0xf4, 0x5c,
	0x69, 0x73, 0x57, 0x59, 0xe5, 0x6e, 0xd3, 0xe9, 0xb7, 0x14, 0xb2, 0x1d, 0x67, 0xd0, 0x3e, 0x41,
	0x93, 0xf6, 0x87, 0x71, 0x84, 0x8d, 0x1e, 0xdf, 0xe2, 0x02, 0xcc, 0x5d, 0xc8, 0x92, 0x16, 0xd0,
	0xa4, 0xd7, 0x6e, 0x0b, 0x26, 0x61, 0x3d, 0xc7, 0xcd, 0x3c, 0x70, 0x13, 0x82, 0xeb, 0xd1, 0x94,
	0x11, 0x90, 0x75, 0x2b, 0xe4, 0x23, 0x9f, 0xa2, 0x74, 0xd3, 0xeb, 0xbb, 0x32, 0x3f, 0x01, 0x02,
	0x77, 0x40, 0xe0, 0x06, 0xb9, 0xfe, 0xc2, 0x7e, 0x4d, 0xdd, 0x7e, 0xf7, 0x80, 0xf9, 0xaa, 0x0e,
	0xb9, 0x64, 0x5d, 0xa1, 0x96, 0xb9, 0xcd, 0x64, 0xb3, 0xa3, 0x5b, 0x81, 0x0c, 0xe1, 0x68, 0xb2,
	0xcd, 0x1d, 0xc9, 0x7c, 0x98, 0x1b, 0xb2, 0xe6, 0x17, 0x20, 0xfd, 0x9c, 0xd4, 0x2c, 0x26, 0xfb,
	0xbe, 0x4b, 0x3d, 0xd7, 0x39, 0xa1, 0x3e, 0x2c, 0xb8, 0xa0, 0xc7, 0x1d, 0x4f, 0x30, 0x2a, 0xa4,
	0xaf, 0xdc, 0xf0, 0x13, 0x07, 0x4b, 0xb4, 0xc6, 0x82, 0x1e, 0xf2, 0x23, 0xe6, 0x52, 0xd1, 0x3f,
	0x08, 0xf8, 0x74, 0x2b, 0x34, 0x40, 0x5e, 0x21, 0x1c, 0x4d, 0x05, 0x9c, 0x89, 0x86, 0xd2, 0x1c,
	0xce, 0x12, 0x4b, 0x60, 0xf4, 0x1e, 0xb9, 0x5b, 0x6b, 0x53, 0xe9, 0xf7, 0xd9, 0xc3, 0xc0, 0xec,
	0x10, 0x37, 0xb5, 0x7d, 0xa6, 0x12, 0xa4, 0xef, 0xbb, 0xea, 0x28, 0x7d, 0x7f, 0x88, 0xb4, 0xe3,
	0x3a, 0x27, 0xda, 0x4b, 0x68, 0x1f, 0xf1, 0xc6, 0x85, 0x19, 0xf2, 0x09, 0x4a, 0x43, 0xd8, 0xe1,
	0x61, 0x37, 0x48, 0x91, 0x91, 0x47, 0x9c, 0xda, 0x02, 0x75, 0xc4, 0x81, 0x88, 0xf6, 0xf3, 0x14,
	0x9a, 0x0b, 0x32, 0x6f, 0xbf, 0x2d, 0xc2, 0x6c, 0x68, 0x76, 0xf8, 0x11, 0xbb, 0x80, 0xa4, 0xd0,
	0xbe, 0xcd, 0x40, 0x7c, 0x61, 0x19, 0xec, 0xb2, 0xd7, 0xf2, 0x22, 0x52, 0xf3, 0x93, 0x53, 0xa9,
	0x99, 0x38, 0x81, 0x02, 0xca, 0x60, 0xae, 0x82, 0xa1, 0x78, 0x90, 0xa4, 0x9f, 0xa1, 0x49, 0x87,
	0xb9, 0x87, 0xb2, 0x73, 0x3a, 0x4b, 0xe1, 0xc4, 0x8d, 0xb3, 0xf4, 0xe0, 0x44, 0x32, 0x31, 0xb4,
	0xd1, 0xa1, 0x10, 0xf9, 0x11, 0xca, 0x30, 0xb7, 0xe9, 0xa9, 0xc2, 0x85, 0x44, 0x9d, 0x09, 0x0e,
	0xde, 0x53, 0x0b, 0xa2, 0x57, 0x43, 0x9e, 0xe4, 0xf0, 0x11, 0x49, 0x26, 0x47, 0xca, 0x58, 0x61,
	0xb2, 0x8b, 0x4d, 0x7e, 0x1f, 0x5d, 0xec, 0x5f, 0x13, 0x28, 0x13, 0xf9, 0xa6, 0x3a, 0xbe, 0x69,
	0xd4, 0xab, 0x6b, 0xa5, 0x46, 0x79, 0xa7, 0x52, 0x2d, 0xe3, 0xf7, 0x48, 0x06, 0x4d, 0x98, 0xb5,
	0xcd, 0x55, 0x9c, 0x22, 0x97, 0x50, 0x56, 0xa1, 0x67, 0xcf, 0xeb, 0xe5, 0x3a, 0x1e, 0x23, 0x59,
	0x94, 0x2e, 0xbf, 0x2c, 0xac, 0xac, 0xe3, 0x71, 0x75, 0x2a, 0x94, 0x5f, 0x2e, 0x17, 0x0a, 0x6b,
	0x78, 0x22, 0xc2, 0xc5, 0x35, 0x9c, 0x0e, 0xf1, 0x72, 0xa9, 0x80, 0x27, 0x43, 0x5c, 0x5c, 0x2d,
	0xe0, 0xa9, 0x18, 0x2f, 0xe3, 0x4c, 0x8c, 0x8b, 0x38, 0x1b, 0xe3, 0x15, 0x8c, 0x62, 0x5c, 0xc2,
	0xb9, 0x18, 0xaf, 0xe2, 0xe9, 0x18, 0xaf, 0xe1, 0x4b, 0x31, 0x5e, 0xc7, 0x33, 0x31, 0x7e, 0x8c,
	0xdf, 0x0f, 0x5c, 0x2b, 0x15, 0x4b, 0x18, 0x87, 0x70, 0x65, 0x1d, 0x5f, 0x0e, 0xe0, 0x6a, 0xa1,
	0x80, 0x49, 0x00, 0xd7, 0x57, 0xd6, 0xf1, 0x95, 0x10, 0xae, 0xaf, 0xe2, 0xd9, 0x00, 0x3e, 0x5e,
	0x2d, 0xe0, 0x0f, 0x22, 0x58, 0xc4, 0x1f, 0x46, 0x70, 0x15, 0x5f, 0x8d, 0xe0, 0x1a, 0xce, 0x47,
	0x70, 0x1d, 0xcf, 0x85, 0x70, 0xad, 0x80, 0xe7, 0x23, 0xb8, 0x8c, 0xaf, 0x45, 0xb0, 0x88, 0x17,
	0x22, 0xb8, 0x82, 0xaf, 0x47, 0xb0, 0x84, 0x3f, 0x8a, 0xe0, 0x2a, 0xbe, 0x11, 0xc1, 0x35, 0x4c,
	0x23, 0xf8, 0x04, 0xdf, 0x0c, 0xe1, 0x7a, 0x09, 0x6b, 0x11, 0x5c, 0xc5, 0xb7, 0x02, 0xf8, 0x64,
	0xa5, 0x88, 0x6f, 0x87, 0xb0, 0xf4, 0x04, 0xdf, 0x09, 0xe1, 0x6a, 0x01, 0x7f, 0xac, 0x36, 0xac,
	0x56, 0xd9, 0x36, 0xf0, 0x5d, 0xb5, 0x24, 0xd6, 0xce, 0x6e, 0x63, 0x79, 0x05, 0x2f, 0x2a, 0xbc,
	0xb7, 0xbb, 0xd1, 0x58, 0x5e, 0xc3, 0xf7, 0xd4, 0x46, 0x06, 0xb8, 0x61, 0x56, 0xf1, 0xfd, 0xa1,
	0xcf, 0xad, 0x2a, 0x7e, 0x10, 0x71, 0xae, 0x14, 0xf1, 0xc3, 0x88, 0xb4, 0x52, 0x54, 0x9c, 0x8f,
	0x86, 0x3e, 0xb7, 0xaa, 0x58, 0x57, 0x46, 0xd5, 0xe7, 0x3a, 0x5e, 0x8a, 0xe0, 0x63, 0x5c, 0x88,
	0x98, 0x1e, 0x37, 0xea, 0xb5, 0x4d, 0xbc, 0x4c, 0xa6, 0x51, 0x66, 0x6f, 0x2f, 0xcc, 0xa6, 0x22,
	0x99, 0x41, 0xe8, 0xd5, 0x56, 0xcd, 0x0c, 0xbf, 0x57, 0xb4, 0x5f, 0xa5, 0xd0, 0x6c, 0xb2, 0x56,
	0xe2, 0xf6, 0x38, 0xa5, 0xba, 0x36, 0x73, 0x65, 0xd8, 0x3c, 0xe2, 0x7b, 0x98, 0x4a, 0xf4, 0x90,
	0x94, 0x2c, 0x9a, 0x48, 0x80, 0x7c, 0x8e, 0x90, 0xf4, 0xa4, 0xed, 0x04, 0xd7, 0xa2, 0x31, 0xa8,
	0xe9, 0x07, 0x20, 0x7e, 0x87, 0xdc, 0x82, 0x89, 0x54, 0x51, 0xa9, 0x38, 0x7d, 0x41, 0xe2, 0x2e,
	0xd4, 0xb8, 0xaa, 0x0e, 0xc5, 0xa0, 0x6e, 0x41, 0xda, 0x5f, 0xc7, 0x86, 0xbb, 0x9b, 0xe9, 0x78,
	0x07, 0xff, 0x63, 0xdd, 0x2d, 0xd1, 0x80, 0xd2, 0xdf, 0x47, 0x03, 0xfa, 0x45, 0x0a, 0xcd, 0x0f,
	0x96, 0x78, 0x3f, 0xe0, 0x56, 0xb3, 0xec, 0x45, 0xcc, 0x38, 0x1a, 0x43, 0x0b, 0xa3, 0x9d, 0x09,
	0x13, 0xb3, 0x8a, 0xd2, 0xe0, 0x3a, 0x9c, 0xdb, 0x13, 0xd1, 0x78, 0x90, 0x5c, 0x8b, 0xf9, 0xe1,
	0xa3, 0x3b, 0x0e, 0x5f, 0x49, 0xa9, 0x5b, 0xaa, 0xfa, 0xd5, 0x7e, 0x99, 0x42, 0xd7, 0x87, 0x86,
	0x47, 0xef, 0xd8, 0x75, 0x3c, 0xbb, 0x55, 0xf6, 0xba, 0x5d, 0xdb, 0x6d, 0x5d, 0x44, 0xdc, 0x87,
	0xe8, 0xc6, 0x1b, 0xfd, 0x09, 0x43, 0xaf, 0xa8, 0x9a, 0x84, 0x3f, 0x42, 0x7f, 0xee, 0x83, 0xc6,
	0xdb, 0x44, 0x0b, 0x6a, 0x12, 0x48, 0x6a, 0x9b, 0x5b, 0xa1, 0x38, 0x95, 0x1d, 0x2e, 0x06, 0xd5,
	0x09, 0x74, 0xed, 0xcf, 0x63, 0x88, 0x2a, 0xff, 0x7d, 0x66, 0x4b, 0xb6, 0xdf, 0x16, 0x16, 0x6b,
	0xfb, 0x4c, 0x74, 0x76, 0x7a, 0xcc, 0x87, 0x69, 0xed, 0x1d, 0x04, 0xbf, 0x73, 0x36, 0xf8, 0x78,
	0xf0, 0x36, 0x36, 0x36, 0x4a, 0xc1, 0xd3, 0x98, 0xba, 0x9c, 0xc3, 0x6b, 0x58, 0xdb, 0x73, 0x5a,
	0xcc, 0x57, 0x8e, 0x1f, 0xa8, 0x41, 0x0e, 0xdc, 0x51, 0x25, 0x30, 0xa8, 0xbf, 0xcf, 0x50, 0xb6,
	0x6b, 0xbf, 0x6e, 0xb4, 0x58, 0x4f, 0x76, 0xc2, 0xbb, 0x44, 0xdc, 0x8f, 0x5e, 0xd8, 0xaf, 0x79,
	0xb7, 0xdf, 0xa5, 0x3e, 0x6b, 0xf6, 0x83, 0x9d, 0x06, 0x36, 0xdd, 0xca, 0x74, 0xed, 0xd7, 0x15,
	0x05, 0xc9, 0x8f, 0x51, 0xce, 0xf5, 0x24, 0x6f, 0x9f, 0x34, 0xfa, 0x82, 0xf9, 0x50, 0x87, 0x19,
	0xf3, 0x29, 0x28, 0x58, 0x23, 0xa5, 0x1f, 0x74, 0x98, 0xec, 0x28, 0xfb, 0xaa, 0x96, 0xa3, 0x55,
	0xa0, 0xa2, 0xe3, 0xf5, 0x9d, 0x16, 0x0d, 0xe4, 0x80, 0xa6, 0x64, 0xa9, 0xe7, 0xab, 0xbf, 0x74,
	0x0b, 0x05, 0x84, 0x3d, 0xc1, 0x7c, 0xed, 0x67, 0xf1, 0x95, 0x6b, 0xe8, 0x12, 0x78, 0x11, 0x39,
	0xf4, 0x93, 0xe8, 0x42, 0x34, 0xe4, 0x47, 0x98, 0x3b, 0xe5, 0xe4, 0xb8, 0x7b, 0x65, 0xc4, 0x95,
	0x75, 0x70, 0x9d, 0x18, 0xdc, 0x98, 0x41, 0x26, 0x9e, 0x7b, 0x07, 0x9d, 0x62, 0x38, 0x50, 0x51,
	0x16, 0x47, 0x17, 0x11, 0xed, 0x4f, 0x91, 0x76, 0x5e, 0x1e, 0x87, 0x81, 0x3f, 0x47, 0xd3, 0xf1,
	0xa6, 0x0e, 0xfc, 0x1a, 0xbc, 0x50, 0x76, 0x18, 0xe5, 0xad, 0xe8, 0x18, 0x0a, 0x93, 0x6f, 0x90,
	0x06, 0xba, 0x95, 0x8b, 0x71, 0xad, 0xa5, 0xfd, 0x3e, 0x05, 0x36, 0x83, 0x05, 0x38, 0x6d, 0xb0,
	0x2e, 0x6d, 0x39, 0x62, 0xdb, 0xc7, 0xde, 0x76, 0x21, 0xde, 0xa9, 0xc7, 0xdf, 0xa6, 0xd0, 0xed,
	0xf3, 0x3d, 0x0e, 0xd7, 0xc9, 0x45, 0x69, 0xa1, 0x3e, 0xc1, 0xdc, 0x4c, 0xf1, 0x81, 0xfe, 0x5d,
	0xa4, 0xe0, 0x11, 0x9a, 0x25, 0x0f, 0x77, 0xd0, 0x72, 0x8e, 0x7b, 0x81, 0x19, 0x4d, 0x43, 0x69,
	0x10, 0x26, 0x39, 0x34, 0x65, 0xed, 0x6d, 0x6f, 0xd7, 0xb6, 0x37, 0xf1, 0x7b, 0x6a, 0x5a, 0xd9,
	0xa8, 0x6d, 0xd7, 0xea, 0xcf, 0xaa, 0x15, 0x9c, 0xd2, 0x7e, 0x13, 0x3c, 0x7a, 0xed, 0xc1, 0xd3,
	0x73, 0x78, 0xd5, 0x2a, 0x07, 0x43, 0xc6, 0x3b, 0x48, 0xb8, 0x17, 0x67, 0x13, 0xae, 0x00, 0xd2,
	0xf7, 0xc9, 0xe2, 0xa8, 0x2e, 0x05, 0x0f, 0xf2, 0x6f, 0xec, 0x51, 0xda, 0xd7, 0x70, 0xa0, 0x8c,
	0xf2, 0x35, 0x5c, 0xe1, 0xcf, 0x47, 0xee, 0xeb, 0x5d, 0x30, 0x79, 0x93, 0xdc, 0x48, 0xee, 0x6b,
	0xf0, 0xdc, 0x7e, 0x5e, 0x22, 0xde, 0x4a, 0xdc, 0x40, 0x43, 0x53, 0x81, 0xf9, 0x77, 0x95, 0x89,
	0xef, 0xd2, 0xe3, 0x3f, 0xa6, 0xd0, 0x9d, 0xff, 0xe2, 0xf1, 0xe8, 0x4c, 0x7c, 0xa8, 0x7f, 0x27,
	0xb1, 0x30, 0x15, 0x13, 0x47, 0x62, 0x22, 0x15, 0xcf, 0xfa, 0xf7, 0x16, 0x99, 0xf8, 0x25, 0x24,
	0xe2, 0x16, 0x17, 0xf2, 0xb9, 0xeb, 0x1d, 0xbb, 0xd1, 0x7d, 0x2d, 0x1a, 0x4a, 0x0c, 0x94, 0x8d,
	0x6e, 0x8c, 0x41, 0x87, 0xcd, 0x9a, 0xb7, 0xc0, 0x91, 0xeb, 0xe4, 0xda, 0xe9, 0x67, 0x84, 0xf8,
	0xca, 0x29, 0x74, 0x6b, 0x20, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x01, 0xec, 0x2e,
	0xe2, 0x1a, 0x00, 0x00,
}
